### ISSUE TITLE
base64url should not require padding

### ISSUE THREAD

**Issue by maticmeznar** [go-playground/validator#1002]
- [X] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [X] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10:

v10

### Issue, Question or Enhancement:

base64url validator is faulty. It requires padding even though padding is optional in URL safe encoding.

### Code sample, to showcase or reproduce:

```
package main

import (
	"encoding/base64"
	"fmt"

	"github.com/go-playground/validator/v10"
)

func main() {
	msg := "hello"
	msgB64url := base64.RawURLEncoding.EncodeToString([]byte(msg))

	val := validator.New()

	fmt.Println(msgB64url) // prints "aGVsbG8"
	fmt.Println(val.Var(msgB64url, "base64url"))
}
```

**Comment by zemzale** [comment]
@maticmeznar Could you provide a simple example of the faulty validation?

**Comment by zemzale** [comment]
Will see what can be done about this, or feel free to open a PR yourself, since this indeed is a bug.

**Comment by yasoobh** [comment]
@zemzale - i have opened a [pull request](https://github.com/go-playground/validator/pull/1024) for this. Can you please check?
