### ISSUE TITLE
XOR validation question

### ISSUE THREAD

**Issue by khawkinson** [go-playground/validator#1004]
- [ x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:
I'm attempting to do XOR validations with structs.  Works fine with strings as shown in this code example:
https://go.dev/play/p/l67xEMBnKfM

### Code sample, to showcase or reproduce:

```go
// Essentially this does not work:
type A struct {
	FieldA *string
}

type B struct {
	FieldB *string
}
type StructTest struct {
	StructA *A `validate:"required_without=StructB,excluded_with=StructB"`
	StructB *B `validate:"required_without=StructA,excluded_with=StructA"`
}

// But this does work:
type StringTest struct {
	A *string `validate:"required_without=B,excluded_with=B"`
	B *string `validate:"required_without=A,excluded_with=A"`
}

```

I'm at a loss on how to get this to work for `StructTest`, what am I missing?
Thanks in advance!

**Comment by zemzale** [comment]
@khawkinson Thanks for the issue. This seems to be some kind of bug. I will try to write a test case for this and check what can I do.

**Comment by zacharyarnaise** [comment]
This might be eligible for closing, I'm unable to reproduce the issue with the latest version of the package.
I believe this was fixed by https://github.com/go-playground/validator/pull/1122.

**Comment by khawkinson** [comment]
@zacharyarnaise  yeah it looks like my test is now failing when it should, thanks!
