### ISSUE TITLE
panic when field is nil

### ISSUE THREAD

**Issue by smzgl** [go-playground/validator#1029]
we define a struct like this:
``` go
type S struct {
      A *int32   `validator:"required_without=B,gt=100,omitempty"
      B *string   `validator:"required_without=B,min=10,omitempty"
} 
```

now, i invoke  validate.Struct( &S { A: ptr.Int32(200) } ), i got panic: Bad field type *string

**Comment by lincolnjpg** [comment]
It might be intentional, since there is an explicit call to the panic function at the end of `isGte()` (and some others too).

https://github.com/go-playground/validator/blob/c7e0172e0fd176bdc521afb5186818a7db6b77ac/baked_in.go#L1857

**Comment by zemzale** [comment]
This must be a problem with some previous versions. Can't reproduce it with the latest version.
