### ISSUE TITLE
required on a struct

### ISSUE THREAD

**Issue by vincentbernat** [go-playground/validator#1030]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

Using `required` on a struct has no effect. validator is validating inside the struct but won't error if the struct is using its default value. From the documentation, I wonder if this is expected. Some examples use `required` on a struct (for example [struct-level/main.go](https://github.com/go-playground/validator/blob/master/_examples/struct-level/main.go) uses `required,dive,required`, the last one being for the struct itself).

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"github.com/go-playground/validator/v10"
)

type User struct {
	Addresses []Address `validate:"required,dive,required"`
}

type Address struct {
	Street string
}

func main() {
	validate := validator.New()
	address := Address{}
	user := &User{
		Addresses: []Address{address},
	}

	err := validate.Struct(user)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by tomaswarynyca** [comment]
Hi @deankarn, do you have any idea how to solve this?

**Comment by zemzale** [comment]
In a case where you want to check if there is a value in the array you are gonna have to use a pointer. 

```go
package main

import (
	"fmt"
	"github.com/go-playground/validator/v10"
)

type User struct {
	Addresses []Address `validate:"required,dive,required"`
}

type Address struct {
	Street string
}

func main() {
	validate := validator.New()
	address := Address{}
	user := &User{
		Addresses: []Address{nil},
	}

	err := validate.Struct(user)
	if err != nil {
		fmt.Println(err)
	}
}
```

Something like this would fail. Sadly because of how Go works, we can't fail on Default values for structs, since that is completely valid Go code that you sometimes might want to use like that. Absence of a value is described by pointers and nil.
