### ISSUE TITLE
transport.go:417:45: undefined: os.ErrDeadlineExceeded

### ISSUE THREAD

**Issue by huizhang001** [go-playground/validator#1032]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

# golang.org/x/net/http2
../../vendor/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded

### Code sample, to showcase or reproduce:

```go
go version go1.13.15 darwin/amd64
```

**Comment by zemzale** [comment]
I just ran the test suite with this version and no compilation errors on our side. 

This must be an issue on your side. Check if you have actually updated the vendor packages. 

This doesn't seem to be an issue unless you can provide an actual reproducible error.
