### ISSUE TITLE
panic: Bad field type string when using unique=fieldName

### ISSUE THREAD

**Issue by hs-dev-web** [go-playground/validator#1034]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
there seems to be other issues like this case too

### Code sample, to showcase or reproduce:

```go
unique=field
```

**Comment by zemzale** [comment]
This indeed has never been implemented. Just pushed a fix for this.

**Comment by muh-hizbe** [comment]
i got same error

<img width="425" alt="image" src="https://user-images.githubusercontent.com/37175249/209902924-aea25240-a568-4341-9159-e021d7ec3f1c.png">
