### ISSUE TITLE
Undefined validation function 'boolean' on field 'IsVisible' ?

### ISSUE THREAD

**Issue by DeveloperVusal** [go-playground/validator#1054]
I get an error: `panic serving [::1]:61822: Undefined validation function 'boolean' on field 'IsVisible'`

Dto struct:
```
type AddGroupDto struct {
	Name        string `json:"name" validate:"required,alphanumunicode"`
	ModeratorId uint   `json:"moderator_id,omitempty" validate:"omitempty,numeric"`
	IsVisible   bool   `json:"is_visible,omitempty" validate:"omitempty,boolean"`
	IsArchive   bool   `json:"is_archive,omitempty" validate:"omitempty,boolean"`
	IsDeleted   bool   `json:"is_deleted,omitempty" validate:"omitempty,boolean"`
}
```

JSON:
```
{
    "name": "Editor",
    "is_visivle": false
}
```

Help guys!

**Comment by ashwek** [comment]
@DeveloperVusal  Are you sure you shared the correct Dto struct & JSON?
I tried reproducing this issue, but i couldn't. Everything works fine.

https://play.golang.com/p/dK1q2rum8xo
This is the playground link.

**Comment by DeveloperVusal** [comment]
Thanks for the example, the problem has been in the version (v9.31)
