### ISSUE TITLE
Support json.RawMessage type for JSON validation

### ISSUE THREAD

**Issue by sahidvelji** [go-playground/validator#1083]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Enhancement

For the [baked in validation for JSON](https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-JSON_String), I would like to see [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) supported as a valid type. Currently, only `string` seems to be supported as per the [IsJSON function](https://github.com/go-playground/validator/blob/f5e5146b316bf0283fd8988dc9f26aebe94b599d/baked_in.go#L2489). I see this as a reasonable use case because a variable having type `json.RawMessage` does not necessarily imply that this variable is valid JSON.

**Comment by Vesquen** [comment]
https://github.com/go-playground/validator/pull/1110

**Comment by sahidvelji** [comment]
Closing this since #1110 was merged. Thanks @Vesquen.
