### ISSUE TITLE
Add optional or nullable rules - useful for ValidateMap

### ISSUE THREAD

**Issue by arxeiss** [go-playground/validator#1092]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

When using `ValidateMap` I would like to set some entries as optional. So if it is not set or set to `nil`, none of the rules then is applied.
Because now when I have a rule for map entry, which does not exist in data map, I got an error.

### Code sample, to showcase or reproduce:

```go
// this returns an errors:
// - plan is required field <- this is OK
// - car must be one of volvo bmw <- this is not OK
res = v.ValidateMap(
	map[string]interface{}{},
	map[string]interface{}{
		"plan": "required,oneof=gold silver bronze",
		"car":  "oneof=volvo bmw",
	},
)

// would be nice to support something like this
// this would return ONLY 1 error:
// - plan is required field
// - car is optional, so no more validation happen
// - phone is optional, so no more validation happen even it is `nil`
res = v.ValidateMap(
	map[string]interface{}{
		"phone": nil
	},
	map[string]interface{}{
		"plan":  "required,oneof=gold silver bronze",
		"car":   "optional,oneof=volvo bmw",
		"phone": "optional,oneof=iPhone Android Other",
	},
)
```

**Comment by zemzale** [comment]
You  are looking for `omitempty` https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Omit_Empty

**Comment by arxeiss** [comment]
Sorry, I was searching nullable and optional and totally missed that one
