### ISSUE TITLE
The error message for a `validate.Var()` contains no information about key and fields

### ISSUE THREAD

**Issue by HaraldNordgren** [go-playground/validator#1109]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

The error message for a `err = validate.Var(val, constraint)` contains no information about key and fields:

```
Key: '' Error:Field validation for '' failed on the 'gt' tag
```

### Code sample, to showcase or reproduce:

```go
err = validate.Var(val, constraint)
```

**Comment by deankarn** [comment]
This is not an issue and has been asked before.

There is no way to dynamically get this information and why it is not present.
