### ISSUE TITLE
How can I allow both `""` and `url`

### ISSUE THREAD

**Issue by acomanescu** [go-playground/validator#1188]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

I'm having a hard time understanding if accepting both `""` (empty) and `url` is possible.

### Code sample, to showcase or reproduce:

```go
type Data struct {
	Logo *string  `json:"logo" validate:"omitempty,url"`
}
```

From what I understand, this should work, but it doesn't.

**Comment by vuon9** [comment]
Have you tried to change pointer of string to string?

**Comment by onattech** [comment]
I am also trying to solve the same problem.

**Comment by sharad-reacher** [comment]
@arobert93 

Try this
Logo string `json:"logo" validate:"omitempty,oneof=url"`
