### ISSUE TITLE
validate.Struct() always returns nil for err.

### ISSUE THREAD

**Issue by stuyy** [go-playground/validator#1207]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version v10: 

I am using V10

### Issue, Question or Enhancement:

validate.Struct() is always returning nil.

### Code sample, to showcase or reproduce:

I have a struct defined like this:

```go
type Todo struct {
	Title       string `json: "title" validate:"required,email"`
	Description string `json: "description" validate:"required,email"`
}
```

And then I'm using gofiber, handling a post request and then parse the body into the `todo` variable, and call validate.Struct(todo). However, it is not validating it. The err object is always nil. I pass in an invalid field for email, and it keeps returning nil.

```go
	validate := validator.New(validator.WithRequiredStructEnabled())
	app.Post("/api/todos", func(ctx *fiber.Ctx) error {
		todo := &Todo{}
		ctx.BodyParser(todo)
		fmt.Println(todo)
		err := validate.Struct(todo)
		fmt.Println(err)
		println("Inside POST /api/todos")
		return ctx.JSON(todo)
	})
	app.Listen(":3000")
```

**Comment by hellowords** [comment]
I also encountered the same problem, did you find a solution? @stuyy 
i use gofiber too.
