### ISSUE TITLE
Add support for numeric ports

### ISSUE THREAD

**Issue by jtuchel** [go-playground/validator#1216]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

Please add support for numeric ports, e.g. a port of type `uint`. For now we have two options

- use `hostname_port` and pass in a string, e.g. `":8080"`
- use a custom validation, e.g. `validate:"gte=1,lte=65535"`

### Code sample, to showcase or reproduce:

The solution would be very similiar to this implementation

https://github.com/go-playground/validator/blob/master/baked_in.go#L2675

The keyword could be `port`, the implementation could be

```go
func isPort(fl FieldLevel) bool {
	val := fl.Field().Uint()
	
	return val >= 1 && val <= 65535
}
```

**Comment by zandwang** [comment]
very good proposal, hope to merge as soon as possible
