### ISSUE TITLE
Validation ignored if struct consists of keys that start with lowercase

### ISSUE THREAD

**Issue by sbp-bvanb** [go-playground/validator#1244]
- [ ] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Code sample, to showcase or reproduce:

```go
type someStruct struct {
  abc string `validate:"required"`
}
```

**Comment by deankarn** [comment]
Please read the documentation.

https://pkg.go.dev/github.com/go-playground/validator/v10#WithPrivateFieldValidation
