### ISSUE TITLE
Help with Logo creation

### ISSUE THREAD

**Issue by joeybloggs** [go-playground/validator#125]
#### Summary
In short I'm no artist, I'm looking to create a logo for this library; hopefully someone can help.

#### Nice to Have
* go/golang gopher included
* some reference to Firefly ( hence the organization name bluesuncorp ) browncoats forever!

#### Please upload images within your comments

**Comment by muyiwaolurin** [comment]
![validator 600x600](https://cloud.githubusercontent.com/assets/3249929/11492263/a3986a0e-97b8-11e5-8562-8aa4a56a92de.png)
![validator 300x300](https://cloud.githubusercontent.com/assets/3249929/11492264/a60b544a-97b8-11e5-8132-2df4373ac87e.png)
![validator 150x150](https://cloud.githubusercontent.com/assets/3249929/11492266/a89069b2-97b8-11e5-895d-98150b97f3a6.png)
![validator 60x60](https://cloud.githubusercontent.com/assets/3249929/11492267/ab85f9fc-97b8-11e5-87f4-9e24a3a177b8.png)

**Comment by muyiwaolurin** [comment]
![validator 2 600x600](https://cloud.githubusercontent.com/assets/3249929/11492272/b217a176-97b8-11e5-81c0-0bec6d8f634b.png)
![validator 2 300x300](https://cloud.githubusercontent.com/assets/3249929/11492275/b47790ac-97b8-11e5-81fd-591e5a83146b.png)
![validator 2 150x150](https://cloud.githubusercontent.com/assets/3249929/11492278/b9db7df6-97b8-11e5-87ef-4a33fdb8931e.png)
![validator 2 60x60](https://cloud.githubusercontent.com/assets/3249929/11492280/bd3472be-97b8-11e5-9495-00e5709395e2.png)
