### ISSUE TITLE
Cron validator is not correct

### ISSUE THREAD

**Issue by HoangViet144** [go-playground/validator#1259]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10.14.0

### Issue, Question or Enhancement:
Cron validator seems not correct. It throws error on input "0 */1 * * *" or "0 */2 * * *"

**Comment by yazver** [comment]
`0 0 */2 * *` don't work too.
