### ISSUE TITLE
Validation failed url with required_without

### ISSUE THREAD

**Issue by fooxlj07** [go-playground/validator#1296]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

Field `Field1 string `validate:"required_without=Field2"``,url, if this field1 is empty, and field2 is not, the validation is failed
Error:  `Key: 'Field1' Error:Field validation for 'Field1' failed on the 'url' tag`
### Code sample, to showcase or reproduce:

```
package main

import (
	"fmt"

	"github.com/go-playground/validator/v10"
)

func main() {
	validate := validator.New()

	s := struct {
		Field1 string `validate:"required_without=Field2,url"`
		Field2 string `validate:"required_without=Field1"`
	}{
		// Field1: "ampq:cd.com",
		Field2: "field1",
	}

	fmt.Println(validate.Struct(s))
}
```

**Comment by vladz** [comment]
> Field1 string `validate:"required_without=Field2,url"`

I've run into this problem too. I solved it by adding `omitempty` param, like this:
```golang
    Field1 string `validate:"required_without=Field2,omitempty,url"`
```
