### ISSUE TITLE
Projects using this - would you like to be linked from the README

### ISSUE THREAD

**Issue by joeybloggs** [go-playground/validator#138]
Hello everyone,

I was looking to start a list of projects on my README that are using this library in the hopes of not only satisfying my own curiosity, but also to promote your works and hopefully draw others to both of our works.

So please comment with the link to your project, if you want, and let me know with a +1 if it would be alright to add your project to the README, otherwise I will assume you do not wish to be added.

Thanks in advance!

**Comment by ilgooz** [comment]
+1 https://github.com/ilgooz/stack
