### ISSUE TITLE
JSON friendly errors

### ISSUE THREAD

**Issue by solher** [go-playground/validator#199]
Currently, the default error message is:
```go
fieldErrMsg = "Key: \"%s\" Error:Field validation for \"%s\" failed on the \"%s\" tag"`
```

Could you just replace the double quotes by simple ones to be more JSON friendly and to avoid the `/"` everywhere when marshaled ?

Just:

```go
fieldErrMsg = "Key: '%s' Error:Field validation for '%s' failed on the '%s' tag"`
```

Amazing work on the validator by the way.

**Comment by joeybloggs** [comment]
Thanks,

I don't see why not @solher I'll try and get it in there sometime today.

**Comment by joeybloggs** [comment]
Hey @solher , the change has been made.

**Comment by solher** [comment]
Awesome !
I guess it wasn't a lot of work that's why I didn't pull request haha.
