### ISSUE TITLE
Hexadecimal empty

### ISSUE THREAD

**Issue by scisci** [go-playground/validator#226]
If I have a an empty field with validation:hexadecimal, I get a validation error. But since the field is empty I would expect no error. I believe the regex needs to be updated from:

`hexadecimalRegexString    = "^[0-9a-fA-F]+$"`

to

`hexadecimalRegexString    = "^[0-9a-fA-F]*$"`

EDIT:
Actually, now that I look at some other regexes, there are many instances of this. So how am I supposed to format a field if I only want the validation to take place if the field is not empty.

**Comment by joeybloggs** [comment]
Hey @scisci 

This came up early in the design of this library and some people do want it to fail when it's blank and others not; so Yes most if not all my regexes are designed to fail when the value is blank and that is what the "omitempty" tag is for, so people can have their cake and eat it too.

So in your case that tags on your hexadecimal field should be "omitempty,hexadecimal"

Sorry for the lateness of my reply, am away from home visiting family

**Comment by scisci** [comment]
no problem, i had omitempty on mjy json, but didn't know it was also a validator tag. Thanks!
