### ISSUE TITLE
Errors map key could honour FieldTagName setting

### ISSUE THREAD

**Issue by byrnedo** [go-playground/validator#227]
If `FieldTagName` is set in the `Config` option, the validation errors map's key should maybe be made up of field names from the tag specified.

Assuming I used

    ...
    FieldTagName = "json",
    ...

The following struct

    type myStruct struct {
        SubStruct struct {
            MyField string `json:"my_field"`
        } `json:"sub_struct"`,
    }

could create a map key like

    sub_struct.my_field

Instead of 

    SubStruct.MyField

**Comment by joeybloggs** [comment]
Thanks @byrnedo will add a boolean option to the config for this after the holidays

**Comment by joeybloggs** [comment]
UPDATE: after some review will be adding another field on each FieldError for this as don't want to confuse StructPartial and StructExcept methods which use the key to determine which fields are to be included/excluded.

**Comment by joeybloggs** [comment]
@byrnedo I have completed the changes please check it out and let me know if it works for you.

**Comment by byrnedo** [comment]
Hi, I'll have a look soon, bit busy at the minute, thanks for doing this!

**Comment by joeybloggs** [comment]
np just let me know when you can

**Comment by joeybloggs** [comment]
any word @byrnedo ?

**Comment by byrnedo** [comment]
Will take a look today, sorry for the delay

**Comment by byrnedo** [comment]
Looks good Dean, that works for me!

**Comment by joeybloggs** [comment]
Perfect
