### ISSUE TITLE
Make email validator conform to formats defined in RFC3696

### ISSUE THREAD

**Issue by moogle19** [go-playground/validator#236]
The current email validator works for all normal emails I tested, but the [RFC3696](https://tools.ietf.org/html/rfc3696#page-6) lists some exotic, but allow email addresses (like: *"Abc@def"@example.com* or *Abc\@def@example.com*).
The question is, should the validator work with such email addresses?

**Comment by joeybloggs** [comment]
#### Docs
I specified right in the docs here https://godoc.org/gopkg.in/go-playground/validator.v8 about this very subject.

#### Summary
email
"This validates that a string value contains a valid email **This may not conform to all possibilities of any rfc standard, but neither does any email provider accept all possibilities.**"

The key being no email provider that I know of accepts all possibilities so passing validation on an email that can't exist in the wild would be worse IMO

#### Accepting RFC email standard
I am totally open to pull requests to add new validations to handle certain standards for example can add a new validation for the [RFC3696](https://tools.ietf.org/html/rfc3696#page-6) with the tag "email_rfc3696"

If you wanted to create it @moogle19 I would definitely add it to the list of validations
