### ISSUE TITLE
Override existing validator

### ISSUE THREAD

**Issue by parveenkumar2308** [go-playground/validator#240]
Hi @joeybloggs ,
I really liked the validator. great work!
One thing which i don't know whether exist or not that can we override existing validation for any type.
for example: for "Required" tag i want that if user doesn't enter anything then it should fail + when user enters white character then also it should fail for my requirements. can i override the required tag validation so that it will do validation wherever i use required tag. similarly in email tag i need validation of underscore in between hence i need to override the  email tag as well.

if yes, then please share an example. if no, then any alternative.

Thanks in advance.

**Comment by joeybloggs** [comment]
Thanks @parveenkumar2308 

Yes you can override required and email, in fact can override any that is not part of [this](http://github.com/go-playground/validator/blob/v8/util.go#L22) map by Registering a new validation see [here](https://github.com/go-playground/validator/blob/v8/validator.go#L270)

It's totally up to you, but since you need to register a new validation to override the old one anyway I would register the new email validation, but not override, but instead use a new name like "uemail"(for underscore email) that way you don't lose the functionality of  the regular email too.

and as for the white space in the required tag you could combine required with any of the excludes tags "excludes", "excludesall" or "excludesrune", just so when someone reads your code(assuming someone else will) they can clearly see what's being validated.

You have many options :smile: the [docs](https://godoc.org/gopkg.in/go-playground/validator.v8) are pretty thourough if you need some code examples, I'd normally include some buy am out of town with no computer.

Hope this explains what you want, if not after I get back in town can provide some examples.

**Comment by parveenkumar2308** [comment]
Thanks Dean Karn.

I have gone through links in your reply. What i have gotten from that is i
need to write a new function like RegisterValidation which makes an entry
in validater map. so, in my case it would be
RequiredWithEmptyCheckValidation and UEmailValidation like you mentioned
that doing it this way i can have both flavours.But, i still didn't get
that where i need to make change in my codebase, where i would define a
util file and i would write the two new validation method or in the API
file itself. also, can you share example, how to define a new one with
exact steps.

I am using validator in my project in below way.i define a struct and give
validation tag against fields and have defined a validation file where i do
validation.

type Person struct{
Id string `json:"id" validate:"required,min=36,max=36"`
Name string `json:"name"`
}

in validation.go file

if errs := validate.Struct(obj); errs != nil {
        if err := errs.(validator.ValidationErrors)["Person.Id"]; err !=
nil {
            if (err.Tag == constant.REQUIRED) {
                errMsg = "msg0"
            }else{


*  if (!IsValidStr(obj.Id)) {//here i am checking white spaces in field if
present returning false else true                    errMsg = "msg1"
        }*else {
                         if(err.Tag == constant.MIN){
                               errMsg =  "msg2"
                         }else if (err.Tag == constant.MAX) {
                              errMsg = "msg3"
                        }

                  }
          }

    return errMsg

How to implement the new validation method which will cater my if
(!IsValidStr(obj.Id)) {} function itself. Also, I have not used excludes
tags "excludes", "excludesall" or "excludesrune". can you suggest where i
fit this tags or new validation method in my solution without changing much.

Regards,
Parveen Kumar

On Fri, May 20, 2016 at 5:35 PM, Dean Karn <notifications@github.com> wrote:

> Thanks @parveenkumar2308 <https://github.com/parveenkumar2308>
>
> Yes you can override required and email, in fact can override any that is
> not part of this
> <https://github.com/go-playground/validator/blob/v8/util.go#L22> map by
> Registering a new validation see here
> <https://github.com/go-playground/validator/blob/v8/validator.go#L270>
>
> It's totally up to you, but since you need to register a new validation to
> override the old one anyway I would register the new email validation, but
> not override, but instead use a new name like "uemail"(for underscore
> email) that way you don't lose the functionality of the regular email too.
>
> and as for the white space in the required tag you could combine required
> with any of the excludes tags "excludes", "excludesall" or "excludesrune",
> just so when someone reads your code(assuming someone else will) they can
> clearly see what's being validated.
>
> You have many options 😄 the docs
> <https://godoc.org/gopkg.in/go-playground/validator.v8> are pretty
> thourough if you need some code examples, I'd normally include some buy am
> out of town with no computer.
>
> Hope this explains what you want, if not after I get back in town can
> provide some examples.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/go-playground/validator/issues/240#issuecomment-220588340>
>



-- 

Warm Regards,
Parveen Kumar
+91-9890333270

**Comment by joeybloggs** [comment]
it doesn't really matter where the util file is defined, just need to register the functions.

there are 3 ways you can accomplish what you want with the required, I recommend option 2 or 3 but you may use any you wish.

#### OPTION 1
```go
package main

import (
	"fmt"
	"reflect"
	"regexp"

	"gopkg.in/go-playground/validator.v8"
)

const (
	uEmailRegexString = "custom email regex"
	uEmail            = "uemail"
	sRequired         = "srequired"
)

var (
	validate    *validator.Validate
	uEmailRegex *regexp.Regexp
)

// Person ...
type Person struct {
	ID    string `json:"id" validate:"srequired,min=36,max=36"`
	Name  string `json:"name"`
	Email string `json:"email" validate:"required,uemail"`
}

func main() {
	uEmailRegex = regexp.MustCompile(uEmailRegexString)

	config := &validator.Config{
		TagName: "validator",
	}

	validate = validator.New(config)
	validate.RegisterValidation(uEmail, IsUEmail)
	validate.RegisterValidation(sRequired, RequiredWithEmptySpace)

	person := &Person{
		ID:    "1",
		Name:  "Joeybloggs",
		Email: "Joey.Bloggs@email.com:",
	}

	errs := validate.Struct(person)

	if errs != nil {
		for k, v := range errs.(validator.ValidationErrors) {
			// Create error messages based on errors returned ...
			fmt.Println(k, v)
		}
	}
}

// IsUEmail ...
func IsUEmail(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {
	return uEmailRegex.MatchString(field.String())
}

// RequiredWithEmptySpace ...
func RequiredWithEmptySpace(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {

	var ok bool

	switch fieldKind {
	case reflect.Slice, reflect.Map, reflect.Ptr, reflect.Interface, reflect.Chan, reflect.Func:
		ok = !field.IsNil()
	default:
		ok = field.IsValid() && field.Interface() != reflect.Zero(fieldType).Interface()
	}

	if !ok {
		return ok
	}

	return !validator.ContainsAny(v, topStruct, currentStructOrField, field, fieldType, fieldKind, param)
}
```

#### OPTION 2
no need for a custom validation for required, use 'excludesall= '
```go
package main

import (
	"fmt"
	"reflect"
	"regexp"

	"gopkg.in/go-playground/validator.v8"
)

const (
	uEmailRegexString = "custom email regex"
	uEmail            = "uemail"
)

var (
	validate    *validator.Validate
	uEmailRegex *regexp.Regexp
)

// Person ...
type Person struct {
	ID    string `json:"id" validate:"required,excludesall= ,min=36,max=36"` // 'excludesall= ' ensures space is excluded
	Name  string `json:"name"`
	Email string `json:"email" validate:"required,uemail"`
}

func main() {
	uEmailRegex = regexp.MustCompile(uEmailRegexString)

	config := &validator.Config{
		TagName: "validator",
	}

	validate = validator.New(config)
	validate.RegisterValidation(uEmail, IsUEmail)

	person := &Person{
		ID:    "1",
		Name:  "Joeybloggs",
		Email: "Joey.Bloggs@email.com:",
	}

	errs := validate.Struct(person)

	if errs != nil {
		for k, v := range errs.(validator.ValidationErrors) {
			// Create error messages based on errors returned ...
			fmt.Println(k, v)
		}
	}
}

// IsUEmail ...
func IsUEmail(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {
	return uEmailRegex.MatchString(field.String())
}
```

#### OPTION 3
register alias for required + excludesall to avoid some typing
```go
package main

import (
	"fmt"
	"reflect"
	"regexp"

	"gopkg.in/go-playground/validator.v8"
)

const (
	uEmailRegexString = "custom email regex"
	uEmail            = "uemail"
	sRequired         = "srequired"
)

var (
	validate    *validator.Validate
	uEmailRegex *regexp.Regexp
)

// Person ...
type Person struct {
	ID    string `json:"id" validate:"srequired,min=36,max=36"`
	Name  string `json:"name"`
	Email string `json:"email" validate:"required,uemail"`
}

func main() {
	uEmailRegex = regexp.MustCompile(uEmailRegexString)

	config := &validator.Config{
		TagName: "validator",
	}

	validate = validator.New(config)
	validate.RegisterValidation(uEmail, IsUEmail)
	validate.RegisterAliasValidation(sRequired, "required,excludesall= ")

	person := &Person{
		ID:    "1",
		Name:  "Joeybloggs",
		Email: "Joey.Bloggs@email.com:",
	}

	errs := validate.Struct(person)

	if errs != nil {
		for k, v := range errs.(validator.ValidationErrors) {
			// Create error messages based on errors returned ...
			fmt.Println(k, v)
		}
	}
}

// IsUEmail ...
func IsUEmail(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {
	return uEmailRegex.MatchString(field.String())
}
```

let me know if this helps @parveenkumar2308, and if you have any more questions just ask.

**Comment by parveenkumar2308** [comment]
@joeybloggs i will try the three methods. though i have 1 query with option 2 and 3. 
If in the Name field of Person struct, i want to validate for "srequired" tag then , does it allow Parveen Kumar value. because i just want to validate for empty string(if strToCheck == "" || len(strToCheck) == 0 || len(strings.TrimSpace(strToCheck)) == 0 {
		return false
	}).

not for each white space.

**Comment by joeybloggs** [comment]
Oh I misunderstood, options 2 & 3 are for any whitespace you are correct.

then option1 would be your best bet with your code changes :)

**Comment by parveenkumar2308** [comment]
Hi Dean,

Thanks a lot. It worked like a charm.

Regards,
Parveen Kumar

On Tue, May 24, 2016 at 9:21 AM, Dean Karn <notifications@github.com> wrote:

> Oh I misunderstood, options 2 & 3 are for any whitespace you are correct.
>
> then option1 would be your best bet with your code changes :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/go-playground/validator/issues/240#issuecomment-221159765>
>



-- 

Warm Regards,
Parveen Kumar
+91-9890333270

**Comment by joeybloggs** [comment]
No problem, glad it worked for you :)
