### ISSUE TITLE
Can I have one choice list validation?

### ISSUE THREAD

**Issue by phenrigomes** [go-playground/validator#242]
Example: validate([]string{"A", "B", "C"}, value)

**Comment by joeybloggs** [comment]
I'm not quite sure what you mean, do you mean ability to validate `[]string` on it's own and not part of a struct?

or

validate a single element within a `[]string` but not the others?

there is the ability to validate any field individually using [validate.Field](https://github.com/go-playground/validator/blob/v8/validator.go#L332) example shown [here](https://github.com/go-playground/validator/blob/v8/examples/simple/simple.go#L85)

**Comment by phenrigomes** [comment]
I have a gender field with values: "M" | "F" | "O". I need an way to validate choice values as: validate(FieldValue, <Choices - []interface{}>) - Choices allowed are: "M" | "F" | "O", but they could be "MA" | "FE" | "OT"...

**Comment by joeybloggs** [comment]
Oh OK, yes totally doable with `or's` in the tag

eg.
```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v8"
)

var (
	validate *validator.Validate
)

func main() {

	config := &validator.Config{
		TagName: "validate",
	}

	validate = validator.New(config)

	fld := []string{"M", "F", "O"}


	errs := validate.Field(fld, "dive,eq=M|eq=F|eq=O")
	fmt.Println(errs)
}
```

`dive` - tells the library to go into/dive into the array
`eq=M|eq=F|eq=O` - says any value in the array must be equal to M or F or O

if using on a single field and not an array, just remove the dive tag.

does this example explain what your looking for?

**Comment by joeybloggs** [comment]
Hey @phenrigomes just checking if my example was what you were looking for?

**Comment by abhineet-plivo** [comment]
@joeybloggs is there a way to may this validation case insensitive ?
