### ISSUE TITLE
How to validate the nested struct fields if this struct is not empty

### ISSUE THREAD

**Issue by wenchma** [go-playground/validator#246]
like the struct below, I want to validate: if User.Address is not empty, then validate the nested struct fileds (City and Street), if User.Address is empty, omit.
Any idea? or is this supported ?

```
type User struct {
    Name    string
    Address Address
}
type Address struct {
    City     string   `validate:"required"`  
    Street  string   `validate:"required"`
}
```

**Comment by wenchma** [comment]
@joeybloggs any comment is appreciated.

**Comment by joeybloggs** [comment]
Hello @wenchma

there are a few options, first off just need to point out that because Go is statically typed, the way Address is defined within the User struct it will never be empty.

Option 1:
change address definition in user to `Address *Address` and then can add the `omitempty` tag.

Option 2
change address definition to allow for multiple addresses `Address []Address's and when no items exist in the array it won't get validated.

Option 3
this one is probably not desired but could also set `omitempty` tag on each field withing Address and allow a blank address.

Sorry for the lack of code, answering from my phone, please let me know if this makes sense or need any more help.

**Comment by wenchma** [comment]
@joeybloggs Awesome, :+1:  your options are very helpful for me, I think them will work, let me try.
Much thanks!

**Comment by roychowdhuryrohit-dev** [comment]
How do I validate if one of the nested struct field (city and street) is empty, the whole Address field will be omitted ?

**Comment by roychowdhuryrohit-dev** [comment]
> @joeybloggs Awesome, 👍 your options are very helpful for me, I think them will work, let me try.
> Much thanks!
How do I validate if one of the nested struct field (city and street) is empty, the whole Address field will be omitted ? @deankarn

**Comment by deankarn** [comment]
@roychowdhuryrohit-dev if I'm not sure I understand your question, can you provide more details?

**Comment by roychowdhuryrohit-dev** [comment]
> @roychowdhuryrohit-dev if I'm not sure I understand your question, can you provide more details?

I am using Gin which uses validator V8. Suppose in the above example 
```
type User struct {
    Name    string
    Address Address
}
type Address struct {
    City     string   `validate:"required"`  
    Street  string   `validate:"required"`
}
```
I want a behaviour in which if any one of the field (City, Street) is empty, the Address field in User will be omitted/empty.

**Comment by roychowdhuryrohit-dev** [comment]
> Thanks @roychowdhuryrohit-dev but still a little confused.
> 
> > I want a behaviour in which if any one of the field (City, Street) is empty(""), the Address field in User will be omitted/empty.
> 
> If this is the case then why validate the fields at all? in what case would you want/need validation?

I am storing the Address field as jsonb field in Postgres. I am looking for a way by which incomplete/missing data doesn't get stored as Gorm doesn't handle this for jsonb types.

**Comment by birnbuazn** [comment]
Option 1 doesn't seem to work for me. If I use a pointer for `Address` within the `User` struct, `City` and `Street` never get validated, even if the address is non-empty. What am I missing?

**Comment by vigmiranda** [comment]
type User struct {
    Name    string
    Address *Address `validate:"omitempty"`
}
type Address struct {
    City     string   `validate:"required"`  
    Street  string   `validate:"required"`
}



This way it works

**Comment by CitTizenfour** [comment]
> как и в структуре ниже, я хочу проверить: если User.Address не пуст, то проверить вложенные поля структуры (City и Street), если User.Address пуст, опустить. Есть идеи? или это поддерживается?
> 
> ```
> type User struct {
>     Name    string
>     Address Address
> }
> type Address struct {
>     City     string   `validate:"required"`  
>     Street  string   `validate:"required"`
> }
> ```

In the following example, we demonstrate how to validate nested structures in Go using the validator package.

type User struct {
    Name    string
    Address Address `validate:"required,dive"` // 'dive' ensures nested validation
}

type Address struct {
    City   string `validate:"required"`  
    Street string `validate:"required"`
}

**Comment by gpsa** [comment]
Sorry for circling back to this question, but I was working on a helper to get errors in a format like `'address.city': "city is required"`, but even with dive, this package only complains about the root level, that means `"address":"address is required"`, 

How can I sorta display nested errors upon calling the `err := v.Struct(generic)`
