### ISSUE TITLE
Please advice. Field validation

### ISSUE THREAD

**Issue by gebv** [go-playground/validator#247]
How to check separate field if it not in the given type

``` go
v := validator.New(&validator.Config{})
v.Field("2", "required,gt=1") // error, want ok
v.Field(2, "required,gt=1") // ok
```

I want that string numbers were perceived as number. Any idea how that's do this?

**Comment by joeybloggs** [comment]
The only reliable way would be to convert it to the correct type and then validate,

there are a couple of options.

1. Convert it prior to checking, I am assuming number is an int:
```go
i, err := strconv.Atoi("2")
if err != nil {
// handle error here
}
v.Field(i,"required,gt=1")
```

2. Create a Custom Validation which converts it in the background for you and then uses the normal validation.

NOTE: didn't test the code but it should work
```go

func AtoiGT(v *Validate, topStruct reflect.Value, currentStruct reflect.Value, field reflect.Value, fieldtype reflect.Type, fieldKind reflect.Kind, param string) bool {

    if fieldKind != reflect.String {
        return false
    }

    i, err := strconv.Atoi(field.String())
    if err != nil {
        return false
    }

    vo := reflect.ValueOf(i)

    return validator.IsGt(v, topStruct, currentStructOrField, vo, vo.Type(), vo.Kind(), param)
}

v := validator.New(&validator.Config{TagName: "validate"})
v.RegisterValidation("atoigt", AtoiGT)

v.Field("2", "required,atoigt=1")
```

Please let me know if this helps :)

**Comment by gebv** [comment]
An excellent idea a create custom validation. It is an elegant solution. Thanks @joeybloggs
