### ISSUE TITLE
v9 - What would YOU like to see?

### ISSUE THREAD

**Issue by joeybloggs** [go-playground/validator#250]
Hello All! and Thanks in Advance!

UPDATE: [v9.0.0 RC1](https://github.com/go-playground/validator/releases/tag/v9.0.0RC1) is out, please let me know what you think

I will soon be rewriting validator v9, from scratch, and am looking for any ideas or suggestions from you the community for anything you would like to see in the new version. I cannot guarantee all will be included, but can't add it if I don't know about it 😄 

Here is a short list of changes that I will continue to add to:

1. Update errors to return as an array instead of map ( more efficient + map is not needed until a translation of the error is generated, if at all ) ✔️ 
2. ~~Attempt to cache parameter for struct fields already cast to the appropriate data type.~~ this would work for allot of scenarios, however when adding custom validator could cause issues, especially with CrossField validation and is just too risky. ✔️ 
3. ~~Add Interface/Implements check for structs that satisfy a `Validatable` interface (TBD), which will mirror Struct Level Validation. This will also allow those who are concerned with ultimate speed and not RAD to validate natively, but still report errors in a consistent way through validator; a true have your 🍰  and eat it too change.~~ This would end up being very confusing to developers as there would be a method on a struct that can only be called by a library? that and would have 2 different ways of struct validation, overall it was just too confusing, would have been inefficient compared to struct validation that can be cached so sticking with just one way, and that struct level validation ✔️ 
4. ~~Allow Structs to be validated, just like fields, see~~ #245 ✔️ 
5. Remove the `exists` tag (which v8 now supports as well), in favour of `required` ([Release v8.17.3](https://github.com/go-playground/validator/releases/tag/v8.17.3) made this possible)
6. Keep `required` and drop `exists` ~~Change `required` to `nondefault` or have both tags present? `required` makes more sense when reporting errors, but `nondefault` is clearer for those using the library. Thoughts?~~ ✔️ 
7. Unexpose `FieldError` fields in favour of interface methods enabling easier updating of changes ✔️ 
8. Custom Error Messages + Translations ( this will be added in a separate repo as a totally optional component, post validation, when [universal-translator](https://github.com/go-playground/universal-translator) is ready)
9. Don't Panic with invalid input, but return InvalidValidationError ✔️ 
10. Change FieldName tag to be a hook to allow users to subscribe their own in order to support many more than just JSON... ✔️ 
11. remove initCheck(), if it's used without initialization.... that's not the library's responsibility. ✔️ 
12. Unexpose internal validator to accommodate new simpler syntax...a tradeoff ✔️ 
13. ~~add alphaunicode and alphanumunicode to compliment the regular ascii checks for~~ #239 will accept a pull request, but would also allow allot of other characters not expected, so leaving out for now.
14. more to come...

**Comment by alioygur** [comment]
first of all, I think you should change list of changes to numeric list :) so I we can talk better

**Comment by alioygur** [comment]
Allow Structs to be validated, just like fields, see #245
I do not agree with this.

Change required to nondefault or have both tags present? required makes more sense when reporting errors, but nondefault is clearer for those using the library. Thoughts?
I do not agree with this.

There is awesome library that written with PHP.
https://laravel.com/docs/5.2/validation

I think go-playground/validator is best validation package in golang. but it is small.

sorry for my bad english.

**Comment by alioygur** [comment]
And, Please don't remove the "dive" tag!

**Comment by joeybloggs** [comment]
thanks @alioygur for your feedback! 😄  and don't worry the `dive` tag is staying!

as for # 4 - I think you may be right

I was hoping you could expand on 2 of your answers:
```
Change required to nondefault or have both tags present? required makes more sense when reporting errors, but nondefault is clearer for those using the library. Thoughts?
I do not agree with this.
```
So you are saying just stick with `required`?

When you say `it is small`, do you mean the number of validations? if so if you could provide a list of ones you would like to see I could work towards adding them.

**Comment by alioygur** [comment]
Yes. about number of validations.

So I provide a package. https://laravel.com/docs/5.2/validation this package has a lot validations.

**Comment by joeybloggs** [comment]
Hey @alioygur just released [v9.0.0 RC1](https://github.com/go-playground/validator/releases/tag/v9.0.0RC1) and would love your feedback if you can find time :)

**Comment by joeybloggs** [comment]
[v9](https://github.com/go-playground/validator/releases/tag/v9.0.0) has been released!

**Comment by codepushr** [comment]
Hm, the `required` tag does not work the same way as `exists` did with pointers! See https://github.com/go-playground/validator/issues/142#issuecomment-250163238

E.g. using a `false` for a bool pointer results in a failed validation. Now using v8 where `exists` worked exactly as intended.

**Comment by LaysDragon** [comment]
@deankarn
hello,I don't understand,why you drop exists tag,the required still have problem with those zero value while decode json in go-gin,it cannot replace complete by required.please take a look of
https://github.com/gin-gonic/gin/issues/491
