### ISSUE TITLE
Is it possible to have a required cross-field validation?

### ISSUE THREAD

**Issue by MarcoVigna17** [go-playground/validator#253]
Hi @joeybloggs, I'm using your package to perform some validation on data that I'm receiving via API.

I'd like to know if there is the possibility (and I missed it) to perform a required cross-field validation.

What I want to achieve is having a validation that returns OK if one of two fields is present on my struct...something like this:

```
type Field struct {
   Value1 string `validate:"at_least_one_required"`
   Value2 string `validate:"at_least_one_required"`
   ...
}
```

and the validator returns an error if no one of the two fields is not set up.

Is that possible?

Thanks,
Marco

**Comment by joeybloggs** [comment]
Hello @MarcoVigna17 

Yes it is possible, but there is no built in tag for it.

You have two options:

1. Create a custom validation for your specific struct and then add that new tag to your struct field(s)

2.  This level of complexity however is best suited for `StructLevel` validation I would just register a Struct level validation and use `ReportError` when there is an issue. Struct level and tags are completely compatible and work together.

Sorry for no examples, answering from my phone; if you need an example just let me know, I should be able to hop on a computer in a half hour or so.

P.S. what version are you using? v8 or v9

**Comment by MarcoVigna17** [comment]
First of all, thanks for the immediate response!

I was starting to develop the first proposed solution, but after your answer, I agree that the second one is probably the best solution. I don't need this kind of validation on other struct, just on the one that I'm developing right now, so probably it's easier and safer!

I'm using v8 cause was just on my package, I just noticed that you released the v9 and I shouldn't have compatibility problems, so I can update easily!

**Comment by joeybloggs** [comment]
Ok awesome, let me know how it goes.

I know v9 says it's RC1 but I don't foresee any changes and will be flipping it to stable in a few weeks ( just want to add an extension to allow for translating errors using my universal-translator package, but will probably be located in another repo )

**Comment by MarcoVigna17** [comment]
I did and it's working, thanks for your help!

Just one question, cause I had to implement a workaround on a sub struct inside my main one, on which I created  the custom validator.

Let me show you some code that it's easier...

Those are my structs:
```
type OuterStruct struct {
	Values      []InnerStruct   `json:"values"`
	ExtraValue   string         `json:"additional_value"`
}

type InnerStruct struct {
	ID string `json:"id" validate:"required"`
}
```

and this is was my custom validator:
```
func StructArgsValidation(v *validator.Validate, structLevel *validator.StructLevel) {
	fieldArgs := structLevel.CurrentStruct.Interface().(OuterStruct)

	if len(fieldArgs.Values) == 0 && fieldArgs.ExtraValue == "" {
		structLevel.ReportError(reflect.ValueOf(fieldArgs.Values), "Values", "values", "valuesOrExtraValue")
		structLevel.ReportError(reflect.ValueOf(fieldArgs.ExtraValue), "ExtraValue", "additional_value", "valuesOrExtraValue")
	}
```

The expected behaviour to me was that the inner struct was validated on the calling of `errs := validator.Struct(outerStruct)`, but it wasn't, cause this object was passing the validation:
```
OuterStruct{
				Values: []InnerStruct{
					{},
				},
			}
```

I read about the "dive" tag, is that the case where I have to use it?

**Comment by joeybloggs** [comment]
Hey @MarcoVigna17 

ya the reason it doesn't is because it's within an array, the dive tag is exactly what you're looking for, you can actually validate against array and then dive down into it like so:

```go
type OuterStruct struct {
    Values      []InnerStruct   `json:"values" validate:"required,gt=0,dive"`
    ExtraValue   string         `json:"additional_value"`
}
```

and that will validate that the array exists, there is at least one entry in the array and then to div into it...

sorry for the short answer, bust day today, let me know if this works for you.

**Comment by MarcoVigna17** [comment]
Perfect, I used the `dive` tag and now I can rid of that check from StructValidation custom function. 

I noticed a problem then (I will open a proper new issue when I have a little bit of free time, but I want to post it now so we can start discuss)

With this validation on different fields, the order of the errors returned when I call my `validation.Struct(structToValidate)` function is never the same.

I noticed cause running my unit test in the same conditions, sometimes fails and sometimes not. In particular, I have my test to check this:

```
		{
			arg: OuterStruct{
				ExtraValue: "",
			},
			expectedError: "Key: 'AudienceFieldArgs.Values' Error:Field validation for 'Values' failed on the 'valuesOrExtraValue' tag\n" +
				"Key: 'AudienceFieldArgs.ExtraValue' Error:Field validation for 'ExtraValue' failed on the 'valuesOrExtraValue' tag",
		}
```

and the returned error says that has this object like response:
```
Key: 'AudienceFieldArgs.ExtraValue' Error:Field validation for 'ExtraValue' failed on the 'valuesOrExtraValue' tag
       		Key: 'AudienceFieldArgs.Values' Error:Field validation for 'Values' failed on the 'valuesOrExtraValue' tag
```

as you can see, I have that both the validation are failing (and this is correct) but in the wrong order, so my test doesn't work

I promise I will create a gist later on today!

**Comment by joeybloggs** [comment]
Hey @MarcoVigna17 

Glad it's working for you :) 

As for the order, it's because the error returned is really of type `ValidationErrors` which is a `map[string]*FieldError` and maps in go are not ordered like in some other languages; in fact when iterating over them they are purposely randomised (there is a good reason why, but that's another discussion)

This is one of the things that v9 inherently solves though as the error returned is really an array of error instead of a map; if you are starting fresh I highly recommend using v9 over v8.

Let me know if that makes sense :smiley:

**Comment by MarcoVigna17** [comment]
Ok I will try to update to v9 and I will say you if it fixes the problem all the time, cheers ;)

**Comment by MarcoVigna17** [comment]
I converted to use v9, I thought was painless, but apparently you improved the code everywhere 😄 

I figure out how to make my code working (and now every test is passing, which is great!), and I like how the code to register a custom struct validator become easier. I just have a doubt on the  new `ReportError` structure:
```
structLevel.ReportError(field, fieldName, altName, tag, param)
```

What this param represents? How stable is this version? Can I use it in production without any problem?

**Comment by joeybloggs** [comment]
that's great @MarcoVigna17 

The param represents the comparison value I.e. if you had a struct tag defined like so `gt=1` then `1` would represent the param, in string form. I had forgotten to accept the param in v8. 

You may be asking why it's important, well the errors returned are actually `FieldError` and all aspects of a validation error are accessible, including the param; the reason all aspects are accessible are is to allow for creation of your own error messages and the param not only should be in the error messages eg.  `Field must be greater than 1 character long` for a validation tag of `gt=1` but also need it for proper plural rule translation which I intend to build functionality for using my `universal-traslator` package ( just debating on the best way to integrate it)

This version should be perfectly stable just like v8, they have and pass the same tests which cover 100% of the code; I will be flipping v9 to stable, I was just waiting to add the aforementioned translation logic, but no reason I can't flip it right now. I will flip it to stable for you by the end of the week.

**Comment by joeybloggs** [comment]
Hey @MarcoVigna17 as promised [v9](https://github.com/go-playground/validator/releases/tag/v9.0.0) has been released!

**Comment by MarcoVigna17** [comment]
Awesome, cheers for all of your support! 😉

**Comment by joeybloggs** [comment]
Thanks!
