### ISSUE TITLE
Get json tag value

### ISSUE THREAD

**Issue by dkostenko** [go-playground/validator#258]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Hello! 
My situation: I have pointer to struct with type interface{} and I validate it with the help of validator (v9). Validation works perfectly! But after getting array of validation errors (ValidationErrors) I'd like to get json tag value, not actual field name. For example:
I have such struct:
type Qwe struct {
  Name string `json:"name" validate:"required"`
}
After validation I would like to get error message with json tag value "name", not "Name" (with a capital letter).

In the source code of validator I see a method Field() in interface FieldError with such comment:
"	// returns the fields name with the tag name taking precedence over the
	// fields actual name.
	//
	// eq. JSON name "fname"
	// see ActualField for comparison"
But I don't see ActualField and don't get field name with the tag name taking precedence over the fields actual name.
Could you please help me with this problem?

**Comment by dkostenko** [comment]
I got it

```
validationErrors := err.(validator.ValidationErrors)
validationErr := validationErrors[0]
fieldName := validationErr.Field()
field, ok := reflect.TypeOf(args).Elem().FieldByName(fieldName)
fieldJSONName, _ := field.Tag.Lookup("json")
```

Sorry for disturbing

**Comment by joeybloggs** [comment]
Hey @dkostenko no problem, but there is actually a better way built in to get any tag name, even JSON
you just have to register your own [TagNameFunc](https://github.com/go-playground/validator/blob/v9/validator_instance.go#L114) and then essentially do the same thing you did to grab the tag name and return, the benefits to using the built in way is that the information is cached and function really only called once.

Then the err.Field() will have whatever name you returned from the function and err.StructField() will have the struct field name.

Sorry answering from my phone, I'll post some sample code once at a computer, but it's pretty easy to figure out :)

**Comment by joeybloggs** [comment]
@dkostenko here is some sample code:

```go
validate := New()
validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
	name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]

	if name == "-" {
		return ""
	}

	return name
})

// ... validate

validationErrors := err.(validator.ValidationErrors)
validationErr := validationErrors[0]
fieldName := validationErr.Field() // this will return the JSON tag name
```

**Comment by BentCoder** [comment]
@deankarn Given that your solution above still works with v9, is there shorter/new/etc. way in v9? Just asking as it has been 3 years. Thanks!

**Comment by sebnyberg** [comment]
For anyone using Gin and wanting to register this validator, there is an example here:

https://github.com/go-playground/validator/blob/v9/_examples/gin-upgrading-overriding/v8_to_v9.go

**Comment by oussamm** [comment]
> For anyone using Gin and wanting to register this validator, there is an example here:
> 
> https://github.com/go-playground/validator/blob/v9/_examples/gin-upgrading-overriding/v8_to_v9.go

@sebnyberg 
Where should we put this code on a main or on the file where we returns an Engine instance?

**Comment by cloco-ritesh** [comment]
> args

What is args here??

**Comment by qwerty22121998** [comment]
@mcarr-and I know that this issue is closed but your solution may not work in nested struct

**Comment by umardev500** [comment]
we can't get the struct field we need to get it by actual struct not from validaton errs

> I'm still having this issue in v10.

**Comment by fanesz** [comment]
any idea for nested struct?
```
{
    "user": {
        "email": "johndoe@mail.com"
    }
}
```
With this request, if I don't include the "email", it only returns like "email is required", I want like "user.email is required"

**Comment by Xentox-Phil** [comment]
@fanesz did you find any solution for this?

also searching for a solution to this...

**Comment by fanesz** [comment]
> [@fanesz](https://github.com/fanesz) did you find any solution for this?
> 
> also searching for a solution to this...

nope :(, i believe you can like create a custom tag and custom err handler to get the tag, 
but that just bad i think
