### ISSUE TITLE
Does the position of the ommitempty matter?

### ISSUE THREAD

**Issue by wanghq** [go-playground/validator#259]
### Package version eg. v8, v9: 
Only tested with v8

### Issue, Question or Enhancement:
Question: does the position of  the ommitempty matter? I know it matters to "dive". For below example, I expect that they both return false.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"gopkg.in/go-playground/validator.v8"
)

func main() {

	thing1 := struct {
		P1 *int32 `validate:"omitempty,min=1,max=300"`
	}{
		P1: util.Int32(0),
	}
	thing2 := struct {
		P1 *int32 `validate:"min=1,omitempty,max=300"`
	}{
		P1: util.Int32(0),
	}
	c := &validator.Config{TagName: "validate"}
	v := validator.New(c)
	fmt.Println(v.Struct(&thing1) == nil) // true
	fmt.Println(v.Struct(&thing2) == nil) // false
}

```

**Comment by joeybloggs** [comment]
Hello @wanghq 

In short yes the order of `omitempty` does matter, but not in your example, they should be false failing on the `min` validation.

I don't exactly know what `util.Int32(0)` is returning, but I'm assuming it's a pointer to an integer with value of zero.
```go
package util

func Int32(val int32) *int32 {
    return &val
}
```

I ran the following code, and both returned false for me and both failed on the `min` validation as expected.
```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v8"
)

func main() {

	var i int32

	thing1 := struct {
		P1 *int32 `validate:"omitempty,min=1,max=300"`
	}{
		P1: &i,
	}
	thing2 := struct {
		P1 *int32 `validate:"min=1,omitempty,max=300"`
	}{
		P1: &i,
	}
	c := &validator.Config{TagName: "validate"}
	v := validator.New(c)
	fmt.Println(v.Struct(&thing1) == nil) // false
	fmt.Println(v.Struct(&thing2) == nil) // false

	fmt.Println(v.Struct(&thing1))
	fmt.Println(v.Struct(&thing2))
}
```

perhaps this was a bug, but has been corrected and you just need to run `go get -u gopkg.in/go-playground/validator.v8` ... assuming you don't have the latest version already( allot of people use validator through gin, the bundled version in gin is: v8.15.1 but the current version is v8.18.1 )

please let me know if this fixes it for you 😄  if not we can dig a little deeper to find out what's going on.

P.S. if you are new to validator I highly recommend using v9, allot was simplified and cleanup up for the end user, there is even an upgrade example for gin if you're using it that way [here](https://github.com/go-playground/validator/tree/v9/examples/gin-upgrading-overriding)

**Comment by wanghq** [comment]
@joeybloggs , thanks for the quick response!

1. Yes, that util.Int32 returns the a pointer to the pass in integer. Sorry for not including that.
2. Yes, I was using an old version (https://github.com/go-playground/validator/tree/c193cecd124b5cc722d7ee5538e945bdb3348435)
3. Yes, upgrading to https://github.com/go-playground/validator/releases/tag/v8.18.1 fixed the problem.
