### ISSUE TITLE
Support for non-latin characters?

### ISSUE THREAD

**Issue by justinclift** [go-playground/validator#261]
Looking at the available validation rules, there doesn't (yet) seem to be anything available for non-latin based character sets.  eg Mandarin, Japanese, Thai (etc)

Is there a desire to get that included? (#239 seems relevant)

If so, Astaxie's Golang programming intro has a method to validate Chinese characters: https://github.com/astaxie/build-web-application-with-golang/blob/c672edb3255b907296d7d8153038b839034da54d/en/04.2.md#chinese
(might be worth incorporating)

No idea about similar for other languages yet, but it might be a useful start.

Asking because I'm looking for a validation approach for valid Unicode characters (for display of names), thus looking around. :wink:

### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Enhancement

**Comment by joeybloggs** [comment]
Hey @justinclift 

alpha & alphanum should be the only validations that do not support latin characters that could/should(if not let me know) and yes I am interested in including 2 more validations.

I would like to add `unicodealpha` and `unicodealphanum` to accept unicode characters, can't break the current validations, the only thing is that the regex in #239 not only accepts unicode characters but also symbols which is probably not desired.

I am completely open to a pull request to add the above validations(or any other validations) as long as they only accept characters and alphanumeric characters; it's on my list of things to do but don't know when I'll get to it. Any help would be appreciated :smile: validations are pretty easy to add, it's all the tests to add that takes a bit.

if you are also referring to actual name validation mentioned in #239, as I had mentioned this is a very subjective and case-by-case thing, however, I have been thinking of creating another repo(or perhaps a subfolder/subpackage in this one) to hold validations that are not in the core but are available to be easily registered if one wants to use them; what do you think?

**Comment by justinclift** [comment]
Hmmm, there doesn't seem to be a validation for "is this a valid Unicode character string?" either, or am I not seeing something obvious?

**Comment by joeybloggs** [comment]
Hey @justinclift 

No you are not missing anything, as my previous comment mentioned, I would like to add them; they do not yet exist.

My time is just very limited right now and don't know when I can get to adding them, if someone could add them and make a pull request I'd merge it.

I will attempt  to add these sometime this morning if I can find time.

**Comment by joeybloggs** [comment]
Hey @justinclift 

I've added `alphaunicode` and `alphanumunicode` in [Release 9.3.0](https://github.com/go-playground/validator/releases/tag/v9.3.0)

please let me know if this helps

**Comment by justinclift** [comment]
Oohh thanks @joeybloggs, that definitely looks useful.  I'll give that a shot, most likely tomorrow (brain dead atm).

**Comment by justinclift** [comment]
It turns out I was getting ahead of myself, so it'll probably be at least a few days until I can try this out properly. 👼

**Comment by justinclift** [comment]
Sorry for the delay.  Got distracted by other things.

No idea when I'll get around to testing this part of things myself. 😦

**Comment by joeybloggs** [comment]
No worries I know how things can get busy :smile:
