### ISSUE TITLE
Is there a way to set Default value?

### ISSUE THREAD

**Issue by mrLSD** [go-playground/validator#263]
Hi @joeybloggs, I liked the validator, great work!

Could you tell me, is there a way to set Default value for field?
For example, I have empty field, and rule with Default value for it.

**Comment by joeybloggs** [comment]
Hey @mrLSD thanks,

Just so I understand, so you have a custom validation and want to set the value of the field and after the validation has run have the field still be set on the struct or variable passed for validation?

**Comment by mrLSD** [comment]
Thank you for the response.

Example:

```
type Page struct {
	Title              string     `validate:"required"`
	Published     string     `validate:"default=false"`
}

func validateStruct() {
	page := &Page{
		Title: "My page title",
	}

	err := validate.Struct(page)
	// We have filled omitted field
	// page.publishe = false
	if err != nil {
```

or for variable:
```
	published := ""
	errs := validate.Var(published, "default=false")
	// publishe = false
```

**Comment by joeybloggs** [comment]
@mrLSD 

ok I understood correctly, unfortunately this is not possible the way that validator is currently configured to work. It seems simple at first glance, but once getting into nested structs, arrays, maps, interfaces and pointers assigning values gets allot more complicated and the way validator works is it dereferences pointers before passing along to the validation functions, and so although the field value is accessible, it is no longer assignable.

I have toyed around with the idea of adding similar functionality, much like the [conform](https://github.com/leebenson/conform) library(which is almost what your looking for), however it always ends up overcomplicating the validator package and I would prefer to keep validator for validation only.

I would recommend creating your own function to set default values and call that prior to validation; could even get fancy and have a map with key type and value the function to be called to set default values and have a single common function that all you need to do is call it and it will check the map and call function if exists.

Thanks for the question though 😃

**Comment by mrLSD** [comment]
@joeybloggs Thank you for great answer and interesting idea. I'll try it.
