### ISSUE TITLE
returning specified sturct field value in the error

### ISSUE THREAD

**Issue by pipejesus** [go-playground/validator#269]
### Package version eg. v8, v9: 
v9

### Question :
Hello, i've come across the problem i do not know how to approach: my struct looks like this:

```
type Field struct {
    Name string `json:"name" validate:"required"`
    Reference string `json:"reference"`
}
```

and i want to do a struct validation but need to get the value of the field "Reference" if the validation fails. I do not know even where to start.

**Comment by joeybloggs** [comment]
@pipejesus it sounds like your validation is getting a bit more complicated and there are a couple of options.

1. Create your own custom validation, `requiredref` or whatever you wish to call it, and within the validation you will have access to the entire struct via the [Field Levels Parent function](https://github.com/go-playground/validator/blob/v9/field_level.go#L14) but this doesn't help you get the value out into the calling program so option 2.

2. Create a `StructLevel` validation where you have full control of the error reported using [ReportError](https://github.com/go-playground/validator/blob/v9/struct_level.go#L43) and access to all fields withing the struct, see [here](https://github.com/go-playground/validator/blob/v9/examples/struct-level/main.go)

I hope to combine both FieldLevel and StructLevel validation in the next version to avoid any limitations.

If you have any more questions please don't hesitate to ask.

**Comment by pipejesus** [comment]
Hi Joey, huge thank you :-) I'll try to work something out with your insight !

**Comment by pipejesus** [comment]
So this isn't a very elegant way to do this for sure ; ) but i got what i needed by registering this StructLevel validation:

```
func FieldStructLevelValidation(sl validator.StructLevel) {
	wholeStruct := sl.Current().Interface().(FieldModel)
	sl.ReportError(wholeStruct.Name, "Name", "name", "jsref", wholeStruct.JSRef)
}

type FieldModel struct {
	ID           bson.ObjectId `bson:"_id,omitempty" json:"id"`
	Type         FieldType     `bson:"type" json:"type"`
	Name         string        `bson:"name" json:"name" validate:"required,ascii"`
	Slug         string        `bson:"slug" json:"slug"`
	Desc         string        `bson:"desc" json:"desc"`
	DisplayOrder uint          `bson:"displayorder" json:"displayorder"`
	Repeatable   bool          `bson:"repeatable" json:"repeatable"`
	JSRef        string        `json:"jsref"`
	Fields       []*FieldModel      `bson:"fields" json:"fields" validate:"dive"`
}
```

Then, when i'm collecting the errors i check whether the "error" is  just actually a "jsref" type of error and add it to a map for later comparison, as now i have the value of the JSRef field spit out in the "param". From there i can  generate the final JSON error output . 

Thanks a lot!!

**Comment by joeybloggs** [comment]
glad it worked for you @pipejesus

Ya there isn't a great way right now, but it all works and the most important thing is consistent error reporting output.

There is one more way you could do this if your interested, the very first value passed to `ReportError` will be accessable in the resulting `FieldError` from the [Value](https://github.com/go-playground/validator/blob/v9/errors.go#L134) that way you can get the jaref value and also a param of one exists...May also be a little more idiomatic.
