### ISSUE TITLE
image field validation

### ISSUE THREAD

**Issue by junaidaziz-kwanso** [go-playground/validator#270]
### Question:

How can i validate image field on struct level is image present or it is image not other files

**Comment by joeybloggs** [comment]
@junaidaziz-kwanso It depends on how your storing it in your struct I suppose, more details are definitely needed; what does your struct look like?

**Comment by junaidaziz-kwanso** [comment]
@joeybloggs 
here is code for y struct

type WatermarkStep struct {
	WatermarkImage string `json:"watermark_image"`
	X              int    `json:"x"`
	Y              int    `json:"y"`
}

how can i check if watermark_image is present and is valid image

here function for validation

func WatermarkStepStructLevelValidation(sl validator.StructLevel) {

	watermarkStep := sl.Current().Interface().(WatermarkStep)

	if watermarkStep.X <= 0 {
		sl.ReportError(watermarkStep.X, "X", "x", "X must be greater then 0", "")
	}

	if watermarkStep.Y <= 0 {
		sl.ReportError(watermarkStep.Y, "Y", "y", "Y must be greater then 0", "")
	}

}

**Comment by joeybloggs** [comment]
Oh ok @junaidaziz-kwanso so it's a path to a file on disk.

So for checking if it's present you can use `os.Stat()` to determine if the file exists by checking if error returned is nil or not.

As for checking if it's valid, it depends on your situation, you could:
- Check the file extension e.g. .PNG, .Jpg.. if that can be trusted
- if it can't be trusted you could look into using the image package to decode the file and if it fails then it's not valid.
- if the image is coming from an http request you could get and store the mime type alongside of the file path and validate it's validity based off of that field (this is the way I do it most of the time)

Sorry for the formatting but answering from my phone, not at a computer yet ;)

Please let me know if this helps or you need any help:)

**Comment by junaidaziz-kwanso** [comment]
yeah basically i am building a api which will receive file and process on image and i am new on golang so i am little confuse how to validate image presence and type i found this package really good to handle my params

**Comment by junaidaziz-kwanso** [comment]
@joeybloggs can you share a snippet or example

**Comment by joeybloggs** [comment]
Ya no problem @junaidaziz-kwanso just give me a couple hours, I'm getting ready for work now :)

**Comment by junaidaziz-kwanso** [comment]
@joeybloggs ok sure waiting for your response

**Comment by joeybloggs** [comment]
ok @junaidaziz-kwanso so normally I have a struct like this:
```go
// Image struct for image information and storage location
type Image struct {
    Path        string `validate:"required"`
    Filename    string `validate:"required"`
    Ext         string `validate:"required"`
    ContentType string `validate:"required"`
    Bytes       int32  `validate:"required,gt=0"`
}
```

Then parse the form and normal stuff
```go
// 1024 * 1024 * 2 = 2MB
if err = r.ParseMultipartForm(1024 * 1024 * 2); err != nil {
    fmt.Println(w, "There was an error parsing the form values.")
    return
}
```

then process the file information into the struct:
https://golang.org/pkg/net/http/#Request.FormFile
```go
file, header, err := r.FormFile("File")
if err != nil {
    ...
}

// copy file to final destination, verify size limits or whatever your application does

// note: if copied to final destination and/or renamed use those value(s) instead of 
header.Filename for Path, Filename and Ext.
img := Image{
    Path: filepath.Dir(header.Filename),
    Filename: filepath.Base(header.Filename),
    Ext: filepath.Ext(header.Filename),
    ContentType: header.Header.Get("Content-Type"),
    Bytes: // can get this while copying or other ways....
}
```

then you can validate the `Content-Type` in your struct validaiton to ensure it's a supported image type; you may even want to verify that before doing all of the copying etc... but that's up to you.
```go
// var somewhere
var acceptedImages = map[string]struct{}{
    "image/png": struct{}{},
    "image/jpg": struct{}{},
    ...
}

// in struct validation, assuming you're also storing Content-Type
if _, err := os.Stat(watermarkStep.WatermarkImage); err!=nil {
    sl.ReportError(watermarkStep.WatermarkImage, "WatermarkImage", "WatermarkImage", "image not found", "")
}
if _, ok := acceptedImages[watermarkStep.ContentType]; !ok {
	sl.ReportError(watermarkStep.ContentType, "ContentType", "ContentType", "unsupported image type", "")
}
```

Hope this Helps 😄  think you'll be able to adapt to your needs; let me know if you need anymore help.

**Comment by junaidaziz-kwanso** [comment]
@joeybloggs thanks for your response currently working on task i will ping you if stuck 👍
