### ISSUE TITLE
package gopkg.in/go-playground/validator.v9: exit status 128

### ISSUE THREAD

**Issue by fasilenko** [go-playground/validator#272]
### Package version v9: 

$ go get -u gopkg.in/go-playground/validator.v9
cd .; git clone https://gopkg.in/go-playground/validator.v9 /Users/Stalker/Workspace/src/gopkg.in/go-playground/validator.v9
Cloning into '/Users/Stalker/Workspace/src/gopkg.in/go-playground/validator.v9'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/go-playground/validator.v9: exit status 128

### Issue, Question or Enhancement:

What is going on??

Thanks for advance!

**Comment by joeybloggs** [comment]
@fasilenko  It looks like GitHub or Gopkg.in is having some problems, the key error is `error: RPC failed` and `fatal: The remote end hung up unexpectedly`

this has happens to me a few times a year, I assure you it has nothing to do with `validator` itself.

I just did a `go get -u gopkg.in/go-playground/validator.v9` to confirm and it successfully completed for me.

#### Other Possibilities
- Internet connection issues.
- Firewall or proxy is blocking.

What OS are you using? and what Git version?

**Comment by fasilenko** [comment]
@joeybloggs Yes, you're absolutely right regarding "It looks like GitHub or Gopkg.in is having some problems"...
Currently everything is ok! And I'm happy :)
Thanks!

**Comment by yankeys** [comment]
i'm windows , i'll tell you in secret, just reload
