### ISSUE TITLE
How can i return json field name from Field() instead of 

### ISSUE THREAD

**Issue by semir-karic** [go-playground/validator#274]
Package version V9

Can I return a json name from structure fields instead of GO structure field name ?
 Example 
```go
ID    int64  `json:"-,omitempty" db:"id"`
Email        string `json:"email" validate:"required"`
Password     string `json:"-" db:"-" validate:"required"`
FirstName    string `json:"first_name" db:"first_name" validate:"required"`
LastName     string `json:"last_name" db:"last_name" validate:"required"`
```

When validating this struct I want to know if it's possible to return "first_name" instead of "FirstName" when calling err.Field()

Thanks

**Comment by joeybloggs** [comment]
Hey @semir-karic 

yep that's totally doable, you just have to [Register a Custom Tag Name function](https://github.com/go-playground/validator/blob/v9/validator_instance.go#L120)

e.g.
```go
validate := validator.New()
validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
	name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]

	if name == "-" {
		return ""
	}

	return name
})
```

Thanks for the question, let me know how it goes :smile:

**Comment by semir-karic** [comment]
That's it thanks a alot. I've just added if the name is "-" or "-" to display the field name from structure in case I don't have json tag set for any of the fields.

**Comment by joeybloggs** [comment]
Awesome glad it worked :thumbsup:
