### ISSUE TITLE
GET REQUEST VALIDATION

### ISSUE THREAD

**Issue by theobouwman** [go-playground/validator#276]
How can I validate variables in a get request?
Something like this:
```
err = c.Validator.Struct(&request.URL.Query())
```

**Comment by joeybloggs** [comment]
Hey @theobouwman 

You can validate every URL value on its own using 'validate.Var(...)`

or decode the URL.Values into a struct and then validate the struct. Check out [form](https://github.com/go-playground/form) for decoding URL.Values into struct.

Sorry about no code example, answering from my phone..Let me know if this helps :)

**Comment by theobouwman** [comment]
Thanks, I can not decode the URL.Values
But I throws an error:
```
type ModuleRequest struct {
	ModuleUUID uuid.UUID `validate:"required"`
}

	var request ModuleRequest

	fmt.Println(r.URL.Query())

	decoder := form.NewDecoder()
	err := decoder.Decode(&request, r.URL.Query())
	if err != nil {
		fmt.Println(err)
		http.Error(w, "Could not decode Request Values", http.StatusBadRequest)
		return
	}

	fmt.Println(request)

	err = config.Validator.Struct(&request)
	if err != nil {
		errorString := "Validation errors:"
		for _, err := range err.(validator.ValidationErrors) {
			errorString += " " + err.Field() + ";"
		}
		http.Error(w, "Bad request data; " + errorString, http.StatusBadRequest)
		return
	}
```
When I pas the `module-uuid` parameter the `ModuleUUID` field of the request object is still set to its zero-value. So I think something is going wrong during the decoding.

**Comment by joeybloggs** [comment]
Hey @theobouwman 

Ok so your query param is all lowercase `module-uuid` and the form library doesn't know what field that is in the struct unless the field name matches or you add the following to the field tag `form:"module-uuid" so it knows which field it should decode it into.

**Comment by theobouwman** [comment]
Thanks that worked.
But it throws this: ```2017/03/08 18:12:20 http: panic serving [::1]:56843: reflect: call of reflect.Value.IsNil on array Value
``` now...

**Comment by joeybloggs** [comment]
I'm far away from my computer right now but I think it may have something to do with `uuid.UUID` type

Although it's underlying type is string, which form is seeing,  a uuid isn't really a string...If that's the case then you just have to register the uuid.UUID type with form...I know it seems like allot and I wish I was near a computer to confirm...But let me know ow if that works

**Comment by theobouwman** [comment]
@joeybloggs you are right, I have to register `uuid.UUID` as a type.
The documentation says that you need to register it on the `Decoder`, however what is a good practice to do that, because you don't want to register it every single? (Golang is pretty new to me)

**Comment by joeybloggs** [comment]
Oh I see both form and validator are intended to be initialized only once and then that instance reused eg.
```go
decoder := form.NewDecoder(...)
```
Then use decoder over and over throughout your entire application, it along with validator, cache the struct information for speed and efficiency.

Could create a utility package which has both form and validator exposed.

The way I do it is have a struct with applications variables etc on it and my http handlers are just a function of that struct and so each handler has direct access to form and validator; if your new to go that may seem co fusing...I will post a sample later on in the day when I find some time though.

**Comment by theobouwman** [comment]
@joeybloggs thanks. Could you mention me on that example?

**Comment by theobouwman** [comment]
@joeybloggs I have a Config package with a few variables that need to be accessed throughout the application. So whenever I need them I import that package.
Is that inefficient?

**Comment by joeybloggs** [comment]
No @theobouwman it is not inneficient and works for most projects just fine.

However once a project gets to a certain size it just becomes easier and easier for a config type package to become a dumping ground for anything and it can get harder to keep separations of concerns; it's like having a function that more and more parameters keep getting added, even if you only use two.
 
Here is how I would do it.
```go
package users

type UserConfig struct {
  // application vars
}

func New(whatever vars the user handlers need) *UserConfig{
  return & UserConfig {
    // Set vars
  }
}

func(app *UserConfig) GetUsers(w http.ResponseWriter, r *http.Request) {

    // now I have access to all the UserConfig vars directly app.WhateverVar
}

// And in main package
users := users.New(...)
http.HanderFunc("/users", users.GetUsers)
```

Doing it this way allows you to split/keep your applications logic in its rightful place and only exposes what you want to each of your handlers.

Note: you can be as fine grained as you want with splitting your http handlers into packages like the users package above...It is not strictly necessary though.
