### ISSUE TITLE
examples directory should be _examples

### ISSUE THREAD

**Issue by nicpottier** [go-playground/validator#279]
### Package version eg. v8, v9: 

9.3.6

### Issue, Question or Enhancement:

When pulling in validator via a go-vendoring tool like glide, all the dependencies of the examples are pulled in, including gin-gonic etc.. Noticed this was an issue both for validator and universal-translator.

I believe the convention is to name your examples directory `_examples` and then those will be ignored by tools such as this.

### Code sample, to showcase or reproduce:

```
% glide get github.com/go-playground/validator

# try to build, will fail due to examples dir having outside dependencies

```

**Comment by joeybloggs** [comment]
@nicpottier I have not encountered `_examples` as a convention for the filenames

This seems like an issue with `glide` itself; it should not be grabbing dependency imports except those referenced from the `validator` package.

Which means that it is behaving contrary to `go get`

If this is happening I would file an issue with `glide` as it is not behaving correctly or perhaps there is an option/argument for it.

Please let me know what comes of this, I am interested to know the results :)

**Comment by joeybloggs** [comment]
Ok I see what's happening `glide` must be running `go install ./...` or `go build ./...` which is recursive.

`go get` does not behave this way it runs `go install` or `go build`

perhaps try passing the `-d` flag like go get.
```
The -d flag instructs get to stop after downloading the packages; that is,
it instructs get not to install the packages.
```

You are correct the go build will ignore any directory beginning with and `_`, `.` or the `testdata` directory.

I will look into renaming the `examples` directory in all my pacakges to `_examples` to avoid this issue, but I still see it as an issue with `glide`

**Comment by nicpottier** [comment]
Cool ya, mostly just flagging this as I imagine anybody else using glide is having trouble with it and the fix seems pretty easy. (though it is a weird convention)

Thanks for considering the change!
