### ISSUE TITLE
Translate or change field names. 

### ISSUE THREAD

**Issue by james-maloney** [go-playground/validator#281]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Question

### Code sample, to showcase or reproduce:

Is there a way to translate the param name when an error occurs?

For instance:

If I want to translate the "required" rule like "{0} must have a value!" and the name of the struct field is "Name" how do I translate "Name" when it replaces "{0}"?

I have toyed around with using `validate.RegisterTagNameFunc` but that also changes the key name which is an issue.

Thanks

**Comment by joeybloggs** [comment]
No there's currently no way to customize the field name, usually I keep the messages generic.

If you keep them generic then after validation could have your own logic to translate the field name and combine with the rest of the translation...or just handle the whole translation after an error.

Haven't yet thought of a good way to dynamically change the field name.

**Comment by james-maloney** [comment]
Good to know. 

Thanks for answering my question, I appreciate the work you have put into your Go packages.

**Comment by joeybloggs** [comment]
Thanks @james-maloney means a lot :)

Actually there may be a way to do what your looking for, when registering a translation function your could reference a pre-built map, or translation from within your function and while building the translation could substitute the Field name with whatever your want.

I admit it is an annoying amount to boilerplate to define a translation for every field name, but at least you only have to do it once...per language :(

I wish I could think of a better way to do it, but the reality is for everything you want to translate you have to have a translation for...

Open to any suggestions or ideas anybody has :)
