### ISSUE TITLE
How to get field name

### ISSUE THREAD

**Issue by s4l1h** [go-playground/validator#282]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:
How to get field name eg: **Name**
### Code sample, to showcase or reproduce:

```go

// Group Models
type Group struct {
	Name        string `json:"name" validate:"unique,required"`
	Description string `json:"Description" validate:"required"`
}

var valid = validator.New()
valid.RegisterValidation("unique", ValidUnique)

func ValidUnique(fl validator.FieldLevel) bool {
        //How to get field name eg: Name
	fmt.Printf("Validating %s\n", fl.Field())



	return false
}
```

**Comment by joeybloggs** [comment]
Hey @s4l1h 

So I'm assuming you are looking to access the struct field name from within the validation, currently there is no method to get that value...bit after a validation fails your can https://github.com/go-playground/validator/blob/v9/examples/simple/main.go#L72

Any reason you need the field name from within the validation?

**Comment by s4l1h** [comment]
check if record exists in database

important problem

```go

// Group Models
type Group struct {
	Name        string `json:"name" validate:"unique,required"`
	Description string `json:"Description" validate:"required"`
}

var valid = validator.New()
valid.RegisterValidation("unique", ValidUnique)

func ValidUnique(fl validator.FieldLevel) bool {

	currentField, _, _ := fl.GetStructFieldOK()
	table := currentField.Type().Name() // table name
	value := fl.Field().String() // value
        column := "????" // need this..
	sql := fmt.Sprintf("select count(*) from %s where %s='%s'", table, column, value)
	if Count(sql) { // check database...
		return false
	}
	return true
}
```

**Comment by joeybloggs** [comment]
@s4l1h makes perfect sense

I think I can pass the cached filed info along and then add a couple of methods to the FieldLevel interface to access both the struct and alt name's.

It may take me a few days, I'm out of town right now, but will try to make the changes asap.

**Comment by s4l1h** [comment]
@joeybloggs thanks for reply and effort.I can help.
Pls check pr.
