### ISSUE TITLE
Validating DB custom types with Valuer interface not working

### ISSUE THREAD

**Issue by bogh** [go-playground/validator#289]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I have a custom implementation of a struct that extends `sql.NullFloat64`. But even if I use the `sql.NullFloat64` validation still doesn't work for this field. If I use `float64` instead the validation works.
The documentation says that is should work for `Valuer` implementations.

### Code sample, to showcase or reproduce:

```go
type Data struct {
	Latitude       types.NullFloat64 `json:"latitude" validate:"gte=-180,lte=180"`
	Longitude    types.NullFloat64 `json:"longitude" validate:"gte=-180,lte=180"`
}

type NullFloat64 struct {
	sql.NullFloat64
}

```

**Comment by joeybloggs** [comment]
Hey @bogh 

I guess the document should say has support for Valuer and overriding behaviour of any type. It works, just not out of the box, but it's only a few lines of code, please see the [custom example](https://github.com/go-playground/validator/blob/v9/_examples/custom/main.go); I only register some of the SQL.Valuer types in the example, but you can add the rest.

Explanation of why it's not handled out of the box:
1. The current way works with not only Valuer types, but any custom type you wish to handle the value differently.
2. Validator doesn't want to make assumptions about what is an ok value for Valuer or not eg. When the Valuer field value is nil say for an `sql.NullFloat64`, some people want the default value of 0.0 returned for validation, others may want nil; it all depends on your application.

Please let me know if this makes sense :) and if you have any trouble getting it working.

**Comment by bogh** [comment]
@joeybloggs Makes perfect sense. Thanks for clarifying. 

Don't have a problem that it's not out of the box :D
