### ISSUE TITLE
Error when put 0 for required int field

### ISSUE THREAD

**Issue by phamduong** [go-playground/validator#290]
### Issue, Question or Enhancement:
I try to put 0 as value for a required in field and the it says missing required field

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type StockPutForm struct {
	Quantity int `validate:"required"`
}

func main() {
	mystruct := StockPutForm{Quantity:0}
	validate := validator.New()
	err := validate.Struct(mystruct)
	fmt.Println(err)
}

```

> Key: 'StockPutForm.Quantity' Error:Field validation for 'Quantity' failed on the 'required' tag

0 is valid value for int then it should work.

Could you please help.
Thanks.

**Comment by phamduong** [comment]
My bad, it's documented.
Sorry,

**Comment by joeybloggs** [comment]
It's also documented in the [godocs](https://godoc.org/gopkg.in/go-playground/validator.v9) under the `required` definition

Yes exists was removed because it was confusing, and functionality merged into required.

Just make your interested a pointer and keep using required tag.

**Comment by joeybloggs** [comment]
Just checking in, did you get this all working?

**Comment by phamduong** [comment]
it works.
Thanks

**Comment by shyandsy** [comment]
@deankarn 
what doesn mean by "Just make your int a pointer and keep using required tag."?

**Comment by Hermsi1337** [comment]
> @deankarn
> what does it mean by "Just make your int a pointer and keep using required tag."?

It means that you should use a pointer to an integer instead of an integer itself.

From:
```golang
type Testing struct {
	Delay uint `validate:"required"`
}
```

To:
```golang
type Testing struct {
	Delay *uint `validate:"required"`
}
```

That way `validate:"required"` ensures that the pointer is not `nil` instead of ensuring the value of the integer is not `0`.

**Comment by Mehrdad-Dadkhah** [comment]
@deankarn @Hermsi1337 

Bad solution :/

**Comment by cbrom-huma** [comment]
@deankarn well, it wouldn't be logical to change field type to pointer just for validation. What if I specifically need the field to be a non pointer?

**Comment by zemzale** [comment]
@cbrom-huma In Go, you don't have any other way how check if a value is set, except comparing it with the zero value. 

And for `int` the zero value is `0`. 

```go
var n int // Value is 0
m := 0 // Value is 0
```

And so if you create a struct without setting a value 
```go
type Testing struct {
	Delay int `validate:"required"`
}

var t Testing
fmt.Println(t.Delay) // output is 0
```
The only way how we can check if the value is set when the required tag is added, we can only compare it against the default value. 

If you want to check if a value is never set you have to use pointers. If you can provide an example of how we could do that I would be glad, but this is the way how Go is designed and we can't do anything about it. 


See: https://go.dev/play/p/6nmYMTzg6oN
https://stackoverflow.com/questions/31048557/assigning-null-to-json-fields-instead-of-empty-strings

**Comment by Azunyan1111** [comment]
i do this
```
`validate:"min=0"`
```

**Comment by yutaronakayama** [comment]
If anyone knows this, let me know please.
https://github.com/go-playground/validator/issues/290#issuecomment-1254645233

**Comment by goyzhang** [comment]
> i do this
> 
> ```
> `validate:"min=0"`
> ```

then it's not required.

**Comment by daronphang** [comment]
An alternative is do create a custom validator and register it in the validator. More intuitive than assigning a pointer to a field type.

This also works for validating boolean.

```go
type Example struct {
    someNumber int `validate:"int_required"`
}

func IntRequired(fl validator.FieldLevel) bool {
    defer func() {
        _ = recover();
    }()
    _ = fl.Field().Int()
    return true
}

func main() {
    v := validator.New()
    if err := v.RegisterValidation("int_required", IntRequired); err != nil {
        // do something
    }
}
```

**Comment by GRASBOCK** [comment]
> Bad solution :/

I was annoyed by the removal of exists at first too, but eventually understood, that this is out of scope of the validator. 
In my case I was validating a struct already unmarshaled from json. There is no way for the validator to know what key was not present in the json struct. You should do that kind of validation before passing it into the validator.

I don't know how everyone else here uses it, but the question for me is rather what solution do you expect?
