### ISSUE TITLE
Validating full name

### ISSUE THREAD

**Issue by mbn18** [go-playground/validator#291]
### Package version eg. v8, v9: 

`v9`

### Issue, Question or Enhancement:

Is it possible to validate `AlphaNumeric` value that include `space`, `dash` or any other char?
Or do I have to write a custom validator?

### Code sample, to showcase or reproduce:

Notice the Name. I wish it to accept "John Doe" or "John-Doe"
```go
type UserEnrollRequest struct {
	Name     string `json:"name" validate:"required,alphanum,gte=3"`
	Email    string `json:"email" validate:"required,email,emailUnique"`
	Password string `json:"password" validate:"required,gte=6"`
}
```

**Comment by joeybloggs** [comment]
Hey @mbn18 

You'd have to create a custom one, but should be pretty easy just copy-paste the current alphanum regex and add space and dash characters and register the new validation.

If you need any help just let me know.

**Comment by mbn18** [comment]
Thanks @joeybloggs , no problem, will do it.
As a suggestion, maybe it could be beneficial to support something like this:
```go
type UserEnrollRequest struct {
	Name     string `json:"name" validate:"required,alphanum=32+95+45,gte=3"`
}
```
In this example `alphanum=32+95+45` I added the ascii value of space, dash, underscore.

**Comment by joeybloggs** [comment]
@mbn18 thanks for the idea, but it's rare that regexes are that straight forward.

Besides if I was another developer coming to read this code, I wouldn't have a clue what '32+95+45' meant. It will/could make the tags harder to read and much longer.

I have document [here](https://godoc.org/gopkg.in/go-playground/validator.v9) why I don't have a regex tag( near the bottom) and this is pretty much the same.

I should probably add that in a clearer place in the README.

**Comment by mbn18** [comment]
Thanks
