### ISSUE TITLE
add tag unique

### ISSUE THREAD

**Issue by ipiao** [go-playground/validator#300]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question:
  - can you add a tag named unique for that value in  slice not  repeated,please

### Code sample, to showcase or reproduce:

```go
type Settings struct {
    Slice  []string `validate:"unique"`
}
```

**Comment by joeybloggs** [comment]
Thanks @ipiao seems like a reasonable new validation.

**Comment by ipiao** [comment]
Thank you @joeybloggs
