### ISSUE TITLE
how to validate param in slice

### ISSUE THREAD

**Issue by ipiao** [go-playground/validator#303]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:
Question:
  how can i validate fiirst param in a slice?
eg. i want to validate  whether Search[0] equals to "name"

### Code sample, to showcase or reproduce:

```go
 Search        []string `validate:"dive,eq=name"`
```

**Comment by joeybloggs** [comment]
Hey @ipiao sorry for the late reply, been super busy

there's no build in way to validate only a single array or map value using a tag validation, but you can add a `Struct Level` validation for this use case that works with your other tags, see [here](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go)

It seems like a very one off case.

**Comment by ipiao** [comment]
thank you @joeybloggs
