### ISSUE TITLE
FQDN validator panics on empty string

### ISSUE THREAD

**Issue by nu11ptr** [go-playground/validator#306]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

When the 'fqdn' validator is supplied an empty string it panics with 'index out of range'. Glancing at the code, this is because it takes the length of the string minus one, but never checks to see if it was empty first. Adding a 'required' validator first works as a workaround.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type Foo struct {
	Bar string `validate:"fqdn"` // Panics on empty struct
	//Bar string `validate:"required,fqdn"` // Works as expected
}

func main() {
	f := &Foo{}
	v := validator.New()
	err := v.Struct(f) // panic: runtime error: index out of range
	if err != nil {
		fmt.Println("Error was: ", err)
	}
}
```

**Comment by joeybloggs** [comment]
Thanks @nu11ptr I'll correct ASAP
