### ISSUE TITLE
Support for conditional mandatory fields

### ISSUE THREAD

**Issue by DanielDHuynh** [go-playground/validator#308]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
It would be nice if a field could be validated as `required` only when another field has a specific value.
In the code example, the `FinLength` is only mandatory if the `Type` is `fish`.
I tried to implement a custom validation but I couldn't end the validation pipeline when the field is not required. I looked into how `omitempty` was done and it's not a conventional tag.

### Code sample, to showcase or reproduce:

```go
type Animal struct {
  Type Type
  LegLength int `validate:"requireIf=mammal@Type,numeric,gte=0"`
  FinLength int `validate:"requireIf=fish@Type,numeric,gte=0"`
}
```

**Comment by joeybloggs** [comment]
Hey @DanielDHuynh thanks for the suggestion.

Although this is possible to code, I highly recommend to everyone that once the validation reaches this level of complexity to use [struct level validation](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go); it can also be combined with validation via tags(they work together)

If I added this type of logic it would severely clutter the tags and make them hard to read; but beyond that doing it via [struct level validation](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go) with be much more performance as well.

Hope this answer helps :)

**Comment by DanielDHuynh** [comment]
Hi @joeybloggs,

I think this is a good solution, thank you!

**Comment by RajeshMalla** [comment]
@deankarn  is StructLevel Validation possible with v8 version ?
