### ISSUE TITLE
How can i validate the slice or map? Can you please guide me?

### ISSUE THREAD

**Issue by anam-digicom** [go-playground/validator#309]
### Code sample, to showcase or reproduce:

```go

```

**Comment by joeybloggs** [comment]
Hey @anam-digicom you would need to use the dive tag documented [here](https://godoc.org/gopkg.in/go-playground/validator.v9)

basic example:
```go
type User struct {
  Foo []string `validate"required,dive,ne=bar"`
}
```

let me know if that helps.

**Comment by denouche** [comment]
Hey @joeybloggs 

This works with a struct containing a slice field, but how to validate a slice using `validate.Struct(mySliceOfStructs)` ?

Thanks!

**Comment by joeybloggs** [comment]
@denouche because your validating a variable at this point you would use validate.Var(mySliceOfStructs, “required,dive”) or if not required use “omitempty,dive”

**Comment by denouche** [comment]
Nice, it works great.

So fast to answer, great answers, nice library!

Thank you!
