### ISSUE TITLE
Custom type validation on non-required field

### ISSUE THREAD

**Issue by denouche** [go-playground/validator#314]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:

Hello, I'm playing with a case similar to this one:
https://github.com/go-playground/validator/blob/946d44437639ac503e2cf068cd8d7f221084cf90/_examples/custom/main.go#L14

In my custom validation function I validate the field format, it works as expected.
But in my case, the field is not required. When I remove the `required` in the validation tag, such as `validate:""`, it also stops to call my custom validation function.

How to achieve this?

Thank you

**Comment by joeybloggs** [comment]
validate only caches fields that need validation, for performance and efficiency; I think you may be confused about what the custom type function is for.

The custom type fund is not used for validation at all, it’s used to transform the data from one form to another for validations to use; for example sql.NullString some people will be ok with a null value and so if it’s null return a string, other return null so it will error on required.

It is in a general sense used to extract the data you to validate from custom types, fields that are an interface like sql.Valuer or io.Reader; types that are not programmed into validator.

and then another validation function actually does the validation on the transformed data.

Hope I’m making sense.

**Comment by denouche** [comment]
Make sense, thank you
