### ISSUE TITLE
Is `func (*Validate) Struct` thread-safe ?

### ISSUE THREAD

**Issue by 7fELF** [go-playground/validator#315]
### Package version: 
v9
### Issue, Question or Enhancement:
Question

I'm using  `func (*Validate) Struct` to validate API requests.
Is that safe to use only one instance of `Validate` for the whole project considering there may be simultaneous calls to `(*Validate) Struct()`?

**Comment by joeybloggs** [comment]
Hey @7fELF great question

And the answer is yes it is completely thread/goroutine safe and is designed to be used with a single instance. Validator also caches information about your struct and validations, in essence only parsing your validation tags once per struct type, without a single instance you wouldn’t get the advantages of the cache.

**Comment by 7fELF** [comment]
Thanks for the quick answer :smile:

**Comment by andrascz** [comment]
> Hey @7fELF great question
> 
> And the answer is yes it is completely thread/goroutine safe and is designed to be used with a single instance. Validator also caches information about your struct and validations, in essence only parsing your validation tags once per struct type, without a single instance you wouldn’t get the advantages of the cache.

Could be this represented somewhere in the documentation? There are some functions noted as not thread-safe which is not really an assurance that the other functions are thread-safe.

**Comment by deankarn** [comment]
PRs welcome @andrascz
