### ISSUE TITLE
Problem with data type validator

### ISSUE THREAD

**Issue by lbozza** [go-playground/validator#316]
### Package version eg. v8, v9: 

V9
### Issue, Question or Enhancement:
Hello i'm trying to use the validator to validate a json object, the problem is that when I try to send an int instead of a string (which the set type fo the field) I get an error, and not just for this field, i get an error for all the following fields that needs to be validated.

### Code sample, to showcase or reproduce:

  "currency": "123",
  "country": "BR",
  "integration": {
    "notificationUrl": "",
    "language": "pt_BR",
    "sandboxMode": true
  },
  "store": {
    "id": 10,
    "projectNumber": 1
  },
  "customer": {
    "email": "testing@email.com,
    "ip": "172.21.112.178"

```go

type Charging struct {
	Reference	string `validate:"required,gte=1,lte=100"`
	Currency    int `validate:"required"`
	Country     string `validate:"required,len=2"`
	Integration Integration
	Store       Store
	Customer    Customer
	Cart        []Product `validate:"dive"`
	Payments	[]Payment `validate:"dive"`
}

```

 Key: 'Charging.Currency' Error:Field validation for 'Currency' failed on the 'required' tag
Key: 'Charging.Country' Error:Field validation for 'Country' failed on the 'required' tag
Key: 'Charging.Integration.NotificationUrl' Error:Field validation for 'NotificationUrl' failed on the 'required' tag
Key: 'Charging.Integration.Language' Error:Field validation for 'Language' failed on the 'required' tag
Key: 'Charging.Store.Id' Error:Field validation for 'Id' failed on the 'required' tag
Key: 'Charging.Store.ProjectNumber' Error:Field validation for 'ProjectNumber' failed on the 'required' tag
Key: 'Charging.Customer.Email' Error:Field validation for 'Email' failed on the 'required' tag
Key: 'Charging.Customer.Ip' Error:Field validation for 'Ip' failed on the 'required' tag

Shouldn't I get the error just for the invalid field at question? which is Currency?

Thanks

**Comment by joeybloggs** [comment]
Hello @lbozza 

Would you be able to provide a more complete example? It’s a little difficult to diagnose with an incomplete picture, I have no idea how you populated the struct, which json library was used or what validations or json tags are set on the internal struct fields.

Have you printed out the struct to ensure the data that was decided into it? I suspect that it might not the data.

**Comment by lbozza** [comment]
hey @joeybloggs , here its a little bit more of code:
``package charging

import (
	"encoding/json"
	"gopkg.in/go-playground/validator.v9"
)

var validate *validator.Validate

func init() {
	validate = validator.New()
}

type Charging struct {
	Reference	string `validate:"required,gte=1,lte=100"`
	Currency    string `validate:"required,len=3"`
	Country     string `validate:"required,len=2"`
	Integration Integration
	Store       Store
	Customer    Customer
	Cart        []Product `validate:"dive"`
	Payments	[]Payment `validate:"dive"`
}

func (c *Charging) Validate() error {
	return validate.Struct(c)
}

func NewCharging(dataAsJson []byte) (Charging, error) {
	var charging Charging

	json.Unmarshal(dataAsJson, &charging)

	err := charging.Validate()

	if err != nil {
		return Charging{}, err
	}

	return charging, nil
}  ``

the Json that is populating the structs is the following one:

{
  "reference": "1504881290",
  "currency": "BRL",
  "country": "BR",
  "integration": {
    "notificationUrl": "https://notify.me",
    "language": "pt_BR",
    "sandboxMode": true
  },
  "store": {
    "id": 10,
    "projectNumber": 1
  },
  "customer": {
    "email":test@email.com",
    "ip": "172.21.112.178"
  },
  "cart": [
    {
      "amount": 1.0,
      "description": "1"
    },
      {
      "amount": 1.0,
      "description": "produto teste"
    }
  ],
  "payments": [
    {
      "amount" : 1.0,
      "payer": {
        "senderHash": "04ef57c7ef311e81753f26f3b448fedad0dbba33bc36cf2404f442de7f811b33",
        "name": "teste da silva",
        "cpf": "00000000191",
        "bornDate": "1990-10-10",
        "phoneNumber": "4484050955"
      },
      "paymentMethod": {
        "type": "credit",
        "token": "2e614ed14f324445a06df6683a25be1b",
        "maskedCardNumber": "************0183",
        "brandName": "visa",
        "installments": {
          "value": 1,
          "quantity": 1
        }
      }
    }
  ]
}

**Comment by joeybloggs** [comment]
@lbozza that makes sense, you can always make your struct implement `UnmarshalJSON` and you could decode that field to a `json.Number` in a custom struct and then populate the string field with the int value.

**Comment by lbozza** [comment]
HEY @joeybloggs thanks for the tip.
