### ISSUE TITLE
How to check if fieldType of a struct is of type const enum

### ISSUE THREAD

**Issue by yokanandCIC** [go-playground/validator#318]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
How to check if fieldType is of type const enum

### Code sample, to showcase or reproduce:

```go

```
type Person struct {
        Name           string  `json:"name" validate:"required"`
        currency       string `json:"currency" validate:"required"` 
        phone          string  `json:"phone" validate:"required"`
}
type currency string
const (
eur currency ="eur"
usd          ="usd"
)

I need to validate that currency in person is of type const (either eur or usd)

**Comment by joeybloggs** [comment]
@yokanandCIC  please see issue #313 which is almost exactly the same as what you're asking and I provide 2 examples of how to do it.
