### ISSUE TITLE
Ref to a field

### ISSUE THREAD

**Issue by gangstaJS** [go-playground/validator#322]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

How can I add a validator for fields `password` and `confirmPassword`?

### Code sample, to showcase or reproduce:
at nodejs I am using `Joi` for the case and I can add ref to another field

```javascript
{
 password: Joi.string().required(),
 confirmPassword: Joi.string().required().valid(Joi.ref('password'))
}
```

**Comment by joeybloggs** [comment]
Hey @gangstaJS 

your looking for the `eqfield` tag eg. `validate:"eqfield=ConfirmPassword"`

Please see the [docs](https://godoc.org/gopkg.in/go-playground/validator.v9) all tags should be thoroughly documented there.

**Comment by joeybloggs** [comment]
Please let me know if this worked for you :)
