### ISSUE TITLE
Similar to StructNamespace function for JSON

### ISSUE THREAD

**Issue by sirakuzi** [go-playground/validator#323]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

FieldError interface has StructNamespace func that returns full path to error field in Golang struct terms.
But if you work with JSON - much better to receive same path, but in JSON terms. Example:

### Code sample, to showcase or reproduce:

If name of second child isn't specified - StructNamespace returns "Family.Child[1].Name", but for JSON would be better to receive "child_list[1].name"

```go
type User struct {
    Name string json:"name" validate:"required"
    Age int json:"age" validate:"required"
}
type Family  struct {
    One User json:"one" validate:"omitempty,dive,required"
    Two User json:"two" validate:"omitempty,dive,required"    
    Child []*User json:"child_list" validate:"omitempty,dive,required"    
}
```

**Comment by joeybloggs** [comment]
Hey @sirakuzi 

If you register a `TagNameFunc` you can extract any tag names you want, including `JSON`, and then use the `Namespace()` function instead, `StructNamespace()` will remain unchanged eg.
```go
package main

import (
	"fmt"
	"reflect"
	"strings"

	"gopkg.in/go-playground/validator.v9"
)

type User struct {
	Name string `json:"name" validate:"required"`
	Age  int    `json:"age" validate:"required"`
}
type Family struct {
	One   User    `json:"one" validate:"omitempty,dive,required"`
	Two   User    `json:"two" validate:"omitempty,dive,required"`
	Child []*User `json:"child_list" validate:"omitempty,dive,required"`
}

func main() {
	fam := Family{
		Child: []*User{&User{}},
	}

	validate := validator.New()
	validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]

		if name == "-" {
			return ""
		}
		return name
	})
	raw := validate.Struct(fam)
	errs := raw.(validator.ValidationErrors)

	for _, e := range errs {
		fmt.Println("NS:", e.Namespace(), "SNS:", e.StructNamespace())
	}
}
```

outputs:
```
NS: Family.one.name SNS: Family.One.Name
NS: Family.one.age SNS: Family.One.Age
NS: Family.two.name SNS: Family.Two.Name
NS: Family.two.age SNS: Family.Two.Age
NS: Family.child_list[0].name SNS: Family.Child[0].Name
NS: Family.child_list[0].age SNS: Family.Child[0].Age
```

although the top level struct `Family` remains the struct name as there is no way to get a `JSON` name from it, this should get you 99% of the way to what you're looking for and then just `string.TrimPrefix`

Please let me know if this helps :)

**Comment by nikonor** [comment]
Thank you!! 
You realy helped. 
Early we reflected structs follow splited StructName. And it's was bad.

**Comment by sirakuzi** [comment]
Hey @joeybloggs 
Yeah, that works, thank you! :)
