### ISSUE TITLE
Validate a string as an ISO date?

### ISSUE THREAD

**Issue by jlpellicer** [go-playground/validator#325]
Hi, I'm working on an API that receives a JSON string which is supposed to be a date.
Is it possible to check if the string is a valid ISO 8601 date format?
Thank you

**Comment by joeybloggs** [comment]
@jlpellicer yes you can there is however no built in validation to handle that, but you can easily register a custom validation and tag to use see [here](https://github.com/go-playground/validator/blob/v9/_examples/custom-validation/main.go) for a simple example

If you need anymore help, just let me know :)

**Comment by jlpellicer** [comment]
this will do, thanks!
