### ISSUE TITLE
Mixing string pointers with max

### ISSUE THREAD

**Issue by kickroot** [go-playground/validator#326]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I've scoured over the documentation but can't find an example that covers this use case.  I've got a struct that has string fields that may be nil.  Is it possible to allow nil fields while still enforcing a max length if they exist?  When I attempt to validate  the struct below with nil FirstName, LastName, or DisplayName fields the validation fails:

`Key: 'ModifyUser.LastName' Error:Field validation for 'LastName' failed on the 'max' tag`

I would expect that since `required` is not set for these fields that they would validate when nil.  The obvious workaround is not utilize pointers, but other packages I'm using requires pointers to denote optional fields. I'm trying to utilize the same structs across my application and not use a DTO just for validation.

### Code sample, to showcase or reproduce:

```go
type ModifyUser struct {
	ID          string
	Email       string  `validate:"required,email,max=255"`
	FirstName   *string `validate:"max=64"`
	LastName    *string `validate:"max=64"`
	DisplayName *string `validate:"max=64"`
}
```

**Comment by joeybloggs** [comment]
Hey @kickroot 

I think what your looking for is `omitempty` eg.

`validate:”omitempty,max=64`

Please let me know if that works for you :)

**Comment by kickroot** [comment]
Ah, thanks so much.  I had not seen the `omitempty` directive.
