### ISSUE TITLE
Custom validation with param

### ISSUE THREAD

**Issue by amirkheirabadi** [go-playground/validator#331]
v9
is there a way to create a custom rule validation with params?
for example
```go
type Inputs struct {
	Mobile   string `valid:"mobile(IR),required"`
	Nickname string `valid:"alphanum,required"`
}
```

**Comment by joeybloggs** [comment]
Hey @amirkheirabadi I'm not 100% sure what you mean?

If you mean for the custom validation to always have a certain parameter, then why not hard-code the parameter in your custom validation?

If you mean you wish to have a custom validation that a parameter can be set, but you don't want to set it everywhere, you can use [Register Alias](https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.RegisterAlias) to alias a tag with a parameter, or even many tags.

Please let me know if I'm way off from what your asking, just trying to interpret :)
