### ISSUE TITLE
FieldError Field function returns struct name instead of JSON tag

### ISSUE THREAD

**Issue by kerak19** [go-playground/validator#337]
I do have this struct:

```
data := struct {
    Email    string `validate:"required,email" "json:"email"`
    Password string `validate:"required,min=8" "json:"password"`
}{}
```

Then i'm using `validate.Struct(data)` and i'm ranging over `ValidationErrors`.
Every `Field()` on `error` in `ValidationErrors` returns struct field instead of JSON tag.
For example, `data.Email` has json tag `"email"`, but it retuns `"Email"` instead.
Why is that? Documentation clearly says it should return JSON tag.

**Comment by joeybloggs** [comment]
Hey @kerak19 can you point out exactly where in the documentation that it states it returns the json name by default? and I'll correct right away.

as for grabbing the `json` tag name, you have to register a tag name parser first eg.
```go
        validate := New()
	validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
		if name == "-" {
			return ""
		}
		return name
	})
```

it's done this way in order to allow for parsing of any tag name like json, bson, sql tags etc...

Please let me know if this was helpful :)

**Comment by kerak19** [comment]
So i probably misunderstood this:

    // returns the fields name with the tag name taking precedence over the
    // fields actual name.
    //
    // eq. JSON name "fname"
    // see ActualField for comparison
    Field() string

Thanks for your answer! :)

**Comment by pnicolcev-tulipretail** [comment]
The documentation definitely makes it look like it will pick something like the JSON tag name. I think it would be very useful to add a sentence to the documentation saying something like "You must implement RegisterTagNameFunc if you want to use a tag rather than the struct field name."

**Comment by joeybloggs** [comment]
Thanks @pnicolcev-tulipretail I agree, any chance you could make a PR?

**Comment by Eternity-SXH** [comment]
> Hey @kerak19 can you point out exactly where in the documentation that it states it returns the json name by default? and I'll correct right away.
> 
> as for grabbing the `json` tag name, you have to register a tag name parser first eg.
> 
> ```go
>         validate := New()
> 	validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
> 		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
> 		if name == "-" {
> 			return ""
> 		}
> 		return name
> 	})
> ```
> 
> it's done this way in order to allow for parsing of any tag name like json, bson, sql tags etc...
> 
> Please let me know if this was helpful :)

type RegisterAccountForm struct {
	Account         int `json:"account" validate:"required"`
	Password        string `json:"password" validate:"required"`
	ConfirmPassword string `json:"confirm_password" validate:"required,eqfield=Password"`
}

but tag "eqfield" seems doesn't work,It returns "password必须等于ConfirmPassword"

**Comment by rjcrystal** [comment]
For folks looking to implement this with gin gonic router here's how you can register the `RegisterTagNameFunc` 

```     
router := gin.New()

if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
	v.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
		if name == "-" {
			return ""
		}
		return name
	})
}
//other router operations 
```

**Comment by BarcoMasile** [comment]
Hi, apparently the doc is still not updated. Any news on this?

**Comment by ameghdadian** [comment]
I've registered tag name parser:
```go
	validate = validator.New()

	validate.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
		if name == "-" {
			return ""
		}
		return name
	})
```
I attempt to validate following struct:


```go
type Credentials struct {
	Password        string   `json:"password" validate:"required"`
	PasswordConfirm string   `json:"password_confirm" validate:"eqfield=Password"`
}
```

However, I'm getting this error: 
`password_confirm must be equal to Password`

What I expected to see:
`password_confirm must be equal to password`

Am I missing something?

**Comment by nodivbyzero** [comment]
@ameghdadian Could you ask this question in the `Discussions` section here: https://github.com/go-playground/validator/discussions?  
I believe `Discussions` is a more appropriate place to ask questions.
