### ISSUE TITLE
`FieldWithValue` is not anywhere in the code

### ISSUE THREAD

**Issue by ryan-ju** [go-playground/validator#339]
### Issue, Question or Enhancement:
`FieldWithValue` is in the godoc https://godoc.org/gopkg.in/go-playground/validator.v9, but does not exist anywhere in the source code.

Is the godoc out of date?

**Comment by joeybloggs** [comment]
It was changed in v9 to `VarWithValue` to try and avoid some confusion as some people thought it had to be a struct field; must have missed updating it in the docs, thanks for reporting so I can correct them :)

**Comment by joeybloggs** [comment]
@ryan-ju corrected in Release 9.9.4
