### ISSUE TITLE
Hostname begins with digits is not accpted by the validator.

### ISSUE THREAD

**Issue by dnartz** [go-playground/validator#341]
The regex of hostname is:

```go
 	hostnameRegexString            = `^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$`
```
For hostname like `1.foo.com`, it is rejected by the validator. 
Accroding to [RFC1123](https://tools.ietf.org/html/rfc1123), valid DNS hostnames could be start with digits.

**Comment by joeybloggs** [comment]
Thanks @dnartz I’ll take a look as soon as I can, 
If you wanted to make a PR That’d be awesome too :)

**Comment by joeybloggs** [comment]
Hey @dnartz I added a new validation in [Release v9.10.0](https://github.com/go-playground/validator/releases/tag/v9.10.0) for RFC 1123 hostname called `hostname_rfc1123`

I put a note in the release of how to continue to use the `hostname` tag with it.
