### ISSUE TITLE
looped call CustomTypeValuer fn

### ISSUE THREAD

**Issue by gebv** [go-playground/validator#344]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Why a looped call PointValuer?

### Code sample, to showcase or reproduce:

```go
func TestCustomType(t *testing.T) {
	v := validator.New()
	v.RegisterCustomTypeFunc(PointValuer, Point{})

	if err := v.Var(Point{}, "required"); err != nil {
		t.Error("failed", err)
	}
}

type Point struct {
	X     float64 `json:"lng"`
	Y     float64 `json:"lat"`
	Valid bool    `json:"valid"` // Valid is true if not NULL
}

func PointValuer(field reflect.Value) interface{} {
	if point, ok := field.Interface().(Point); ok {
		return point
	}
	return nil
}

```

**Comment by gebv** [comment]
Looped here

https://github.com/go-playground/validator/blob/v9/util.go#L47


I'm not using the Var function correctly for custom type validation? Please advice @joeybloggs

**Comment by joeybloggs** [comment]
Hey @gebv I think there may be confusion about what `RegisterCustomTypeFunc` is for; here is an example https://github.com/go-playground/validator/blob/v9/_examples/custom/main.go

`RegisterCustomTypeFunc` is really for registering a function to take a certain type and transmute the data into what you want to validate eg.

if I wanted to validate that an [sql.NullString](https://golang.org/pkg/database/sql/#NullString) was required, we would have to get the value out before validating as whether the value is set or not is hidden within the struct `sql.NullString`, which is always set.

so `RegisterCustomTypeFunc` is really for taking the `sql.NullString` and either extracting the string for validation or returning blank or nil.

In your example, the data isn't being transmuted, but the same value is returned causing an infinite loop.

perhaps if I knew exactly what you were trying to accomplish I could provide an example, can you elaborate?

**Comment by gebv** [comment]
I need to validate the lat lng coordinates
Created a custom data type
```go
type Point struct {
	X     float64 `json:"lng"`
	Y     float64 `json:"lat"`
	Valid bool    `json:"valid"` // Valid is true if not NULL
}
```
Added a custom validator, for example always returns false
```go
func ValidationInMoscow(fl validator.FieldLevel) bool {
	// TODO: implement
	log.Printf("DEBUG: check call validator, got data type %T\n", fl.Field().Interface())
	return false
}
```

I want that here I got an error
```go
v := validator.New()
v.RegisterValidation("inmsk", ValidationInMoscow)
v.Var(NullPoint{}, "inmsk")
```

I look at the log, validator was not called. How do I validate a custom type?

**Comment by gebv** [comment]
So, i want got for the my custom object for custom validation.

```go
func ValidationInMoscow(fl validator.FieldLevel) bool {
        // log.Printf("DEBUG: check call validator, got data type %T\n", fl.Field().Interface())

        point := fl.Field().Interface().(NullPoint)

        if point == nil { return false } // how to customize the validator 'required'?

	return inMSK(point) // check intersection in poligon
}
```

 @joeybloggs please any ideas

**Comment by joeybloggs** [comment]
Normally validating with .Var isn’t for struct so have been thinking about how to accomplish this best.

I think creating a StructLevel validation is what your looking for and in that you can do your inmsk check, and report the error as you see fit and then you can use the validate.Struct instead of validate.Var. There should be an example in the repo.

Sorry for the lack of examples, answering from my phone, but will try and add one tomorrow morning for you(assuming you still need one)

**Comment by gebv** [comment]
Yes, please attache your examples
Meanwhile I'll see how StructLevel works

**Comment by joeybloggs** [comment]
@gebv 

So there are 3 ways to handle this, the decision is up to you which to implement:
1. Struct level
```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

// NullPoint ...
type NullPoint struct {
	X     float64 `json:"lng"`
	Y     float64 `json:"lat"`
	Valid bool    `json:"valid"` // Valid is true if not NULL
}

func main() {
	validate := validator.New()
	validate.RegisterStructValidation(structLevelValidation, NullPoint{})

	var pt NullPoint
	errs := validate.Struct(pt)
	fmt.Println(errs)
}

func inMSK(point NullPoint) bool {
	return point.Valid
}

func structLevelValidation(sl validator.StructLevel) {
	pt := sl.Current().Interface().(NullPoint)
	if !inMSK(pt) {
		sl.ReportError(pt, "in_msk", "InMsk", "inmsk", "")
	}
}
```

2. Custom Type
```go
package main

import (
	"fmt"

	"reflect"

	"gopkg.in/go-playground/validator.v9"
)

// NullPoint ...
type NullPoint struct {
	X     float64 `json:"lng"`
	Y     float64 `json:"lat"`
	Valid bool    `json:"valid"` // Valid is true if not NULL
}

func main() {
	validate := validator.New()
	validate.RegisterValidation("in_msk", ValidationInMoscow)
	validate.RegisterCustomTypeFunc(PointValuer, NullPoint{})

	var pt NullPoint
	errs := validate.Var(pt, "in_msk")
	fmt.Println(errs)
}

func ValidationInMoscow(fl validator.FieldLevel) bool {
	return fl.Field().Bool()
}

func PointValuer(field reflect.Value) interface{} {
	// TODO: do validation here and return primitive type for "in_msk" validation
	point, ok := field.Interface().(NullPoint)
	if ok {
		return false
	}
	// TODO: check if in msk, return true or false
	return point.Valid
}
```

3. Use the NullPoint inner structure(assuming `Valid` == `in_msk`
```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

// NullPoint ...
type NullPoint struct {
	X     float64 `json:"lng"`
	Y     float64 `json:"lat"`
	Valid bool    `json:"valid" validate:"in_msk"` // Valid is true if not NULL
}

func main() {
	validate := validator.New()
	validate.RegisterValidation("in_msk", ValidationInMoscow)

	var pt NullPoint
	errs := validate.Struct(pt)
	fmt.Println(errs)
}

func ValidationInMoscow(fl validator.FieldLevel) bool {
	return fl.Field().Bool()
}
```


please let me know if this helps :)

**Comment by gebv** [comment]
Thanks @joeybloggs for detailed response
Right for me Custom Type. But I was in disarray PointValuer must return a simple type otherwise looped.

**Comment by tom-on-the-internet** [comment]
This thread helped me understand this function. Thank you!
