### ISSUE TITLE
Update failed for gopkg.in/go-playground/validator.v8: Cannot detect VCS

### ISSUE THREAD

**Issue by vbmade2000** [go-playground/validator#347]
### Package version eg. v8, v9: 
v8

### Issue, Question or Enhancement:
Issue

### Code sample, to showcase or reproduce:

>  glide get gopkg.in/go-playground/validator.v8
> [INFO]	Preparing to install 1 package.
> [INFO]	Attempting to get package gopkg.in/go-playground/validator.v8
> [INFO]	--> Gathering release information for gopkg.in/go-playground/validator.v8
> [INFO]	--> Adding gopkg.in/go-playground/validator.v8 to your configuration
> [INFO]	Downloading dependencies. Please wait...
> [INFO]	--> Fetching updates for github.com/gin-gonic/gin
> [INFO]	--> Fetching gopkg.in/go-playground/validator.v8
> [WARN]	Unable to checkout gopkg.in/go-playground/validator.v8
> [ERROR]	Update failed for gopkg.in/go-playground/validator.v8: Cannot detect VCS
> [ERROR]	Failed to checkout packages: Cannot detect VCS

**Comment by joeybloggs** [comment]
GitHub experienced a DDoS attack and was down for approx 10 minutes and is the most likely cause.

It is also likely that Gopkg.in experienced some issues around the same time.

It appears to be up and working now, if you could please try again to see if the problem is resolved.

**Comment by vbmade2000** [comment]
@joeybloggs Same issue again.

> [INFO]	--> Fetching gopkg.in/go-playground/validator.v8
> [WARN]	Unable to checkout gopkg.in/go-playground/validator.v8
> [ERROR]	Error looking for gopkg.in/go-playground/validator.v8: Cannot detect VCS
>

**Comment by joeybloggs** [comment]
Have you tried any of the following:
- attempted to `go get gopkg.in/go-playground/validator.v8` directly?
- can you git clone the https://github.com/go-playground/validator directly
- can you visit [this](http://gopkg.in/go-playground/validator.v8) page in your browser?, should look like:
![image](https://user-images.githubusercontent.com/8068371/36909397-af983d80-1df2-11e8-9587-dbe442b83a28.png)
- What OS are you running?
- what version of git are you using? pre 1.7.6(iirc) had problems with redirects which gopkg.in uses

It could be any number of factors such as an issue with glide, firewall, proxy issues, location in the world.

What I can say is that it's working from my location and so must be an external problem as I have done nothing with the v8 branch and is fully intact.

**Comment by vbmade2000** [comment]
> attempted to go get gopkg.in/go-playground/validator.v8 directly?
Yes. Getting following output.
package gopkg.in/go-playground/validator.v8: unrecognized import path "gopkg.in/go-playground/validator.v8" (https fetch: Get https://gopkg.in/go-playground/validator.v8?go-get=1: dial tcp: lookup gopkg.in on 127.0.0.53:53: read udp 127.0.0.1:42094->127.0.0.53:53: i/o timeout)

> can you git clone the https://github.com/go-playground/validator directly
Yes

> can you visit this page in your browser?, should look like:
Yes

> What OS are you running?
Ubuntu 17 64 bit

> what version of git are you using? pre 1.7.6(iirc) had problems with redirects which gopkg.in uses
git version 2.14.1

> Running Proxy
No

> Firewall
Disabled

May my system has some issue.

**Comment by joeybloggs** [comment]
>dial tcp: lookup gopkg.in on 127.0.0.53:53: read udp 127.0.0.1:42094->127.0.0.53:53: i/o timeout)

Those addresses seem a little strange... why is it trying to lookup on port 53? I'd look into that first.

**Comment by vbmade2000** [comment]
Make sense. I'll check that. Thanks.

**Comment by vbmade2000** [comment]
@joeybloggs Yes. It was issue with my system.
