### ISSUE TITLE
Validating (and rejecting based upon) additional map fields

### ISSUE THREAD

**Issue by frednomoon** [go-playground/validator#349]
### Package version eg. v8, v9: 

v9

### Question / Enhancement:

Apologies in advance if I have missed something or misunderstood some part of the pkg, but I have been not been able to find a way to validate whether a `map[string]interface{}` contains only the correct fields.

For example we may have the following struct,

```go
type Person struct {
	Age  int `json:"age"`
	Name struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"name"`
}
```

I receive a HTTP request with the following JSON body
```json
{
  "age": 123,
  "name": {
    "foo": "bar",
    "last": "smith"
  }
}
```

We could easily unmarshall this into a `Person` struct, then we could validate whether any required fields are missing. But any misspelt or otherwise erroneous fields will simply be omitted by `json.Unmarshall`. What I want is a function which can catch this for me.... 

I have written a solution for this, and I wondered if this would be something you would consider including in this package? Or if anyone had any suggestions for improvements (I imagine there will be many)

### Code sample, to showcase or reproduce:

Using this function, you pass in the map you would like to validate, `m`, and an instance of the struct you would like to validate it against, `s`.

```go
func validateMap(s interface{}, m map[string]interface{}) error {
	t := reflect.TypeOf(s)
	for k := range m {
		check := false
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			if tag == k {
				check = true
			}
		}
		if !check {
			return fmt.Errorf("Invalid field in request body: %s", k)
		}
	}
	return nil
}
```

Furthermore we can make the function recursive to validate against structs with nested structs...

```go
func validateMap(s interface{}, m map[string]interface{}) error {
	t := reflect.TypeOf(s)

	err := validateType(t, m)

	return err
}

func validateType(t reflect.Type, m map[string]interface{}) error {
	for k := range m {
		check := false
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			tag := f.Tag.Get("json")
			if tag == k {
				if f.Type.Kind() == reflect.Struct {
					err := validateType(f.Type, m[k].(map[string]interface{}))
					if err == nil {
						check = true
					} else {
						return err
					}
				} else {
					check = true
				}
			}
		}
		if !check {
			return fmt.Errorf("Invalid field in request body: %s", k)
		}
	}
	return nil
}
```

And in relation to my initial example, the function(s) would be used like so:

```go
bytes, _ := ioutil.ReadAll(r.Body)
var m map[string]interface{}
json.Unmarshal(bytes, &m)
p := Person{}

err = validateMap(p, m)
```
Then if we have an error, we know the request contains at least 1 incorrect field.

**Comment by joeybloggs** [comment]
Hey @frednomoon sorry about the delay I must admit this one slipped through the cracks.

I'll try and give it a look next week, it is an interesting use case

**Comment by blackstar257** [comment]
I just ran into this as well.

**Comment by joeybloggs** [comment]
@blackstar257 @frednomoon just to let you know I haven't forgotten, just really busy

off the top of my head I would say a custom validation is probably best and unmarshal into map then
`validate.Var(<map>, "custom validation")`

and if all is well then unmarshal into the struct and run validation against the struct, it's not ideal but a workaround for now.

**Comment by deankarn** [comment]
A long time ago I added the ability to pass data via `context.Context` which should handle the passing in of the map, the only thing that would be needed is to use a `Struct` validation rather than a field validation.

closing for now given it's age, feel free to revive if this does not allow the functionality necessary.
