### ISSUE TITLE
Integrated as default Validator for aah framework

### ISSUE THREAD

**Issue by jeevatkm** [go-playground/validator#353]
Hello @joeybloggs - I'm Jeeva, author of [aah framework](https://aahframework.org). I thought to inform you in `v0.10` release `validator` library have been integrated as default validator module by users recommendation go-aah/aah#132 and [documentation](https://docs.aahframework.org/validation.html).

Looking forward to your support if aah user ran into issues/question, please assist them. Thank you.

**Comment by joeybloggs** [comment]
Thanks for the heads up @jeevatkm will endeavour to help anyone out.

I saw in your examples about validating query params individually, if I could make a suggestion, I tend to unmarshall them into a struct and then validate which seems better than doing it one by one.

P.S. if your interested I also have a fully complete form parser and encoder https://github.com/go-playground/form which handles pretty much anything including full support for maps(I think it's probably the most complete form parsing lib out there) and also https://github.com/go-playground/mold for trimming strings and applying transformations and/or scrubbing PII data...

**Comment by jeevatkm** [comment]
@joeybloggs Thank you for your suggestions. Yes I agree your suggestion is good one.

Actually I given that choice to the aah users, aah has [Auto bind module](https://docs.aahframework.org/request-parameters-auto-bind.html) which maps any `Path`, `Form`, `Query` into struct fields and nested struct fields.

If user uses the struct to map values then aah applies the validation automatically and gives the errors to the user as part the request flow. 

It seems I have to update the documentation to explain clearly with your suggested approach.

Currently I do not know about `mold` library. I will surely have a look and study.

Thank you for building flexible validator library 👍
