### ISSUE TITLE
Strict sequence? is validation tag must be first?

### ISSUE THREAD

**Issue by gangstaJS** [go-playground/validator#354]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Question

### Code sample, to showcase or reproduce:

```go

// validation works good

data := struct {
	Password        string `validate:"required,alphanum,gte=6",json:"password"`
}{}

// validation does not work

data := struct {
	Password        string `json:"password",validate:"required,alphanum,gte=6"`
}{}

```

**Comment by joeybloggs** [comment]
Hey @gangstaJS 

No this should not be strictly ordered at all, it uses Tag.Get https://golang.org/pkg/reflect/#StructTag.Get here https://github.com/go-playground/validator/blob/v9/cache.go#L135 to retrieve the tag information.

I will check this morning to be sure though, would you be able to post some additional information about your OS and Go version and maybe an expanded version of the logic/example you gave to aid in debugging.

**Comment by gangstaJS** [comment]
Go version: go version go1.10 darwin/amd64. MacOS High Sierra 10.13.3

```go
func ResetPassword(writer http.ResponseWriter, request *http.Request) {
	res := Payload{}
	validate := validator.New()

	data := struct {
		UUID            string `validate:"required,uuid",json:"uuid"`
		Password        string `validate:"required,alphanum,gte=6",json:"password"`
		ConfirmPassword string `validate:"eqfield=ConfirmPassword",json:"confirmPassword"`
	}{}

	err := json.NewDecoder(request.Body).Decode(&data)

	if err != nil {
		res.Result = err.Error()

		SetPayloadErr(writer, res)
		return
	}

	err = validate.Struct(data)

	if err != nil {
		res.Result = err.Error()
		SetPayloadErr(writer, res)
		return
	}

	if !db.ResetPassword(data.UUID, data.Password) {
		res.Result = "Reset link has expired or was not created"

		SetPayloadErr(writer, res)
		return
	}

	res.Result = "New password was saved"

	SetPayloadOk(writer, res)
}
```

**Comment by joeybloggs** [comment]
@gangstaJS finally found time to look at this, I can confirm that validator is working correctly, it's actually how you defined your struct tags.

You have a `,` comma in-between the separate tags `validate` and `json` and so the tag parse doesn't look past the first tag defined in the second case.

eg. `json:"password",validate:"required,alphanum,gte=6"`

should be `json:"password" validate:"required,alphanum,gte=6"`
no comma between tags.   ☝️

**Comment by gangstaJS** [comment]
Thanks! It is strangely cuz json annotation still works when I am doing  `validate:"required,alphanum,gte=6",json:"password"`

**Comment by joeybloggs** [comment]
They must parse the tag differently for some reason.
