### ISSUE TITLE
Email - Hostname is not validated correctly

### ISSUE THREAD

**Issue by danielpoe** [go-playground/validator#359]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
According to http://www.ietf.org/rfc/rfc1123.txt
Hostnames are limited  to letters-digits-hyphen

Currently underscores are allowed in the validator 

### Code sample, to showcase or reproduce:

```go
Test struct {
Email            string `form:"email" validate:"required,email" conform:"email"`
}

Validation of "test@test_test.org" suceeds but test_test.org is not a valid hostname
```

**Comment by joeybloggs** [comment]
@danielpoe thanks for reporting, I will try and get to this, but might take a little bit, PR's are welcome if you would like it sooner :)

**Comment by jadhub** [comment]
I supplied a PR for this: https://github.com/go-playground/validator/pull/362
