### ISSUE TITLE
Extend unique tag to map values.

### ISSUE THREAD

**Issue by jservice-rvbd** [go-playground/validator#360]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Enhancement:  Can the unique tag be extended to also validate map values?  Or, alternatively, can a tag such as uniquevalues be added?

### Code sample, to showcase or reproduce:

```go
type VolumeMapper struct {
    Volumes map[string]string `validate:"unique"`
}
```

**Comment by joeybloggs** [comment]
@jservice-rvbd merged your PR in v9.16.0
