### ISSUE TITLE
Please provide a RegisterFiledNameFunc for translate 

### ISSUE THREAD

**Issue by syssam** [go-playground/validator#365]
RegisterTagNameFunc is using for json key and fieldName,
For example, I would like the return is
```
"error":{
"email": "Email is a required field",
"first_name": "First Name is a required field",
"last_name": "Last Name is a required field"
}
```

But now is return 
```
"error":{
"Namespace.email": "email is a required field",
"Namespace.first_name": "first_name is a required field",
"Namespace.last_name": "last_name is a required field"
}
```

So, please add RegisterFiledNameFunc for diff filed name and json key name.
On the other hand, if I have define the json name, it should use the json name, and not Namespace + json name, please improve it

**Comment by joeybloggs** [comment]
Hey @syssam I think there's maybe some confusion about how this all works, the way you are seeing this is just the default error message this library uses see [here](https://github.com/go-playground/validator/blob/v9/errors.go#L251) and [here](https://github.com/go-playground/validator/blob/v9/errors.go#L43)

You are able to type cast to those error types and format any error message you wish, this also seems very related to #364  which I believe would also do what you're looking for.

please let me know if this clarifies things a bit.

**Comment by syssam** [comment]
Hi @joeybloggs , Yes, I am really confused.
I want to do a translations for error message, but I don't know how to do it.So, I open the issue #364 , then I read sample, I find out the RegisterTagNameFunc , I think this function is my need.

Would you provide more clearly sample to using validator and locale, like the result
"error":{
"email": "Email is a required field",
"first_name": "First Name is a required field",
"last_name": "Last Name is a required field"
}

**Comment by joeybloggs** [comment]
Here is a quick example, have to start my day, will try to make a better full example later, but it's basically what was done in #364  in combination with this: (which can easily be hidden behind a reusable function. )

```go
// returns ValidationErrors ( []FieldError )
	err := validate.Struct(user)
	if err != nil {
		for _, err := range err.(validator.ValidationErrors) {

                        // from here you can create your own error messages in whatever language you wish using the below mothods and the translate method to create the structure you want.
			fmt.Println(err.Namespace())
			fmt.Println(err.Field())
			fmt.Println(err.StructNamespace()) // can differ when a custom TagNameFunc is registered or
			fmt.Println(err.StructField())     // by passing alt name to ReportError like below
			fmt.Println(err.Tag())
			fmt.Println(err.ActualTag())
			fmt.Println(err.Kind())
			fmt.Println(err.Type())
			fmt.Println(err.Value())
			fmt.Println(err.Param())
		}
return
```

**Comment by syssam** [comment]
um, I using this method before,
like https://github.com/syssam/go-playground-sample/blob/master/main.go

**Comment by joeybloggs** [comment]
Hey @syssam sorry for my late reply, did you end up getting this working?

**Comment by syssam** [comment]
@joeybloggs Yes, I'm using https://github.com/syssam/go-playground-sample/blob/master/main.go
It seems not perfect.But it's fine

**Comment by joeybloggs** [comment]
Thank you for your feedback, I'm recording it all to make the next version better :)

**Comment by syssam** [comment]
Great, keep going.
expected
