### ISSUE TITLE
More documentation on register translators

### ISSUE THREAD

**Issue by ryan-ju** [go-playground/validator#366]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
The translator registration part isn't clear on how it works, and the example is not very helpful (https://github.com/go-playground/validator/blob/v9/_examples/translations/main.go)

In particular, the confusing part is this:

https://github.com/go-playground/validator/blob/v9/_examples/translations/main.go#L48
```go
en_translations.RegisterDefaultTranslations(validate, trans)
```

`trans` is registered with the `validate`.  But later in the code, when formatting the validation errors, it requires passing in the `trans` again!  Why is it passed in again?
https://github.com/go-playground/validator/blob/v9/_examples/translations/main.go#L79
```go
fmt.Println(e.Translate(trans))
```

**Comment by joeybloggs** [comment]
@ryan-ju I will try and look into adding a better example and documentation, for now here is a brief overview and how this is set up for i18n:

It all starts with the [locales](https://github.com/go-playground/locales) which provides the various languages translation and formatting rules.

I then have another package [universal-translator](https://github.com/go-playground/universal-translator) which you can register locales with, which provides a way to coordinate locales and register actual text translations.

Now when registering a translation in validator it is providing a function that actually registers the text translation for the validation tag (using [universal-translator](https://github.com/go-playground/universal-translator)) and another function that will actually perform the translation which is then saved within `validator`.

Now when translating a `FieldError` you have to pass in the translator, which will lookup the registered translator and then lookup/translate based on the validation tag that was registered earlier.

So in short validator's translations were designed for i18n usage and is setup to use/handle multiple locales; a good example would be a web application where a user makes a request to your site, and:
- you determine the locale via the `Accept-Languages` http header and use [universal-translator](https://github.com/go-playground/universal-translator) to get the `Translator` for the rest of your application
- when validating a `POST` request using validator if you encounter errors, you can translate by passing in the `Translator` determined from the http header, which could be one of many locales.

I hope this clarifies why it's done this way, there are a few things that even I would change, hindesight being 20/20, like having to provide the registering of the text translation; it was only done that way to not lose track of where your translation is registered vs translated, but has proven to be confusing.

**Comment by joeybloggs** [comment]
@syssam as I stated this is designed for i18n and I don't intend to provide a way for validator to be locked into a single locale for translations; I believe it's that callers job to make that determination.
