### ISSUE TITLE
Custom validation tag is ignored when validating a field that is of type struct

### ISSUE THREAD

**Issue by codasols** [go-playground/validator#367]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

The custom validation tag appears to have no impact when it is used against a field that is of type struct. If the tag is not registered, the validator library panics as expected, however if the tag is registered and deliberately set to return false, I would expect validation to fail.

However it does not.

Is this intended behaviour? Can field validation not be performed in this way? If I was to use my custom tag against a standard system type, such as a string, the validation fails as expected.

Apologies if this is covered in the documentation somewhere.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"time"

	validator "gopkg.in/go-playground/validator.v9"
)

// We want to validate the ValidUntil is equal to or after ValidFrom

type Record struct {
	ValidFrom  ExtendedDate `validate:"required"`
	ValidUntil ExtendedDate `validate:"required,gteEpoch=ValidFrom"`
}

type ExtendedDate struct {
	Epoch   int64     `validate:"required"`
	Iso6801 time.Time `validate:"required"`
}

var validate *validator.Validate

func main() {

	record := Record{
		ValidFrom: ExtendedDate{
			Epoch:   1,
			Iso6801: time.Now(),
		},
		ValidUntil: ExtendedDate{
			Epoch:   1,
			Iso6801: time.Now().AddDate(0, 0, -1),
		},
	}

	validate = validator.New()
	validate.RegisterValidation("gteEpoch", gteEpoch)

	err := validate.Struct(record)

	// This should fail, but it does not?
	if err != nil {
		fmt.Printf("%v\n", err.Error())
	}
}

func gteEpoch(fl validator.FieldLevel) bool {
	// Perform required validation checks here...

	// Deliberately fail here for this example
	return false
}

```

**Comment by joeybloggs** [comment]
Hey @ptcoda sorry for the delay, I was looking deep into the code and to make this work properly will definitely be a breaking change, I did not anticipate this specific use case; I will add this to the list of v10 improvements :)

 however, not to fret, all is not lost, this is actually a perfect use case for [Struct Level](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go) validation; I would add a validation for your `Record` struct.

Please let me know if this will help :)

**Comment by alecthomas** [comment]
I just hit the same problem, but I don't think this can be solved by Struct Level validation as far as I can tell. The problem is that the validator (in this case `gteEpoch=ValidFrom`) is set on the parent field, but struct level validators don't have access to this. Am I mistaken here?

PS. Great library, thanks!

**Comment by xfoxawy** [comment]
@deankarn Hety Dean, this issue had been stale for while, I would like to take a stab at it cuz Im actually facing this problenm.
if you can point me to where to dig that would be great
