### ISSUE TITLE
Pointer to string can not be validated with `max=10`

### ISSUE THREAD

**Issue by vpikulik** [go-playground/validator#369]
### Package version eg. v8, v9: 
V8 and V9

### Issue, Question or Enhancement:

Struct has a field with  type `*string`. When the value is `nil`, validation (max=10) returns error:
`Key: 'User.FirstName' Error:Field validation for 'FirstName' failed on the 'max' tag` 

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type User struct {
	FirstName *string `validate:"max=10"`
}

func main() {

	validate := validator.New()

	user := &User{
		FirstName: nil,
	}

	err := validate.Struct(user)

	if err != nil {
		fmt.Println("Error:", err)
	} else {
		fmt.Println("Well done!")
	}
}
```

**Comment by joeybloggs** [comment]
@vpikulik could you explain what you expected to happen?

I think, depending on your answer, you will be looking to use the `required` or `omitemtpy` tag preceding the max.

**Comment by vpikulik** [comment]
I expected, that my example should pass validation. Tag `omitempty` helps. But only if it stays as the first tag. Before we tested this with this tag at the end ((. The problem was solved, thanks!
