### ISSUE TITLE
Spaces allowed in struct tags?  (Bug?  Intended?)

### ISSUE THREAD

**Issue by czbaker** [go-playground/validator#372]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
When using this package to validate a struct in my project, it seems that if you have a space in between `validate:` and `"required"`, the tags aren't seen by the package and validations don't happen?

I was able to create a struct with all missing/empty fields and it passed validation if the space was present in the struct tag, otherwise it worked as intended

### Code sample, to showcase or reproduce:

This struct definition DOES work (tags)
```go
type User struct {
	Username string `validate:"required"`
	Password string `validate:"required"`
	Email    string `validate:"required"`
}
```

This one doesn't work:
```go
type User struct {
	Username string `validate: "required"`
	Password string `validate: "required"`
	Email    string `validate: "required"`
}
```

In both cases, I used the following to test validation:
```go
func (u User) Validate() error {
	validate = validator.New()
	err := validate.Struct(u)
	if err != nil {
		return err
	}
	return nil
}

u := &User {
        Username: ""    
}

err := u.Validate()
```
Is this behavior intended?  I just wondered, encountered this while working on a project and wasn't sure, so I thought I'd ask.

**Comment by czbaker** [comment]
Upon further research and asking around on Discord, apparently this is just how things work, as stated in the `reflect` package.   Whitespace is apparently important, I didn't know that.

Feel free to close this, I just didn't read the docs all the way, my bad!

**Comment by aprilnops** [comment]
confuse too
