### ISSUE TITLE
Second call to validate.Struct() after calling validate.SetTagName() fails to assert new validations.

### ISSUE THREAD

**Issue by beiriannydd** [go-playground/validator#378]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

This could be solved (maybe) with an enhancement request:
Please allow the context from any of the Ctx functions to be passed to the TagNameFunction so that it can factor into the choice of validator.  Since the non-Context functions simply call the validator with a default Background() context this should be compatible (if you use a separate method to add a context aware TagNameFunction and have the old method assign a wrapper anonymous function with context which simply doesn't pass the context.)

Requirement:
I want to be able to use different validations based on the schema version specified in the structure.
In my structure the value is held in "ManifestVersion".  I have custom validations added to validate.
I want to be able to validate the structure against "validate" but then validate the same structure against "validate2.1" if the version is 2.1

I am calling validator.New() for each iteration, so the TagName configured for the object under test should be consistent within the test.  It is not.  The only conclusion I can draw is that the cache is what is returning the validated structure against the original tags and therefore for each call to validate.Struct()

My attempt to use the tagnamefunction failed because of using a global to store that version which is absolutely not thread safe.

### Code sample, to showcase or reproduce:

```go
    validate := validator.New()
    // First Check the version
    if err = validate.StructPartial(manifest, "ManifestVersion"); err != nil {
        return nil, errors.New("validate: invalid manifest_version.")
    }
    // Now the version is valid, trim to Major and Minor only.
    mfversion := manifestVersion(manifest.ManifestVersion)
    // Validate the generic structure
    if err = validate.Struct(manifest); err != nil {
        return nil, errors.New("validate: basic validation failed: " + err.Error())
    }
    // Set validators to be version specific
    validate.SetTagName("validate" + mfversion)
    // Validate version specific tags
    if err = validate.Struct(manifest); err != nil {
        return nil, errors.New("validate: version validation failed: " + err.Error())
    }
    // Validation is completed.
    return manifest, nil

```

**Comment by beiriannydd** [comment]
This isn't working because of the parallel execution of my tests.  I need to create two different validations to make this work which are statically a particular tag name.  I cannot use a TagName function because it won't accept a context, which I could use to persist the manifest version under test, or allow me to see all the fields in the structure.

**Comment by joeybloggs** [comment]
Hey @lucasmundim I think the underlying reason this isn't working for you is because after the first call the validate.Struct it caches the parsed validation functions and uses the struct type as the key and so the second call would use the first cached values.

The library wasn't meant to change that value at runtime and will cause races, as you mentioned you could have 2 validations or use Context to pass to a single, however there is one more possibility, you could create 2 separate validator instances that are set to use different tags names and use each as needed.

Let me know if that helps :)

**Comment by beiriannydd** [comment]
Thanks, I think I came to the same conclusion.  I actually think the TagNameFunctionCtx could be the best possible solution, since it would allow me to just execute the validation once per instance.
Will Context be included in the cache key too?

**Comment by joeybloggs** [comment]
That I'll have to think about, initial thoughts are no because that logic is abstracted away from the end user, but there may be a better way if I can think on it a bit.

**Comment by beiriannydd** [comment]
So, I tried this:
```go
    ctx := context.Background()
    validate := validator.New()
    // add our custom validations
    validate.RegisterTagNameFunc(func(field reflect.StructField) string {
            // wrap our current context
            return manifestSchemaVersionTagCtx(field, ctx)
    })
…
    // First Check the version
    if err = validate.StructPartialCtx(ctx, manifest, "ManifestVersion"); err != nil {
        return nil, errors.New("validate: invalid manifest_version.")
    }
    // Now the version is valid, trim to Major and Minor only.
    mfversion := manifestVersion(manifest.ManifestVersion)
    ctx = context.WithValue(ctx, manifestSchemaVersionKey, mfversion)
    // Validate the structure
    if err = validate.StructCtx(ctx, manifest); err != nil {
        return nil, errors.New("validate: basic validation failed: " + err.Error())
    }
```
So now there is only one call to StructCtx per validation, there is no global (each thread will add its own unique context based tag function), the debug code in the tag function tells me that the tag is consistent per validate instance but the test still fails.  I think if you can add uniqueness by tag to the cache that would be ideal.

**Comment by joeybloggs** [comment]
@beiriannydd Yes the Tag Name function is used in the caching layer and used only once pre-validation.

I'll try to think of the best way to implement this, I'm wary about adding separate caches per tags for performance reasons.

in the meantime though I'd recommend using 2 different validator instances one for each different tag name.

Alternatively, you could probably achieve what you're looking for using a [StructLevel validation](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go); usually, these are used for more complex validations.

**Comment by beiriannydd** [comment]
```go
func getValidator(tagname string) *validator.Validate {
	// create a new validator
	validate := validator.New()
	validate.RegisterValidation("manifestversion", validManifestVersion)
	validate.RegisterValidation("appversion", validAppVersion)
	validate.RegisterValidation("thornversion", validThornVersion)
	validate.RegisterValidation("hyphenunderscore", hyphenUnderscore)
	validate.SetTagName(tagname)
	return validate
}

func (manifest *Manifest) Validate() (bool,error) {
	validate := getValidator("validate")
	// First Check the version
	if err := validate.StructPartial(manifest, "ManifestVersion"); err != nil {
		return false, errors.New("validate: invalid manifest_version.")
	}
	// Now the version is valid, trim to Major and Minor only.
	// Validate the structure
	if err := validate.Struct(manifest); err != nil {
		return false, errors.New("validate: basic validation failed: " + err.Error())
	}
	// Validate version specific data
	mfversion := manifestVersion(manifest.ManifestVersion)
	validate = getValidator("validate"+mfversion)
	// Validate the structure
	if err := validate.Struct(manifest); err != nil {
		return false, errors.New("validate: basic validation failed: " + err.Error())
	}
	return true, nil
}
```
This code works, thank you.  I will tell you that when I used the tagname function, the initial call to StructPartial requested the tag for ManifestVersion and the two sub structures with no version number.  Then subsequently it was called for each field with a specific version, this is why I expected the code to work that way (without dissecting validator).  So you may be able to make some performance optimizations by dropping a tag name request that you're not going to use anyway :)
