### ISSUE TITLE
How to validate an "End" time field is no more than 24 hours after a "Start" time field?

### ISSUE THREAD

**Issue by veqryn** [go-playground/validator#383]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question/Enhancement

### Code sample, to showcase or reproduce:
Given this:
```go
type pixelQueryParams struct {
	Start time.Time `json:"start,omitempty" form:"start,omitempty" validate:"required"` // Required, RFC3339
	End time.Time `json:"end,omitempty" form:"end,omitempty" validate:"required,gtfield=Start"` // Required, RFC3339
}
```
I would like to additionally validate that the End time is no more than 24 hours after the Start time.

This could be made more generic to apply to both numbers and times, allowing you to define a valid range of values when comparing two fields.
`<add/sub>=<other-struct-field> <inclusive-lower-end> <exclusive-higher-end>`
Such as: `sub=Start 1 86400000000001`
Where `sub` is the tag name, `1` is 1 nanosecond, and `86400000000001` is 1 day and 1 nanosecond.
Nanoseconds are because `myTime.Sub(otherTime) = time.Duration` which is an int64 representing nanoseconds.
```go
type NoMoreThan24Hours struct {
	Start time.Time `validate:"required"`
	End time.Time `validate:"required,sub=Start 1 86400000000001"`
}
```

A parameter could be left blank (or maybe have a `*`?) to signify an open ended range, such as:
```go
type AtLeast10 struct {
	A int
	B int `validate:"add=A 10 *"`
}
```
The above would make sure that A plus B was at least 10.

**Comment by veqryn** [comment]
No problem

**Comment by sans-clue** [comment]
Hello, 

Sorry for drudging up an old thread but I wanted to know how one would go about writing the custom validation for this. My problem is similar except that I need to find out that a field is no more than 10 years old or something.

```go
type user struct {
    name string
    bday time.Time `validate:"isten"
}

func isTen(fl FieldLevel) bool {
     // fl.Field().String()
}
```

This just gives me an output of `<time.Time Value>`. I'm still learning Go but I can't seem to find any helpful information about this. Am I just missing something super simple?

**Comment by deankarn** [comment]
@sans-clue please see the struct level validation example [here](https://github.com/go-playground/validator/blob/8f604265e0ead955151bc460ee9b123c029d37d1/_examples/struct-level/main.go#L112) once you have the top level struct it's pretty straight forward.
