### ISSUE TITLE
Return reflect.StructField in FieldError

### ISSUE THREAD

**Issue by veqryn** [go-playground/validator#384]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question/Enhancement

I am using your `form` library to first decode url query values / form values into a struct, then I am using this library to validate that struct. Pretty standard application I think.

I would like to be able to tell the clients which parameter they have messed up when it fails validation.

Unfortunately, FieldError only tell me about the struct's field name in golang, not the actual form parameter key.
For example:
```go
type queryParams struct {
	FooIDBar  string `form:"foo_id_bar,omitempty" validate:"required"`
}
```
If this struct fails validation, the information I have from the FieldError is that `FooIDBar` failed `required` tag.

I would actually like to know that it was `foo_id_bar` that failed `required`.

If you added `reflect.StructField` or alternatively all of the struct field's tags as `reflect.StructTag`, then I would be able to pull the form tag value out and send a better error message to the client.

As of right now, I don't want to tell them `FooIDBar` is required, because they might send a new request literally using `FooIDBar` instead of `foo_id_bar`.

thx!

**Comment by veqryn** [comment]
Thx!

**Comment by lansana** [comment]
This is super old, but I have my own solution for knowing that:

```go
package validator

import (
	"errors"
	"reflect"
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

// Examples package usage:
//
// type Account struct {
//     Name string `validate:"required,max=5"`
// }
//
// func (a *Account) Validate() map[string]map[string]string
//     return map[string]map[string]string{
//         "Name": map[string]string{
//             "required": "Name is required",
//             "max":        "Name cannot exceed 5 characters."
//         }
//     }
// }
//
// messages, err := validator.Validate(&Account{Name: "foobarbaz"})
// if err != nil {
//     panic(err)
// }
// if len(messages) > 0 {
//     fmt.Println(messages) // []string{"Name cannot exceed 5 characters."}
// }

var (
	v = validator.New()
)

// Validatable is an interface representing objects that can be validated.
type Validatable interface {
	Validate() map[string]map[string]string
}

// ValidationMessage is a string type alias that represents validation
// a validation message.
type ValidationMessage string

func (v ValidationMessage) String() string {
	return string(v)
}

// Validate will validate a Validatable object and return a slice of
// validation messages as well as an error if any is encountered.
func Validate(obj Validatable) ([]ValidationMessage, error) {
	return validate(obj)
}

func validate(obj Validatable) ([]ValidationMessage, error) {
	messages := make([]ValidationMessage, 0)
	err := v.Struct(obj)

	if _, ok := err.(*validator.InvalidValidationError); ok {
		return []ValidationMessage{}, errors.New(err.Error())
	} else if _, ok := err.(validator.ValidationErrors); ok {
		messageMap := obj.Validate()

		for _, err := range err.(validator.ValidationErrors) {
			f := err.StructField()
			t := err.Tag()

			if _, ok := messageMap[f]; ok {
				if _, ok := messageMap[f][t]; ok {
					messages = append(messages, ValidationMessage(messageMap[f][t]))
				}
			}
		}
	}

	return messages, nil
}
```

By looping through the validation errors, I can map a field to a validation tag and vice versa. I use that information here to map to friendly error messages.

**Comment by sleagon** [comment]
> Hey again @veqryn ya I agree and it has been requested a couple of times it is something I will be considering for the next release.
> 
> If anyone wants to take a crack at it before then, I would consider adding it to this version but it will take a lot of thought because of all the indirection that occurs before getting to the error itself.

Is there any plan to add this feature to v8/v9? We want to add a middleware to translate validate failure message to user friendly message, the default message generated by validator like `SomeStruct.SomeField is required` is strange to users. We can definitely register a specific translator for every request struct, but it to complex for our developers. We want to add a simple i18n key tag and get the tag when parsing validator errors, then translate the error, we want some error message like `Phone number is required`.

**Comment by sleagon** [comment]
@deankarn

**Comment by deankarn** [comment]
The error can be parse after the error occurs or the built in translations can be used, thos are the only two options ATM.

closing this due to it's age, dong a little cleanup, feel free to reopen.
