### ISSUE TITLE
Validate that two or more values are not assigned at the same time.

### ISSUE THREAD

**Issue by droslean** [go-playground/validator#390]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question:
Is there any way to specify that I don't want 2 or more values to be assigned at the same time?

### Code sample, to showcase or reproduce:

```go
type TestStruct struct {
	Name     string `validate:"required"`
	Nickname string `validate:"required"`
}
```
In this example: Is it possible to validate that only 1 of those 2 fields are assigned?

**Maybe something like:**

```go
type TestStruct struct {
	Name     string `validate:"required,nocoexitst=Nickname"`
	Nickname string `validate:"required,nocoexitst=Name""`
}
```
or If this example above is more complicated, maybe should be able to specify this when we construct the validator. 
```go
validate = validator.New()
validate.RegisterRestrictions("coexists", TestStruct.Name, TestStruct.Nickname)
```

**Comment by joeybloggs** [comment]
Hey @droslean 

There are two options:

1. You can create and register a custom validation function that does what you want, see [here](https://github.com/go-playground/validator/blob/v9/_examples/custom-validation/main.go#L20) for the example. `FieldLevel` has access to the current and top level structs and so you can create a validation that looks at both fields.

2. You can use the StructLevel validation like the example [here](https://github.com/go-playground/validator/blob/v9/_examples/struct-level/main.go#L37), which sounds more like what you're looking for. When validation use cases get complicated enough it usually warrants this type which will allow you to validate however you wish.

Please let me know if that helps :)

**Comment by droslean** [comment]
@joeybloggs It seems that this solves my problem.
