### ISSUE TITLE
Support json in structs?

### ISSUE THREAD

**Issue by droslean** [go-playground/validator#391]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question:
Is there any way to change the error message to show the JSON field and not the struct field name?

### Code sample, to showcase or reproduce:

```go
type TestStruct struct {
	Name     string `json:"name" validate:"required"`
	Lastname string `json:"lastname" validate:"required"`
	Address  string `json:"address" validate:"required"`
	Phone    string `json:"phone" validate:"required"`
}
```
Instead of ``` Key: 'TestStruct.Address' Error:Field validation for 'Address' failed on the 'required' tag ```
I want to show to user 
```
Error in validation for 'address' failed on the 'required' tag
```

**Comment by joeybloggs** [comment]
Yes @droslean, as in the docs [RegisterTagNameFunc](https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.RegisterTagNameFunc)

[here](https://github.com/go-playground/validator/blob/v9/validator_test.go#L388) is an example in the tests.

**Comment by droslean** [comment]
@joeybloggs Thanks a lot. This is what I was looking for.
