### ISSUE TITLE
Support nullable for custom type

### ISSUE THREAD

**Issue by canhlinh** [go-playground/validator#392]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
At this line

https://github.com/go-playground/validator/blob/e69e9a28bb62b977fdc58d051f1bb477b7cbe486/util.go#L51

I saw that the lib doesn't support nullable for custom type. Then I can not  validate on nullable field sql.NullString

Please support nullable for the custom type as default.

**Comment by joeybloggs** [comment]
Hey @canhlinh 

It's hard to tell exactly what you're trying to accomplish without an example, but I'll try my best.

The line you reference is past [this](https://github.com/go-playground/validator/blob/e69e9a28bb62b977fdc58d051f1bb477b7cbe486/util.go#L47) line which brings you back to the top of the switch check and so if you return a nullable type from the [custom type](https://github.com/go-playground/validator/blob/e69e9a28bb62b977fdc58d051f1bb477b7cbe486/util.go#L45) function, is will return true as nullable.

**Comment by canhlinh** [comment]
@joeybloggs 

Thank you. 

Example: 
I want to validate with `sql.NullString`.
I leave the value of `sql.NullString` is empty. I don't want the column to be validated.

But the validator still validate the column.

I go to the this line https://github.com/go-playground/validator/blob/e69e9a28bb62b977fdc58d051f1bb477b7cbe486/util.go#L51
change it to 
```
return current, current.Kind(), true
```
It works.

**Comment by joeybloggs** [comment]
@canhlinh would it be possible to see the structure you're trying to validate and any custom type funcs registered? 

Before having to make a breaking change I'd like to explore the options, I think this can be used in conjunction with the omitempty tag, just need and example use case.

**Comment by canhlinh** [comment]
@joeybloggs You are right. Just use `omitempty` tag instead. Thank you

**Comment by joeybloggs** [comment]
@canhlinh glad that worked for you:)

**Comment by canhlinh** [comment]
@joeybloggs One star for doing a very good job.
