### ISSUE TITLE
validate:required is not validating for default value

### ISSUE THREAD

**Issue by payuprashantg** [go-playground/validator#397]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
**validate:required** is not validating for default value. i.e. in below example Name in employee struct in set to "" (Default Value).

Here I am expecting the result as validation error for Name field

### Code sample, to showcase or reproduce:

```
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
	"time"
)

type Employee struct {
	Name string `validate:required`
	Age int32	`validate:required`
	DOB	time.Time	`validate:required`
	Address struct{}
}

var validate *validator.Validate

func main()  {

	var emp Employee
	validate = validator.New()

	err := validate.Struct(emp)
	if err != nil {
		fmt.Println("Error Occured", err)
	} else {
		fmt.Println("Validation Successful")
	}


}
```

**Comment by joeybloggs** [comment]
Hey @payuprashantg it looks like your tag syntax is incorrect and missing the double quotes eg.
```go
`validate:"required"` vs `validate:required`
```

please let me know if that solves it :)

**Comment by payuprashantg** [comment]
Thanks @joeybloggs ,
Its working fine now.
