### ISSUE TITLE
Validation for `email` is always required

### ISSUE THREAD

**Issue by loeffel-io** [go-playground/validator#401]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Validation for `email` is **always** required

### Code sample, to showcase or reproduce:

```go
Email  *string `json:"email" validate:"email" structs:"email,omitempty"`
```

Returns `Key: 'accountUpdate.Email' Error:Field validation for 'Email' failed on the 'email' tag`. This shouldn't happen on nil if there is no `required` tag.

**Comment by joeybloggs** [comment]
Hey @loeffel-io I think you are looking for the omitempty tag to be used with the email tag if a blank or nil value is ok in your application.

To address your comment about blank or nil passing without a required tag the built in validations won’t pass in these cases and need to be told that blank is ok; I would say that it’s working as expected as you asked it to ensure the field was a valid email and blank is not.

**Comment by loeffel-io** [comment]
Hey @joeybloggs, thanks for your response. The `omitempty` tag is not working in combination with the `email` tag. 

```golang
Email  *string `json:"email" validate:"email,omitempty" structs:"email,omitempty"
```

**Comment by loeffel-io** [comment]
```golang
package main

import (
	"log"
)

type info struct {
	Email *string `json:"email" validate:"email,omitempty" structs:"email,omitempty"`
}

func main() {
	info := &info{}
	validate := validator.New()
	err := validate.Struct(info)

	if err != nil {
		log.Fatal(err.Error())
	}

	log.Printf("Success")
}
```

**Comment by joeybloggs** [comment]
@loeffel-io you must reverse the omitempty and email tags, omitempty skips the rest of the validations and so having it last causes the email validation to still occur.

Please refer to the godocs linked to the README, they are pretty thorough and provide example usage.

**Comment by loeffel-io** [comment]
> you must reverse the omitempty and email tags

🙈  thank you very much!

**Comment by bnegrao** [comment]
> @loeffel-io you must reverse the omitempty and email tags, omitempty skips the rest of the validations and so having it last causes the email validation to still occur.
> 
> Please refer to the godocs linked to the README, they are pretty thorough and provide example usage.

I would love to see that rule about ordering and precedence on the Omitempty tag documentation. Also, if you could provide an example that would be awesome.

**Comment by deankarn** [comment]
@bnegrao @loeffel-io I'd love to add examples, but I can't find the time lately.

If anyone can help with PR's it would be greatly appreciated. I have an issue for more documentation and examples that anyone can pitch in with :) https://github.com/go-playground/validator/issues/509

**Comment by apyong** [comment]
Hello, Is there a way to omit certain field on validation on update? eg: password.
Like I would require it upon creation of the user but not on update.
