### ISSUE TITLE
Incorrect UUID validation regex

### ISSUE THREAD

**Issue by alexbilbie** [go-playground/validator#402]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

The regular expression validation for UUIDs only allows lowercase characters.

[RFC 4122](http://www.ietf.org/rfc/rfc4122.txt) allows uppercase characters for input of functions but requires lowercase characters on output:

>  Each field is treated as an integer and has its value printed as a
  zero-filled hexadecimal digit string with the most significant
  digit first.  The hexadecimal values "a" through "f" are output as
  lower case characters and are case insensitive on input.

In addition the acceptable hex digits are (according to section 3 of the RFC):

```
hexDigit =
    "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9" /
    "a" / "b" / "c" / "d" / "e" / "f" /
    "A" / "B" / "C" / "D" / "E" / "F"
```

### Code sample, to showcase or reproduce:

```go
v := validator.New()
err := v.Var("479992BD-5A1E-43AA-9268-597F581380F0", "uuid4") // err will not be nil
```

**Comment by joeybloggs** [comment]
As asked in the PR https://github.com/go-playground/validator/pull/403#issuecomment-432718271

**Comment by alexbilbie** [comment]
Closing as it's fixed
