### ISSUE TITLE
Enhance the Chinese translation

### ISSUE THREAD

**Issue by kanozec** [go-playground/validator#405]
### Package version eg. v8, v9: 

v9

###  Enhancement:

Could I add the zh-tw translation to the translations package??
Because there is only zh translation for Chinese words.
There are such different between the zh and zh-tw

Actually the zh translation in the package is zh-cn, it's for China area (Simplified Chines).
The zh-tw is for Taiwan area (Traditional Chinese).

I can make a pull request for the zh-tw translation. Thank you.

**Comment by joeybloggs** [comment]
@kanozec yes by all means please add, the underlying locales package should support that :)
