### ISSUE TITLE
Is there a way for not validating a struct in another struct

### ISSUE THREAD

**Issue by AbajurAdam** [go-playground/validator#407]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Hello, I have a struct named employee. Employee contains a struct named User. When I try to add Employee, I get an error because it looks at the tags in the validate User to see that there are no places marked as required. I can't use omitempty tag because this struct being used with another pages and this columns cannot be null.
But in my case, user, user, username, password and roleid parts should not be sent with employee.

Is there a way to accept another struct in a struct without validating it?

### Code sample, to showcase or reproduce:

```go
type Employee struct {
	gorm.Model   `structs:",flatten"`
	CompanyID    uint
	Name         string `gorm:"not null" validate:"required"`
	Surname      string `gorm:"not null" validate:"required"`
	Phone1       string `gorm:"not null;size:13" validate:"required,phone,len=13"`
	Phone2       string `gorm:"not null;size:13" validate:"phone,len=13"`
	Email        string `gorm:"unique_index;not null;size:50" validate:"required,email,min=6,max=50"`
	User         *user.User
}

type User struct {
	gorm.Model `structs:",flatten"`
	Username   string `sql:"index" gorm:"unique_index;not null;size:50" validate:"required,email,min=6,max=50"`
	Password   string `gorm:"size:64;not null;" validate:"required,len=64"`
	IsActive   bool
	FailCount  int
	LastLogin  *time.Time
	RoleID     uint `gorm:"not null" validate:"required"`
	CompanyID  uint
}

// BeforeSave validates User model
func (u *User) BeforeSave() (err error) {
	err = validator.Validate.Struct(u)
	return
}
```

**Comment by joeybloggs** [comment]
Yep, multiple ways in the Doc you can use:
- https://godoc.org/gopkg.in/go-playground/validator.v9#hdr-Skip_Field
- https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.StructExcept
- https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.StructFiltered
- https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.StructPartial

I think the first is what you're looking for given your scenario; let me know if that helps :)
