### ISSUE TITLE
Support for Plan9

### ISSUE THREAD

**Issue by wongyinlok** [go-playground/validator#410]
### Package version eg. v8, v9: 
v8

### Issue, Question or Enhancement:
Is there or will there be support for Plan9?

**Comment by joeybloggs** [comment]
I’m not sure I understand the question, could you provide more details?

**Comment by wongyinlok** [comment]
I mean if this package can be run in Plan9. When I tried go get it said repository isn't supported.

**Comment by joeybloggs** [comment]
I've seen issues like that before where it's the git version, that `go get` uses under the hood that doesn't follow redirects; IIRC it was 1.7.3

what's your git version?

**Comment by wongyinlok** [comment]
I am using 2.2.0

**Comment by joeybloggs** [comment]
hmm @wongyinlok have you tried git cloning manually and using it? if that succeeds then it's something to do with the fetching rather than the package itself.

**Comment by wongyinlok** [comment]
@joeybloggs thanks for the reply, seems like the problem is with git. I tried git cloning manually and it didnt clone the package. Then I downloaded the zip and it seemed to work fine.
