### ISSUE TITLE
Specific Field validation of a Struct

### ISSUE THREAD

**Issue by dakait** [go-playground/validator#416]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question: I'm unable to figure out a way to validate a field of a struct. For example, I have a struct
```
type Foo struct {
	Id    int64  `json:"id" validate:"required"`
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`  
}
var foo Foo
```
I just want to check if `name` field is not empty. I have tried doing `StructPartial(foo, "Name")`.
I have also tried `StructExcept(foo, "Id")` for validating name and email fields. But none of that seems to work for me. What am I doing wrong ?

**Comment by joeybloggs** [comment]
Hey @dakait 

it's because the name is prefixed with the structs name, you'll want to do `StructPartial(foo, "Foo.Name")`

this is because this package supports multiple levels of nesting.

please let me know if this helps :)

**Comment by dakait** [comment]
I tried using `StructPartial(foo, "Foo.Name")` but it didn't help me. I want to add one more point to my question that Foo lies in some package X and `StructPartial(foo, "Foo.Name")` lies in package Y. 
So, I also tried
```
var foo X.Foo
StructPartial(foo, "X.Foo.Name")
```
But it didn't help me either.

**Comment by dakait** [comment]
Thanks @joeybloggs  for your help.
