### ISSUE TITLE
URN validation

### ISSUE THREAD

**Issue by leodido** [go-playground/validator#428]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Enable validation of a string value as a URN according to [RFC 2141](https://tools.ietf.org/html/rfc2141) spec.

### Code sample, to showcase or reproduce:

```go
type Config struct {
    path string `validate:"urn"`
}
```

**Comment by joeybloggs** [comment]
@leodido thanks for the PR!

Just one ask, because there are multiple RFC’s and this one is already obsoleted by 
https://tools.ietf.org/html/rfc814 can we rename it to urn_rfc2141?

One can always register an alias if they want to use the short name :)

**Comment by joeybloggs** [comment]
@leodido actually there is one more thing I noticed there was no license on the go-arn package used for the validation; I’d need a compatible license added before I can include

**Comment by leodido** [comment]
Hey @joeybloggs is a MIT compatible?

Regarding the name I agree with you. Was thinking to do exactly the same, since the other RFC (8141) is in the making.

**Comment by joeybloggs** [comment]
Yep MIT is compatible

**Comment by leodido** [comment]
Could you please review PR #429 ? I updated it.

**Comment by joeybloggs** [comment]
Merged the changes and released in https://github.com/go-playground/validator/releases/tag/v9.24.0 :)
