### ISSUE TITLE
assert.Equals() panics on type based on string

### ISSUE THREAD

**Issue by ansel1** [go-playground/validator#431]
### Package version eg. v8, v9: 
v9

### Issue:

When comparing unequal values of a type based on string, assert.Equals (and assert.EqualValues)
will panic: 

    panic: interface conversion: interface {} is example.Color, not string

panic occurs here:

    github.com/stretchr/testify/assert/assertions.go:1352 

It seems you cannot coerce an interface value to string just because the kind is string.  Probably should use 

### Code sample, to showcase or reproduce:

```go
type Color string

func TestColor (t *testing.T) {
	c1 := Color("red")
	c2 := Color("blue")

	assert.Equal(t, c1, c2)
}
```

**Comment by joeybloggs** [comment]
@ansel1 are you sure this has been posted to the correct place?

**Comment by ansel1** [comment]
I'm sure it hasn't.  :)  Sorry about that.
