### ISSUE TITLE
Namespace: how to ignore nested struct

### ISSUE THREAD

**Issue by byrnedo** [go-playground/validator#432]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:

I have a struct

```
type Y struct {
    Field string
...
}
type X struct {
    Y
}
```

If I call `Namespace()` on `FieldError` I'll get `X.Y.Field`.
Is there a way I can get `X.Field` instead?

**Comment by joeybloggs** [comment]
Hey @byrnedo, unfortunately, no and for a good reason too:
```
type Y struct {
    Field string
...
}
type X struct {
    Y
    Field string
}
```
this is perfectly valid and why Y is included in the names space in order to be able to differentiate between the 2.

**Comment by byrnedo** [comment]
My use case is to have send a json response like this for validation errors:

```
{
    "address.line_1": [ "required" ],
    "address.city": [ "required" ]
}
```

And namespace works fine until I've an anonymous struct in the path somewhere.
My hack right now is to snake case all json fields (and have a json field namer) and then remove any camel cased sections from the namespace. Works but sure will bit me in the ass at some point :p

Do you think it'd be useful to implement some kind of `JsonPath()` function to do this?

**Comment by byrnedo** [comment]
@joeybloggs If you think this isn't something that validator should care about then lets close this?

**Comment by Chi89** [comment]
There is a solution to  ignore nested struct on this link https://stackoverflow.com/questions/64093143/how-can-go-validator-check-fields-against-their-zero-value
