### ISSUE TITLE
Translator does not work with "|" operator (the OR operator)

### ISSUE THREAD

**Issue by thessem** [go-playground/validator#444]
This is a feature request.

I have a struct which is being validated with
```go
	Body struct {
		Type string                 `json:"type" validate:"eq=image|eq=video"`
	} `validate:"required,dive"`
```
When the error is translated, I am left with "Body.Type' Error:Field validation for 'ResourceType' failed on the 'eq' tag". I would expect an error which is represents some understanding of the OR operator here such as "Type is not equal to image or Type is not equal to video".

Alternatively, I would expect some way of setting this up myself, but it does not look like this functionality exists.

**Comment by joeybloggs** [comment]
@thessem the validator currently only reports on the error that occurred, however, there are 2 options to achieve what you're looking for:

1. You can register an [alias](https://github.com/go-playground/validator/blob/v9/validator_instance.go#L179) and then [register your own translation](https://github.com/go-playground/validator/blob/v9/_examples/translations/main.go) for it.

2. There is no requirement to use the built-in translations or error messages in this library, it returns all the information needed to create your own messages as you see fit, see [here](https://github.com/go-playground/validator/blob/v9/_examples/simple/main.go#L69) for an example.
