### ISSUE TITLE
Proposal: validator for regexp

### ISSUE THREAD

**Issue by tredoe** [go-playground/validator#447]
### Issue, Question or Enhancement:
A solution to add a validator based into a regular expression, would be to indicate the name of a variable with a compiled expression (*regexp.Regexp)

Usage: pattern=reName

```go
var reName = regexp.Compile(`[a-z]`)
```

**Comment by joeybloggs** [comment]
@tredoe at this point what would you not go the extra step and register it as a validation; it would be much clearer as to what it does via the validation tag also.

This is also dangerous as there's no compile-time checking you don't have a typo or that someone hasn't renamed your variable or removed it altogether unintentionally and it will blow up at runtime.
