### ISSUE TITLE
cross validation: if a.b is true, then validate a.c

### ISSUE THREAD

**Issue by mh-cbon** [go-playground/validator#452]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I was looking for a built-in validator that could help me to implement a validation logic of a field only if another field of the same struct is set to true;

typically, there is a checkbox, if checked there s an input that requires to be validated. otherwise it must be ignored.

### Code sample, to showcase or reproduce:
not a bug

**Comment by mh-cbon** [comment]
for future readers, i have implemented a custom validation like this 


```go
	app.Validator.RegisterValidation("iffalse", func(f validator.FieldLevel) bool {
			rv := f.Parent().Elem().FieldByName(f.Param())
			if !rv.IsValid() {
				log.Fatalf("field %q not found", f.Param())
			}
			if rv.Kind() == reflect.Ptr {
				rv = rv.Elem()
			}
			var v bool
			if rv.IsValid() {
				v = rv.Interface().(bool)
			}
			if v {
				return true
			}
			rs := f.Field()
			if rs.Kind() == reflect.Ptr {
				rs = rs.Elem()
			}
			s := rs.Interface().(string)
			return s != ""
		})
```

**Comment by joeybloggs** [comment]
@mh-cbon can you provide an example usage of the above validation? I'm curious to see how it's used and potentially add it to the built-in validations.
