### ISSUE TITLE
Get struct tags in custom validation

### ISSUE THREAD

**Issue by josephzidell** [go-playground/validator#454]
### Package version eg. v8, v9: 
v8

### Issue, Question or Enhancement:
How do you access a Field's tags in a custom validation func? I'm trying to implement enum validation, to restrict to a list of valid values.

### Code sample, to showcase or reproduce:

```go
type Payment struct {
	MethodID int `json:"methodId" binding:"required,enum" enum:"1,2,4,5"`
}

func checkEnum(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {
	// need to get the Tags here in order to check for valid values
}

// in main func
v.RegisterValidation("enum", checkEnum)
```

**Comment by joeybloggs** [comment]
You could use reflection on the `currentStructOrField` using reflection to get the field https://golang.org/pkg/reflect/#Value.Field

And then get the tag using `field.Tag.Get("enum")`

instead, though I highly recommend having you enum defined outside of your validation and loaded into a map instead for efficiency, see [here](https://github.com/go-playground/validator/issues/313#issuecomment-333722803) for an example

please let me know if this helps :)

**Comment by josephzidell** [comment]
@joeybloggs Thanks for the pointer. Can you help me further?

This is my code (edited):
```go
	for i := 0; i < currentStructOrField.NumField(); i++ {
		if enum := currentStructOrField.Type().Field(i).Tag.Get("enum"); len(enum) > 0 {
			// do the checking
		}
	}
```
but this only works for the first field containing an enum.
Example:
```go
type Payment struct {
	MethodID int    `json:"methodId" binding:"required,enum" enum:"1,2,4,5"` // works
        State    string `json:"state" binding:"required,enum" enum:"Authorized,Captured"` // doesn't work
}
```

**Comment by deankarn** [comment]
@josephzidell each field should call your function and then the enum lofic again, am I missing something?

**Comment by josephzidell** [comment]
I have moved on from that project and company.
