### ISSUE TITLE
How to inject dependencies on custom validator

### ISSUE THREAD

**Issue by bpaz** [go-playground/validator#457]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Hello. I am creating a custom validator where I need to access a service for my application. My question is how can I inject that service into my validator?

The "RegisterValidation" only receives a function? Can I pass a function from a struct?

Thank you.

**Comment by joeybloggs** [comment]
This is almost identical to a previous questions [here](https://github.com/go-playground/validator/issues/462) please task a look at my 2 suggestions and let me know if that makes sense.
