### ISSUE TITLE
Unexpected behavior with validate Struct requires dive

### ISSUE THREAD

**Issue by fabianbaier** [go-playground/validator#458]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

When I try to validate my nested struct I do not see that it `automatically validates nested structs` as described here: https://sourcegraph.com/github.com/go-playground/validator/-/blob/validator_instance.go#L261:20&tab=references

Instead I need to use dive to force looking at the nested struct. In the example below when you run it without dive I get:
```bash
$ go run dive.go 
<nil>
```

but I would expect an error. With dive I get the desired outcome:
```bash
$ go run dive.go 
Key: 'Test.NestedStruct[0].Name' Error:Field validation for 'Name' failed on the 'required' tag
```

Do you know why? Shouldn't `validate.Struct(test)` automatically validate the nested struct as well?
### Code sample, to showcase or reproduce:

```go
// dive.go 
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

// Test ...
type Test struct {
	Array []string          `validate:"required,gt=0,dive,required"`
	NestedStruct   []NestedStruct `validate:"gt=0,required"`
	//NestedStruct   []NestedStruct `validate:"gt=0,required,dive"`
}

type NestedStruct struct {
	Name string `validate:"required"`
}

// use a single instance of Validate, it caches struct info
var validate *validator.Validate

func main() {

	validate = validator.New()

	test := Test{
		Array: []string{"test"},
		NestedStruct: []NestedStruct{
			{""},
		},
	}

	val(test)

}

func val(test Test) {
	err := validate.Struct(test)
	fmt.Println(err)
}
```

**Comment by joeybloggs** [comment]
Hey @fabianbaier yes I can describe this behaviour and why it's like this.

There are actually two levels of validation that can be done on types such as arrays and maps:
1. Is checking what I call top-level properties that don't relate to the internal values such as the length of the array or map which the `required` tag handles.

2. Is checking the values of array or map.

to do this there needed to be a way to separate what validations are run for the top-level and which for the values, which is where `dive` comes in to provide that functionality; also sometimes people don't wish to validate the contents but just rather there are contents.

please let me know if this helps :)
