### ISSUE TITLE
how to check custom regist tag  is used by other registFunc

### ISSUE THREAD

**Issue by AdwindOne** [go-playground/validator#465]
### Package version eg. v8: 
How can be tell tag has been registered

### Issue, Question or Enhancement:

how to Batch transaction  English to other language  like "required" into "不能为空" 

### Code sample, to showcase or reproduce:

```go

```

**Comment by joeybloggs** [comment]
Hey @AdwindOne I'm not sure I completely understand what you're asking, can you please clarify your request?

**Comment by AdwindOne** [comment]
sorry,  How do I know if the alias of my self-defined validation rule is being used
