### ISSUE TITLE
How to not allow white space in a string

### ISSUE THREAD

**Issue by tnolet** [go-playground/validator#466]
### Package version eg. v8, v9: 

V8, because using in conjunction with gin gonic.

### Issue, Question or Enhancement:

How do I exclude a whitespace from a string?
I have a name that should allow all unicode characters, except a white space. I can't figure it out in the docs.

### Code sample, to showcase or reproduce:

```go
type Policy struct {
	Id      string `json:"id"`
	Name    string `json:"name" binding:"required,min=3,max=20, ascii,exclude=<some way of defining whitespace>`
	Version int    `json:"version"`
	Steps   []Step `json:"steps" binding:"required,dive"`
}
```

**Comment by syssam** [comment]
https://github.com/go-playground/validator/blob/v8.18.2/examples/custom/custom.go

**Comment by joeybloggs** [comment]
@tnolet I think your looking for `excludesall` and does adding a space not work?

PS: you can use v9 with Gin, see [here](https://github.com/go-playground/validator/tree/v9/_examples/gin-upgrading-overriding)
