### ISSUE TITLE
Validating a string for positive numeric value

### ISSUE THREAD

**Issue by bondhan** [go-playground/validator#467]
### Package version eg. v8, v9: 
V9

### Issue, Question or Enhancement:
How to validate a string positive numeric?

### Code sample, to showcase or reproduce:

```go

type Payment struct {
	UserAgent   string `json:"user_agent" validate:"required,numeric,gt=0"`
}
```
I have read that for gt (greater than) for string means the length of the string itself. The above will pass  when user_agent = "-1", how to validate for the same (disallow negative number on string numeric)? Please advise. Thanks!

**Comment by syssam** [comment]
1. Change to string to int
2. Use custom method https://github.com/go-playground/validator/blob/v9/_examples/custom/main.go
3. Please see my validator implement

**Comment by vijaykd21** [comment]
Hi  I hit the same. This is not very clear.
The tag has `numeric` hence from here onward the test on this field should ideally be carried on as numeric value, where 
`gt=0` should be tested as follows:
```
// isGt is the validation function for validating if the current field's value is greater than the param's value.
func isGt(fl FieldLevel) bool {
	field := fl.Field()
	param := fl.Param()

	switch field.Kind() {

	case reflect.String:
		p := asInt(param)

		return int64(utf8.RuneCountInString(field.String())) > p // currently hitting this, which is checking the length of the string.
```
Ideally we should be using: 
```
case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		p := asIntFromType(field.Type(), param)

		return field.Int() > p
```
As the ct.type = "numeric".
