### ISSUE TITLE
Is there a way of partial validating an array of structs without having to pass all indexes of the array?

### ISSUE THREAD

**Issue by jhullse** [go-playground/validator#472]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Is there a way of partial validating an array of structs without having to pass all indexes of the array?

### Code sample, to showcase or reproduce:
```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type Struct struct {
	SubStructs []SubStruct `validate:"required,dive"`
}

type SubStruct struct {
	ValidationRequired    int `validate:"gt=1"`
	ValidationNotRequired int `validate:"gt=1"`
}

func main() {
	validate := validator.New()

	st := Struct{
		SubStructs: []SubStruct{
			{
				ValidationRequired: 1,
			},
			{
				ValidationRequired: 1,
			},
		},
	}

	// at this point we have to add all array indexes,
	// something like SubStructs[].ValidationRequired
	// would be nice
	err := validate.StructPartial(
		st,
		"SubStructs[0].ValidationRequired",
		"SubStructs[1].ValidationRequired",
	)

	fmt.Println(err)
}
```

**Comment by deankarn** [comment]
@jhullse sorry no such way exists beyond passing each index sorry. Not sure how I would go about this either beyond perhaps using a struct level validation.

let me know if using a struct level validation works for you.

**Comment by jmvbxx** [comment]
@jhullse Thank you for sharing this issue. Following up to see if Dean's recommendation helped. We're going to go ahead and close this issue but please feel free to reopen if you have questions or comments.
