### ISSUE TITLE
Email doesn't allow +s

### ISSUE THREAD

**Issue by robinjoseph08** [go-playground/validator#476]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

When using the `email` validator, it doesn't allow values with `+` before the `@` which is a common thing [Gmail allows you to do](https://gizmodo.com/how-to-use-the-infinite-number-of-email-addresses-gmail-1609458192). For example, `test+2@gmail.com` fails validation.

### Code sample, to showcase or reproduce:

```go
type loginParams struct {
	Email    string `form:"email" json:"email" mod:"lcase,trim" validate:"required,email"`
	Password string `form:"password" json:"password" validate:"required,min=8"`
}
```

**Comment by deankarn** [comment]
Thanks for pointing this out @robinjoseph08 

It will likely be a bit before I can look into it, happy to accept a PR in the meantime though :)

**Comment by JonathanWThom** [comment]
For what it's worth, I wasn't able to replicate this with the following code:

```
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type loginParams struct {
	Email    string `form:"email" json:"email" mod:"lcase,trim" validate:"required,email"`
	Password string `form:"password" json:"password" validate:"required,min=8"`
}

func main() {
	validate := validator.New()
	login := &loginParams{
		Email:    "test+2@gmail.com",
		Password: "password",
	}
	err := validate.Struct(login)
	if err != nil {
		// nothing prints here
		fmt.Println(err)
	}
}
```

I know the issue was for v9, but it's worth noting that a test for "test+2@email.com" passes against v10. 

Definitely possible that I'm missing something though!

**Comment by doi-t** [comment]
I also confirmed that v10 works for "test+2@email.com". 👍

**Comment by zemzale** [comment]
If this works with v10 I suppose it's fine to close this issue?

**Comment by jmvbxx** [comment]
Thank you @robinjoseph08 for the original issue. Given that the issue no longer applies to the latest version `v10` we're going to go ahead and close this. Please feel free to reopen if you have any follow up questions.
