### ISSUE TITLE
Is isIPAddrResolvable working correctly?

### ISSUE THREAD

**Issue by dealancer** [go-playground/validator#477]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

It looks like the following function does not work correctly:

```
// IsIPAddrResolvable is the validation function for validating if the field's value is a resolvable ip address.
func isIPAddrResolvable(fl FieldLevel) bool {

	if !isIP(fl) {
		return false
	}

	_, err := net.ResolveIPAddr("ip", fl.Field().String())

	return err == nil
}
```

It does not resolve "localhost" because `isIP` returns `false`, however `net.ResolveIPAddr` returns `true`.

Any ideas?

**Comment by deankarn** [comment]
Hey @dealancer I believe that it is working correctly and why the `isIp` check comes before the `ResolveIpAddr` because `localhost` is not a valid IP but a `hostname` which can resolve to an IP.
