### ISSUE TITLE
numeric and number are mixed up

### ISSUE THREAD

**Issue by dealancer** [go-playground/validator#478]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Right now the regular expressions for number and numeric are mixed up. Here is a reasoning.

* Number could be negative
* Numeric is just a number without a sign or a dot (because of alphanumeric pattern)

The behavior should be vice-versa. Am I right?

**Comment by deankarn** [comment]
For `Number` I suppose it's true this could be negative, however changing it now would be a breaking change.

For `Numeric` I think your confusing it with `Alphanumeric`; just because it hase `numeric` in it's name does not denote equivelence:
```
Numeric may refer to any of the following:
numeric

1. Numeric is anything of, relating to, or containing numbers. The numbering system consists of ten different digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, and 9. If a value is an alphanumeric, it contains letters and numbers.
```
