### ISSUE TITLE
Custom Msg For Cross Field Validation (& turn it to camel case)

### ISSUE THREAD

**Issue by tronch0** [go-playground/validator#482]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

I'm using the Validate pkg (really awesome!) but I'm stuck with one small thing, how can i register custom message for multi parameters message which is highly important if I want to do cross fields validation.

So I'll stop mumbling now and get to a concrete example :)

### Code sample, to showcase or reproduce:

I have a struct with two fields:

```
type Person struct {
  YearBorn int `validate:"ltefield=YearDied"`
  YearDied int `validate:"gtefield=YearBorn"`
}
```
As you can see I just added a logical validation `YearBorn <= YearDied`.

everything works as expected up till here.

but when I want to overwrite the message with my own custom message I get an OutOfRange error that my '{1}' placeholder causes.

here is how I register the new message:

I create a function for register custom messages:

```
func registerErrorMsg(v *validator.Validate, trans ut.Translator, tagName string, errorMsg string) error {
	err := v.RegisterTranslation(tagName, trans, func(ut ut.Translator) error {
		return ut.Add(tagName, errorMsg, true)
	},
		func(ut ut.Translator, fe validator.FieldError) string {
			t, _ := ut.T(tagName, fe.Field())
			return t
		})
	if err != nil {
		return err
	}
	return nil
}
```

Then I call it with:
```
err = registerErrorMsg(v, trans, "ltefield", "{0} must be less than or equal to {1}")
	if err != nil {
	     return err
}
```

Small side note, the reason that I want to override the message is becuase the return message contain the actual field name(CamelCase) and not the json tag (snake_case).

I also register a tag name function that takes care of that:

```
validator.RegisterTagNameFunc(func(fld reflect.StructField) string {
		name := strings.SplitN(fld.Tag.Get("codec"), ",", 2)[0]
		if name == "-" {
			return ""
		}
		return name
})
```

So to conclude, I have two questions:
1. How can I override with custom message that have two parameters?
2. Can I register a TagNameFunc that will take care of the other field in the cross field validation?

Thanks,
Ron

```go

```

**Comment by deankarn** [comment]
Hey @tronch0 

1. I think you're getting the out of range error because when calling the translation you only passed in one parameter in when the translation is registered with 2:
```go
t, _ := ut.T(tagName, fe.Field()) 

should be 

t, _ := ut.T(tagName, fe.Field(), fe.Param()) <-- or whatever you need the second param to be.
```

2. no there is no way at getting at the other field information as if it were an error.
