### ISSUE TITLE
omitempty on pointers only checks if present or nil

### ISSUE THREAD

**Issue by bt** [go-playground/validator#485]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
`omitempty` on pointers only checks if present or nil, skipped if the underlying string is empty.

I have a field that I want to pass if it is not present `eg: omitempty` or if it's empty, `eg: ""`. However, `omitempty` only checks that the string is `nil`. If the string is defined and empty, `""`, it moves onto the next validation; in my example below, that is `alphanum`, which will return `false`.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

type User struct {
	Name *string `validate:"omitempty,alphanum"`
}

var validate *validator.Validate

func main() {
	validate = validator.New()

	emptyStr := ""
	u := User{
		Name: &emptyStr,
	}
	if err := validate.Struct(u); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Test OK")
	}
}
```

**Comment by deankarn** [comment]
Hey @bt this is desired behaviour for `omitempty` as this validation is from the perspective of the field itself and not the field's value. as you stated it's basically only to check for the presence of a value.

Once presence has been verified you can use the `required` validation to verify if the value itself is empty/the type default value.

eg.
```go
type User struct {
	Name *string `validate:"omitempty,required,alphanum"`
}
```

let me know if this helps :)

**Comment by bt** [comment]
Hey @deankarn 
I'm trying that but it seems to not work the way I wanted, but sorry I just re-read my issue and I think I was not clear.

I have a field; it's meant to be a JSON object. There's 4 possibilities:

1. The field is not set at all. This should pass (eg. `omitempty`)
2. The field is set, but empty. This should pass (eg. opposite of `required`)
3. The field is set, but not a JSON object. This should fail (eg. custom validation using `RegisterValidation`)
4. The field is set, is a JSON object. This should pass.

I'm fine with 1, 3 and 4. But I cannot get 2 to work, because there's no way to `omitempty` if pointer is set but is the default value.

**Comment by deankarn** [comment]
@bt sounds like there are a couple of options for No. 2 above:
1. Register a custom validation that works for when it's blank.
2. you can use the `or` syntax eg. `omitempty,eq=|alphanum`

I haven't tested but that should work.

**Comment by bt** [comment]
@deankarn Ah okay -- I thought there would be another way of doing it. I've been using the 1st option as it is more descriptive.

Not sure if this is something that you would want to be supported as a validator.

**Comment by deankarn** [comment]
@bt I’m not sure if I can integrate such a change into the current codebase as although omitempty is a tag you can use, it’s not backed by a validation function but rather part of the control flow, I’d have to do a deep dive to see if it’s possible to make it be backed by a function which would allow overriding. I suspect that I’d have to expose some internals like required as well, it being central to the omitempty logic.

Considering there is a way to do this without omitempty checking for a blank and I want to keep this low level I don’t think I want to add it to the base logic.

BTW have you seen the alias logic? you may be able to alias omitempty and the blank check into your own tag without creating a custom validation in itself.
