### ISSUE TITLE
Additional method for FieldError interface

### ISSUE THREAD

**Issue by BentCoder** [go-playground/validator#508]
### Package version eg. v8, v9: 
v9

### Enhancement:
Is there a plan to add one more method to [FieldError](https://github.com/go-playground/validator/blob/v9/errors.go#L83) that returns what `Namespace()` already returns but without the root struct name?

Currently this is what I am doing `err[e.Namespace()] = fmt.Sprintf("The %s.", e.Translate(trans))` in error loop but I will have to run extra logic to get rid of struct prefix from `e.Namespace()`.

### Code sample, to showcase or reproduce:

```go
e.Namespace() // LeagueRequestBodyStruct.teams[0].name
e.NamespaceWithoutRootStruct() // teams[0].name <------- something like this
```

Thanks

**Comment by WhileLoop** [comment]
I ended up using this work around, which works as long as there aren't nested struct names.

```
ns := e.Namespace()
first := strings.IndexRune(ns, '.')
last := len(ns)
field := ns[first + 1:last]
```

**Comment by BentCoder** [comment]
I use this for now.

```go
		for _, e := range err.(validator.ValidationErrors) {			lst[strings.TrimPrefix(e.Namespace(), reflect.TypeOf(structure).Name()+".")] =				fmt.Sprintf("The %s.", e.Translate(trn))		}
```
