### ISSUE TITLE
Document list of all available rules for increased productivity

### ISSUE THREAD

**Issue by PrakharSrivastav** [go-playground/validator#509]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
During development, it will be extremely useful to have a list of available validation methods available at one place for reference. I understand that I can look at the package to see the available validation methods, but switching back and forth between packages is slow.

I want to request a *.md file which I can open in a browser tab and quickly reference the validation to check if rule is called min or minimum for example.

An example to refer would be https://respect-validation.readthedocs.io/en/1.1/list-of-rules/
where I can see everything quickly. I think a list of this kind would really boost developer productivity.

### Code sample, to showcase or reproduce:

```go
type RegisterRequest struct {
       // an md file will be useful to quickly see if rule is called alpha, alphanumeric or alphabet
	FirstName   string `json:"first_name" validate:"required,min=3,alpha"`
	LastName    string `json:"last_name"`
}
```

**Comment by deankarn** [comment]
@PrakharSrivastav a good idea, even though the functionality is listed in the docs it's hard to read.

I would welcome any help with this, github pages would be great and I could wire up my `go-playground` domain :)

**Comment by psampaz** [comment]
@deankarn what about a simple alphabetical list in README which contains the tag name and a small description? If someones needs more details, then the  go doc is the right place.


| Tag           | Description |
|-| ----------- |
| alpha | |
| alphanum | |
| alphanumunicode | |
| alphaunicode | |
| ascii | Checks if a string is contains only ASCII characters |
| base64 | Checks if a string is base64 encoded |
| base64url | |
| btc_addr | |
| btc_addr_bech32 | |
| cidr | |
| cidrv4 | |
| cidrv6 | |

Another idea would be to group them by functionality

## Crossfield validations

| Tag           | Description |
|-| ----------- |
| ltcsfield | |
| lte | |
| ltecsfield | |
| ltefield | |
| ltfield | |

## Network validations

| Tag           | Description |
|-| ----------- |
| tcp4_addr | |
| tcp6_addr | |
| tcp_addr | |
| udp4_addr | |
| udp6_addr | |
| udp_addr | |

## Other validations

| Tag           | Description |
|-| ----------- |
| alpha | |
| alphanum | |
| alphanumunicode | |

**Comment by deankarn** [comment]
@psampaz I'd be good with either, grouped might be the easiest to consume :)

would love some help on this :)

**Comment by psampaz** [comment]
Ok cool. Let me do the first draft with groups and I will ping you.

Just the tag name and a short description, correct?

Ideally the types that the tag applies would be very helpful. No need to
check the code for this if it is in the readme.



Στις Δευ, 10 Φεβ 2020, 18:16 ο χρήστης Dean Karn <notifications@github.com>
έγραψε:
