### ISSUE TITLE
How to set custom tag name when use validate.Var() for single variable

### ISSUE THREAD

**Issue by SoulSu** [go-playground/validator#513]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

I want translate my validate error 

The `validate.Struct()` function can use `validate.RegisterTagNameFunc()` for register a tag name to change `fieldError.ns ` value for I want， but I don't find how to set custom tag name for  `validate.Var()` func.

### Code sample, to showcase or reproduce:

```go
age := 150
v := validator.New()
err := v.Var(age, "required,lt=120")
// real: Key: '' Error:Field validation for '' failed on the 'lt' tag
// want: Key: 'age' Error:Field validation for 'age' failed on the 'lt' tag 
fmt.Printf("%v", err) 
```

Thanks

**Comment by benrowe** [comment]
Same problem applies if you provide custom validation. I can't see a way to specify the field name manually.

**Comment by fonini** [comment]
Need this too

**Comment by tsu1980** [comment]
https://github.com/go-playground/validator/issues/625#issuecomment-701685379

**Comment by 9tec7** [comment]
i don't think that is the proper way for this issue. 
It's good to have a proper solution for this like how we get proper key value when we use `v.Struct()`

**Comment by tsu1980** [comment]
Yep. In the end, I solved the problem by using anonymous structs.
```
age := 150
v := validator.New()

reqParams := struct {
  Age int `validate:"required,lt=120"`
}{
  Age: age,
}

err := v.Struct(&reqParams)
```

**Comment by jmvbxx** [comment]
@SoulSu Thank you for your question. It appears that @tsu1980 provided a solution. Does this work for you? For now, we're going to close this issue. Please feel free to reach out if you have any questions.
