### ISSUE TITLE
Best practice to use validator in high traffic web service?

### ISSUE THREAD

**Issue by laughmetal** [go-playground/validator#528]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
What's the best practice to use validator for a web service that has high traffic?

### Code sample, to showcase or reproduce:

```go
// The following code works.
// However, calling New() for each income request doesn't seem to be efficient.
// Another thing I'd like to avoid is global variable.
// Is there any solution to create validator as "static member variable" or "singleton"?

err := validator.New().Struct(mystruct)
```

**Comment by thinkgos** [comment]
I think you need pools to cache it.

**Comment by deankarn** [comment]
@laughmetal @thinkgos you should not call `validator.New()` but create a single instance and reuse it in your service.

Validator has an internal cache for struct parsing & information already and is completely thread-safe.

I won't go into the details of how to share it around, that's really up to what framework your using and how you want to inject context or ther dependencies.

**Comment by laughmetal** [comment]
Thanks for the inputs @thinkgos @deankarn !
Creating a single instance for the service was exactly what I did.

Closing this question.

**Comment by thinkgos** [comment]
got it ,thanks.
