### ISSUE TITLE
validate on embedded type

### ISSUE THREAD

**Issue by tjblackheart** [go-playground/validator#532]
Version: v9

Hello! I have build something like this to get rid of some code duplication:

```go
type request struct {
	Order   string `validate:"required,numeric,len=16"`
	Zipcode string `validate:"required,numeric,len=5"`
}

type StatusRequest struct {
	request
	ShopID  int `validate:"required,number"`
}

type CancelRequest struct {
	request
	Type    int `validate:"required,number"`
	Reason  int `validate:"required,number"`
}

func (r *request) Validate(v *validator.Validate) ErrList {
	if err := v.Struct(r); err != nil {
		// ...
	}
}
```

However, if I call this (from a test) for example from a `StatusRequest.Validate`, it validates only for `request`, but not the type which called. Is this even possible or do I have to use the validator only on the actual types?

**Comment by deankarn** [comment]
@tjblackheart Have you tried exposing `request` as `Request`?

there's a limitation to reflection and unexposed Fields/Structs.

**Comment by tjblackheart** [comment]
Hi, thanks for your reply! I tried, but that makes no difference. Actually the more I think about this, the more sense it makes - the validator can only be bound to one type, right? So I'll guess I have to do the extra legwork and validate both child structs in separate.

**Comment by jmvbxx** [comment]
@tjblackheart Thank you for your question. It appears this issue has been resolved. We're going to go ahead and close it but if you have any follow-up questions please don't hesitate to ask.
