### ISSUE TITLE
[Que/Enh] Aligning error list structure with input structure/json

### ISSUE THREAD

**Issue by BentCoder** [go-playground/validator#533]
Hi,

Just wondering if there is a way or plan in future to construct error list in such a way that it matches the input structure rather than using numeric indexes. See example below for better explanation. Currently using `v9`.

**Note**: This is also linked to [this](https://github.com/go-playground/validator/issues/508) issue otherwise list will contain struct names etc. I think there can be a method that final error list into json representation such as `....toString()`.

Thanks

**Invalid request**

```json
{
  "first_name": "",
  "friends": [
    {
      "name": ""
    }
  ]
}
```

**Current error list**

```json
{
  "first_name": "whatever the error message",
  "friends[0].name": "whatever the error message"
}
```

**Expected**

```json
{
  "first_name": "whatever the error message",
  "friends": [
    {
      "name": "whatever the error message"
    }
  ]
}
```

**Comment by deankarn** [comment]
Hey @BentCoder I currently have no plans to change the output. I may in the future add a parser, just like translations, where a custom mapper/error output based on a registered function, but that's a far out at this point.
