### ISSUE TITLE
https://godoc.org/github.com/go-playground/validator/v10 is 404d

### ISSUE THREAD

**Issue by kaelanfouwels** [go-playground/validator#536]
### Package version eg. v8, v9: 
v9/v10

### Issue, Question or Enhancement:
The godoc for both v9 and v10 is 404d. :'(

### Code sample, to showcase or reproduce:

![image](https://user-images.githubusercontent.com/2944543/68661786-6b4e8380-0533-11ea-8ec9-d1e6ae2de42d.png)

**Comment by deankarn** [comment]
I'm not sure where these links came from @kaelanfouwels but the lonks in the v9 & v10 readme's work as expected:
`v10` - https://godoc.org/github.com/go-playground/validator
`v9` - https://godoc.org/gopkg.in/go-playground/validator.v9

**Comment by kaelanfouwels** [comment]
Ah, the readme currently lists the url with an extension of **/v10** on the github.com url.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/2944543/69012573-2b423300-096f-11ea-904a-db0a54f4171a.png">

**Comment by deankarn** [comment]
perfect thanks @kaelanfouwels, merged and will release with some other things today :)
