### ISSUE TITLE
need lint tool

### ISSUE THREAD

**Issue by okhowang** [go-playground/validator#537]
### Package version eg. v8, v9: 
v8

### Issue, Question or Enhancement:
can we have a lint tool for check misuse of tag
not panic runtime

### Code sample, to showcase or reproduce:

```go
type S1 struct {
    IntField int `validate:"exists"`
    NonSliceField string `validate:"dive,required"`
}
```

**Comment by deankarn** [comment]
@okhowang I can see how this would be useful I, however, don't have the bandwidth to create such a tool but wholy support someone making one 😄 

FWIW I rely on tests to ensure what I'm validsating works and makes sense.
