### ISSUE TITLE
go.mod has non-....v9 module path "github.com/go-playground/validator/v10" at revision v9.30.1

### ISSUE THREAD

**Issue by bboehmke** [go-playground/validator#549]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I get this error message for updating a project using v9:
```
go get: upgrading gopkg.in/go-playground/validator.v9@v9.30.0: gopkg.in/go-playground/validator.v9@v9.30.1: invalid version: go.mod has non-....v9 module path "github.com/go-playground/validator/v10" at revision v9.30.1
```

This is maybe caused by the go.mod file in the version v9.30.1 that point to the v10 branch.
https://github.com/go-playground/validator/blob/v9.30.1/go.mod

**Comment by bboehmke** [comment]
It seems that the latest v9 tags went to the wrong branch:
![image](https://user-images.githubusercontent.com/9787279/69571680-e6e41200-0fc2-11ea-98f1-410b59953d55.png)

**Comment by deankarn** [comment]
@bboehmke thanks for reporting, looks like I cut against the wrong branch, try https://github.com/go-playground/validator/releases/tag/v9.30.2

**Comment by bboehmke** [comment]
thanks for the fast fix, it is working now
