### ISSUE TITLE
how to validate json request

### ISSUE THREAD

**Issue by AliBedaer** [go-playground/validator#552]
Hi i want to validate a request body (application/json):
but every time i get this error 

> 2019/12/03 06:07:18 http: panic serving [::1]:51412: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc0002d0000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x8444a0, 0xc11700)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/go-playground/validator/v10.(*Validate).StructCtx(0x0, 0x95b4e0, 0xc00001c108, 0x8838c0, 0xc0002e4180, 0x1a, 0x0)
	/home/mekadoo/go/pkg/mod/github.com/go-playground/validator/v10@v10.0.1/validator_instance.go:299 +0x1fb
github.com/go-playground/validator/v10.(*Validate).Struct(...)
	/home/mekadoo/go/pkg/mod/github.com/go-playground/validator/v10@v10.0.1/validator_instance.go:277
github.com/AliBedaer/go-blog/controllers.(*PostsController).NewPost(0xc3c670, 0x95a720, 0xc0002ec000, 0xc000300100)
	/media/mekadoo/67969EAF034747B7/study/go/blog/controllers/PostsController.go:39 +0x252
net/http.HandlerFunc.ServeHTTP(0xc00028c5e0, 0x95a720, 0xc0002ec000, 0xc000300100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000190540, 0x95a720, 0xc0002ec000, 0xc0002c8100)
	/home/mekadoo/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc00029c000, 0x95a720, 0xc0002ec000, 0xc0002c8100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0002d0000, 0x95b4a0, 0xc0002b20c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

and here is the i use 
```go
// NewPost : Create new Post
func (controller *PostsController) NewPost(response http.ResponseWriter, request *http.Request) {

	var post models.Post

	// requestBody, err := ioutil.ReadAll(request.Body)
	err := json.NewDecoder(request.Body).Decode(&post)
	helper.ValidateError(err)

	fmt.Println(post)

	erro := validate.Struct(post)

	if erro != nil {

		// this check is only needed when your code could produce
		// an invalid value for validation such as interface with nil
		// value most including myself do not usually have code like this.
		if _, ok := err.(*validator.InvalidValidationError); ok {
			fmt.Println(err)
			return
		} else {
			fmt.Println(err)
			return
		}

		// fmt.Println(err.(validator.ValidationErrors))

		for _, err := range err.(validator.ValidationErrors) {

			fmt.Println(err.StructField(), " is : ", err.Tag())
			// fmt.Println(err.Namespace())
			// fmt.Println(err.Field())
			// fmt.Println(err.StructNamespace()) // can differ when a custom TagNameFunc is registered or
			// fmt.Println(err.StructField())     // by passing alt name to ReportError like below
			// fmt.Println(err.Tag())
			// fmt.Println(err.ActualTag())
			// fmt.Println(err.Kind())
			// fmt.Println(err.Type())
			// fmt.Println(err.Value())
			// fmt.Println(err.Param())
			// fmt.Println()
		}

		// from here you can create your own error messages in whatever language you wish
		return
	}

	post.CreatePost(&post)
	resp := map[string]string{"message": "Post Created Successfully"}
	response.Header().Set("Content-Type", "application/json")
	json.NewEncoder(response).Encode(resp)

}
```
``` go
type Post struct {
	Id      uint   `validate:"required"`
	Title   string `validate:"required"`
	Desc    string `validate:"required"`
	Content string `validate:"required"`
}
```
any help how to validate a post request from json api ??

**Comment by griffinmartin** [comment]
Did you instantiate `validate` with `validator.New()`?
