### ISSUE TITLE
customRegisFunc tags for translations

### ISSUE THREAD

**Issue by jamesgoodhouse** [go-playground/validator#553]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
Question

### Code sample, to showcase or reproduce:
https://github.com/go-playground/validator/blob/master/translations/en/en.go#L34-L65

I have dug around the code quite a bit and do not understand how a tag like `len-string-character` for example is consumed? I know there is a validator `len`, and I know that the validation results in different translated text if it's a string or an int or slice, etc. But it's completely opaque to me where in the code the additional type information is concatenated with the name of the validator. Can you point me in the proper direction? I've been trying to dig into the translators, but it's very confusing unfortunately.

**Comment by moroz** [comment]
@jamesgoodhouse Could you explain how it works?

**Comment by jamesgoodhouse** [comment]
> @jamesgoodhouse Could you explain how it works?

oh boy, i wish i could remember. and wish i would have returned and explained instead of just closing this.
