### ISSUE TITLE
how to validate value is required if any of the other specified field  is equal to the parameter given

### ISSUE THREAD

**Issue by ticktap** [go-playground/validator#556]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
how to validate value is required if any of the other specified field  is equal to the parameter given?

### Code sample, to showcase or reproduce:

```go
type params struct {
	Type int
	Name string
}
//  if Type == 1, Name is required
```

**Comment by deankarn** [comment]
Hey @ticktap currently there is no built in-validation that can handle this use case, you'll have to:

Register a custom validation
or
Register a struct level validation.
