### ISSUE TITLE
How can I define custom error message?

### ISSUE THREAD

**Issue by bakbuz** [go-playground/validator#559]
How can I define custom error message? I don't want to make a detailed explanation. I just want to make a brief statement.

### For example:

```go
type RegisterRequest struct {
	Username    string `validate:"required"` 		// UsernameIsRequired
	Email       string `validate:"required,email"` 		// EmailIsRequired,EmailIsNotValid
	Password    string `validate:"required,gte=8,lte=32"`   // PasswordRequired,PasswordGreaterThan8,PasswordLessThan32
}
```

**Comment by deankarn** [comment]
@bakbuz take a look at the example of the translation for custom error message by locale https://github.com/go-playground/validator/blob/master/_examples/translations/main.go it's geared towards more general messages for each tag.

If you need more custom messages I recommend creating your own messaging layer using all the information returned by each error, see the simple example for details https://github.com/go-playground/validator/blob/master/_examples/simple/main.go#L69

**Comment by bakbuz** [comment]
Thank you very much.

**Comment by bilalcaliskan** [comment]
Defining custom error messages are unneccessarily hard, i do not know why.

**Comment by krazik-intuit** [comment]
I agree @bilalcaliskan!

multiple steps to define which seems not ideal and then I still have to process/translate the errors that are returned from the library keeping a "global" translation instance around.  I don't understand why the libary can't handle the translation internally before return an error.

ie: https://github.com/go-playground/validator/blob/master/_examples/translations/main.go#L126. 

🤯

**Comment by johngtrs** [comment]
A guy helped me on stackoverflow to easily create my custom error messages by watching the current tag.

```go
type ApiError struct {
	Param   string
	Message string
}

type User struct {
	FirstName      string `binding:"required"`
	LastName       string `binding:"required"`
	Age            uint8  `binding:"gte=0,lte=130"`
	Email          string `binding:"required,email"`
	FavouriteColor string `binding:"iscolor"`
}

func msgForTag(fe validator.FieldError) string {
	switch fe.Tag() {
	case "required":
		return "This field is required"
	case "email":
		return "Invalid email"
	}
	return fe.Error() // default error
}

// Gin handler in my case
func handler(c *gin.Context) {
	var u User
	if err := c.ShouldBindQuery(&u); err == nil {
		c.JSON(http.StatusOK, gin.H{"message": "Good Job"})
	} else {
		var ve validator.ValidationErrors
		if errors.As(err, &ve) {
			out := make([]ApiError, len(ve))
			for i, fe := range ve {
				out[i] = ApiError{fe.Field(), msgForTag(fe)}
			}
			c.JSON(http.StatusBadRequest, gin.H{"errors": out})
		}
		return
	}
}
```
And the output will be: 

```json
{
    "errors": [
        {
            "Param": "FirstName",
            "Message": "This field is required"
        },
        {
            "Param": "LastName",
            "Message": "This field is required"
        },
        {
            "Param": "Email",
            "Message": "Invalid email"
        },
        {
            "Param": "FavouriteColor",
            "Message": "Key: 'User.FavouriteColor' Error:Field validation for 'FavouriteColor' failed on the 'iscolor' tag"
        }
    ]
}
```

**Comment by vladyslav2** [comment]
@johngtrs John, i'm trying to run your example and getting an error
```
➜  escrow-worker git:(master) ✗ go run main.go
# command-line-arguments
./main.go:30:12: fe.Error undefined (type validator.FieldError has no field or method Error)
```

my guess validator API changed? how do you do it now?

**Comment by seeff00** [comment]
Is there any solution for custom message for other type different than 'string'. For example int, uint, float, float64 etc ...???

**Comment by eugennicoara** [comment]
You might find [this](https://dev.to/thanhphuchuynh/customizing-error-messages-in-struct-validation-using-tags-in-go-4k0j) useful.

**Comment by aliml92** [comment]
In my echo app, I used the similar pattern:
```go
func BindAndValidate(c echo.Context, req interface{}) error {
	if err := c.Bind(req); err != nil {
		return err
	}

	if err := c.Validate(req); err != nil {
		
		if _, ok := err.(*validator.InvalidValidationError); ok {
			log.Error(err)
			return errors.New("Something went wrong. Please try again later.")
		}
		
		var verr validationErrors
		for _, err := range err.(validator.ValidationErrors) {
			var e error
			switch err.Tag() {
			case "required":
				e = fmt.Errorf("Field '%s' cannot be blank", err.Field())
			case "email":
				e = fmt.Errorf("Field '%s' must be a valid email address", err.Field())	
			case "eth_addr":
				e = fmt.Errorf("Field '%s' must a valid Ethereum address", err.Field())
			case "len":
				e = fmt.Errorf("Feild '%s' must be exactly %v character long", err.Field(), err.Param())
			default:
				e = fmt.Errorf("Field '%s': '%v' must satisfy '%s' '%v' criteria", err.Field(), err.Value(), err.Tag(), err.Param())
			}
			verr = append(verr, e)
		}

		return verr
	}

	return nil
}


type validationErrors []error

func (ve validationErrors) Error() string {

	buff := bytes.NewBufferString("")

	for i := 0; i < len(ve); i++ {

		buff.WriteString(ve[i].Error())
		buff.WriteString("\n")
	}

	return strings.TrimSpace(buff.String())
}
```

**Comment by bakbuz** [comment]
Thanks everybody

**Comment by chirag1807** [comment]
`
Validate = validator.New()
en := en.New()
uni := ut.New(en, en)
Translator, _ = uni.GetTranslator("en")

Validate.RegisterTranslation("min", Translator, func(ut ut.Translator) error {
	return ut.Add("min", "{0} must be at least {1} char long", true)
}, func(ut ut.Translator, fe validator.FieldError) string {
	t, _ := ut.T("min", fe.Field(), fe.Param())
	    return t
	}
)
`
Here is my code for custom message for min tag. Now, I want to define two other custom messages for the 'min' tag combined with 'number' and 'min' combined with 'alpha'. So, if any field of a struct has both 'min' and 'number' tags, then show the corresponding message. Similarly, if it has both 'min' and 'alpha' tags, then show the corresponding message.
How can I achieve this functionality?

Thanks in Advance.

**Comment by chirag1807** [comment]
func InitReqDataValidationTranslation() {
	Validate = validator.New()
	en := en.New()
	uni := ut.New(en, en)
	Translator, _ = uni.GetTranslator("en")

	Validate.RegisterTranslation("min", Translator, func(ut ut.Translator) error {
		return ut.Add("min", "{0} field must be at least {1} long.", true)
	}, func(ut ut.Translator, fe validator.FieldError) string {
		t, _ := ut.T("min", fe.Field(), fe.Param())
		return t
	})

}

Here is my code for custom message for min tag. 
Now, I want to define two other custom messages for the 'min' tag combined with 'number' and 'min' combined with 'alpha'. So, if any field of a struct has both 'min' and 'number' tags, then show the corresponding message. Similarly, if it has both 'min' and 'alpha' tags, then show the corresponding message.
How can I achieve this functionality?

Thanks in Advance.

**Comment by distinctdan** [comment]
This seems way harder than it should be. It covers the advanced translation case, but it doesn't provide an easy way to do the simple use case like most other validation libraries provide. This should be as simple as:
```golang
type MyStruct struct {
  Name   string      `validate:"required",validateMsg:"A name is required"`    
  ADate  civil.Date  `validate:"customCivilDate",validateMsg:"Must be in the format YYYY-MM-DD"`
}
```

My desired behavior is for `Validate` to generate all error messages with a single call, because if any extra parsing is required after the initial call, then that extra parsing and translation logic will be duplicated in every place that requires validation. It's good that validator allows custom error handling, but I would suggest that the default should be the most convenient case. For translation, this might look like passing the language code in the call like `err := Validate(myStruct, "en-US")` and it automatically localizes the strings, or it includes the translation as a separate property for each error.

**Comment by migueleliasweb** [comment]
It is puzzling how difficult this is by default. Really.

This is my attempt to make this a bit less painful.

This is an untested snippet of a translator that would read from the `msg` tag that can be added via a custom validator.

```go
enLocale := en.New()
translator, _ := ut.New(enLocale, enLocale).GetTranslator("en")

validate.RegisterTranslation("msg", translator,
  func(ut ut.Translator) error {
	  return ut.Add("msg", "{0}", true)
  },
  func(ut ut.Translator, fe validator.FieldError) string {
	  s, _ := ut.T("msg")
	  return s
  },
)
```

**Comment by orimdominic** [comment]
I wrote a gist for this. If you use it, you get an output in the format
```json
[
  {
    "field": "password",
    "message": "failed validation on `min` requirement. Expected min=6  but received paa"
  },
  {
    "field": "role",
    "message": "failed validation on `oneof` requirement. Expected oneof=client nutritionist instructor  but received hhh"
  }
]
```
You can find the gist at https://gist.github.com/orimdominic/50fea5dc126cd71bc7767e7570fb9e19

Please give it a star if you find it useful.
Thank you.
