### ISSUE TITLE
Support hostname:port validator

### ISSUE THREAD

**Issue by terala** [go-playground/validator#562]
**Package Version**: `v10` 
**Enhancement**: 
`hostname:port` is a very commonly used string field used for specifying network endpoints. Validator is needed to perform validation for this string field.

**Example**:
```go
type Host struct {
    Addr string `validate:"hostname_port"`
}
```

**Comment by psampaz** [comment]
#563 closes this one I think

**Comment by terala** [comment]
Support added with #563
