### ISSUE TITLE
Check that only one field among several is set

### ISSUE THREAD

**Issue by torkelrogstad** [go-playground/validator#566]
### Package version eg. v8, v9: 
v9

### Question:

Is it possible to validate that _only one_ field among a set of fields is set? 

### Code sample, to showcase or reproduce:

```go
type MyType struct {
  Foo int `validate:"???"`
  Bar int `validate:"???"`
}

// OK
MyType{
  Foo: 2
} 

// OK
MyType{
  Bar: 2
} 

// Not ok!
MyType{
  Foo: 2
  Bar: 2
} 
```

**Comment by deankarn** [comment]
Hey @torkelrogstad 

I don't think there is a current built in validation for this use case, however, you could use a struct level validation for this use case.

**Comment by jmvbxx** [comment]
@torkelrogstad Thank you for your question. Hopefully, Dean was able to help answer. We're going to close this issue but please feel free to follow up if you have any additional questions.
