### ISSUE TITLE
How to do a custom cross-field validation

### ISSUE THREAD

**Issue by hiro-o918** [go-playground/validator#567]
### Package version eg. v8, v9: 
v10
### Issue, Question or Enhancement:
I have a question to validate if some lists have the same length based on this package.
But I cannot find a way to do a custom cross-field validation, or does [this page](https://godoc.org/github.com/go-playground/validator#hdr-Cross_Field_Validation) mean that I have to implement some validating function independently?

### Code sample, to showcase or reproduce:

```go
type WeatherForecast struct {
	Days []int
	Weather []string
        Temperature []int
}
```
For example, is there a good way to validate if all the lengths of `Days`, `Weather` and `Temperature` have the same numbers?

Thank you.

**Comment by deankarn** [comment]
@hiro-o918 there are a couple of ways you can do your own cross-field validation:

1. Struct Level validation, see [here](https://github.com/go-playground/validator/blob/master/_examples/struct-level/main.go#L112) for an example. You can then program in your logic as usual.

2. Create a custom Field Level validation which checks the another field/array is of the same length, this can be done in a similar manner to the existing cross-field fictionality you linked above.

let me now if this helps 😄

**Comment by hiro-o918** [comment]
Thank you for responding!
It works!
Thank you!
