### ISSUE TITLE
Validate if all struct fields are zero

### ISSUE THREAD

**Issue by ivanovaleksey** [go-playground/validator#568]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
Hello, thanks for the library!
I wonder what is the best way to check if struct instance is empty, i.e. all it's fields have zero value.
The code below doesn't return any validation error.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"

	"github.com/go-playground/validator/v10"
	"github.com/go-playground/validator/v10/non-standard/validators"
)

type A struct {
	Field1 int
	Field2 string
}

type B struct {
	AField A `validate:"notblank"` // I also tried `required`
}

func main() {
	valide := validator.New()
	valide.RegisterValidation("notblank", validators.NotBlank)

	var b B
	err := valide.Struct(b)
	fmt.Println(err)
}
```

**Comment by hiro-o918** [comment]
You mean whether all the parameters of nested struct exists, don't you?
How about this as show [here](https://github.com/go-playground/validator/blob/master/_examples/struct-level/main.go)?

```go
type A struct {
	Field1 int    `validate:"required"`
	Field2 string `validate:"required"`
}

type B struct {
	AField A `validate:"required,dive"`
}
```

**Comment by jmvbxx** [comment]
@ivanovaleksey Thank you for your question. Looks like @hiro-o918 was able to help you out. We're going to go ahead and close this ticket but please feel free to reach out if you have any follow-ups.
