### ISSUE TITLE
How to validate required_with and numeric

### ISSUE THREAD

**Issue by loeffel-io** [go-playground/validator#570]
### Package version eg. v8, v9: 

v10

### Issue, Question or Enhancement:

How to validate `required_with` and `numeric`?
I can not use omitempty to disable the `numeric` rule, cause otherwise the `required_with` rule gets disabled.

### Code sample, to showcase or reproduce:

```go
type Foo struct {
	Model
	Amount   *string    `json:"amount" binding:"required_with=End,numeric,min=0"`
	End      *time.Time `json:"end"`
}
```

**Comment by loeffel-io** [comment]
@deankarn

**Comment by deankarn** [comment]
Hey @loeffel-io 

So your saying when **required_with** succeeds is the only time you want the **numeric** validation to run, have you tried the `or` syntax `|` eg. `json:"amount" binding:"required_with=End,len=0|numeric"`

Not ideal, but get's you what you want I think. Let me now if this helps/works 😄

**Comment by loeffel-io** [comment]
Thanks! Don’t know there is are or, i will try it soon
