### ISSUE TITLE
Empty String Validation Not Working

### ISSUE THREAD

**Issue by kartavya-ramnani** [go-playground/validator#580]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
Trying to do empty string validation, however it is not working.
using validate="required,min=1"

I am new to this library, apologies in advance if I am not using this properly.

### Code sample, to showcase or reproduce:

```go
import "github.com/go-playground/validator/v10"

type Category struct {
	Code        string `json:"code,omitempty",validate:"required,min=1"`
	Description string `json:"description,omitempty",validate:"required"`
}

func testValid(t *testing.T) {
valid := validator.New()
// Keeping Code as empty string
cat := Category{Description: "Test Description"}

err = valid.Struct(cat)
// getting err nil when I am expecting an error as Code is empty
if err == nil {
 t.Error("Expecting err not nil")
}
}
```
I know, we can use *string for optional string parameters but my philosophy does not align with that and I am of the opinion that your business logic should not be based around a string coming empty. 

Please help and suggest a way to not allow empty string.
Apologies as a novice validator user

Thanks in advance.

**Comment by psampaz** [comment]
Validation for required works fine. 

Check here https://play.golang.org/p/fhlBQ8ZQN2A

**Comment by kartavya-ramnani** [comment]
Will Check once and Close.

**Comment by kartavya-ramnani** [comment]
Working
Closing.
