### ISSUE TITLE
Contains or includes for slices and maps that ensures the keys contain one value

### ISSUE THREAD

**Issue by annaelizabeth2019** [go-playground/validator#586]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

I haven't found a way to validate that a map or slice contains (or includes) a value. If I use contains on a slice or map, it only checks that each value inside of it contains the substring. 

### Code sample, to showcase or reproduce:
So, I can do this and ensure that the keys are one of foo and bar and the values are one of 10, 100
```go
validate.Var(params, "max=1,dive,keys,oneof=foo bar,endkeys,dive,oneof=10 100,required")
```
I would like to be able to use a contains or includes tag like this:
```go
validate.Var(params, "max=1,dive,keys,oneof=foo bar,includes=foo,endkeys,dive,oneof=10 100,required")
```
This would ensure not only that the params are one of foo or bar, but also that they at least include foo (bar is optional).

**Comment by deankarn** [comment]
Hey @annaelizabeth2019 

I would recommend Creating a custom Field Level validation for you use case, an example can be found [here](https://github.com/go-playground/validator/blob/master/_examples/custom-validation/main.go#L37)

The validation you are attempting is getting complex enough to warrant a custom validation IMO.

let me know if this helps 😄
