### ISSUE TITLE
v10 doesn't work with $GOPATH

### ISSUE THREAD

**Issue by stanleynguyen** [go-playground/validator#590]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
I'm getting this error in GithubActions
![Screenshot 2020-03-06 at 12 46 32 PM](https://user-images.githubusercontent.com/12974927/76053546-880e3b80-5fa8-11ea-94e1-e1b5cfdf0b4d.png)

Seems that `locale` doesn't work with $GOPATH

### Code sample, to showcase or reproduce:
https://github.com/stanleynguyen/github-actions-golang

**Comment by deankarn** [comment]
No v10 doesn't work with `$GOPATH`, it's been updated to using go modules which is a breaking change, hence the version bump. see #565 for more details

**Comment by stanleynguyen** [comment]
Thanks @deankarn 👍
