### ISSUE TITLE
Is there a way of validating slice directly 

### ISSUE THREAD

**Issue by ticktap** [go-playground/validator#595]
### Question:
Hey. I trying to validate slice directly, but it show error: (nil []User). Is there a way of validating slice without struct outside.

### Code sample:

```go

type User struct {
    name string `json:"name" validate:"required"`
}

var params []User  
...
...
validate.Struct(params)
```

**Comment by deankarn** [comment]
@ticktap yes, please see the [docs](https://godoc.org/github.com/go-playground/validator) for more info but:

`validate.Var(params)`

**Comment by ticktap** [comment]
> @ticktap yes, please see the [docs](https://godoc.org/github.com/go-playground/validator) for more info but:
> 
> `validate.Var(params)`

validate.Var  validates a single variable. But I need to validate every field in slice. Did I miss something?

**Comment by deankarn** [comment]
Yep please look at the docs they have a lot of info :)

But if you validate with the “dive” tag it will dive down into the elements of the array like you want.

**Comment by ticktap** [comment]
@deankarn  It work, thank you!

**Comment by said-saifi** [comment]
Just so others can get the answer quickly.

```go
validate.Var(params, "dive")
```
