### ISSUE TITLE
is there any way to check when a field not exist,and then validate it?

### ISSUE THREAD

**Issue by thinkgos** [go-playground/validator#619]
### Issue, Question or Enhancement:

when Auto==true, it should  not validating IPAddress. 
when Auto==false, it should validating IPAddress. 

but Auto==true,it will check ipv4 tag. 
is ther any way, when auto==true, ignore ipv4 tag.
or required_without=Auto and then validating ipv4 tag 

### Code sample, to showcase or reproduce:

```go
type Config struct {
	Auto      bool   `json:"auto"`                                            // if true,not need check IPAddress.
	IPAddress string `json:"ipAddress" validate:"required_without=Auto,ipv4"`
}

func main() {
	cfg := Config{
		Auto:      true,
		IPAddress: "",
	}
	validate := validator.New()
	err := validate.Struct(&cfg)
	if err!= nil{
		panic(err)
	}
```

**Comment by deankarn** [comment]
Hey @thinkgos I don't think there is a built-in validation to do this unfortunately. However you can register a `Struct Level Validation` to handle this pretty easily.
