### ISSUE TITLE
How to require nil? 

### ISSUE THREAD

**Issue by loeffel-io** [go-playground/validator#622]
### Package version eg. v8, v9: 

v10

### Issue, Question or Enhancement:

How to require nil? For security reasons i want to make sure a field is **nil**

### Code sample, to showcase or reproduce:

```go
type Token struct {
	Token *string `gorm:"unique;not null" json:"token" binding:"required,len=32"`
	UserId *uint `gorm:"not null" json:"userId" binding:"MUST BE NIL"`
}
```

Thanks!

**Comment by 54853315** [comment]
Hi, You can try try  `default` ，like this :

``form:"field_name,default=0" binding:"required"``

**Comment by deankarn** [comment]
@loeffel-io Have you tried using the `isdefault` validation? since your field is a pointer the default is `nil` and so it should work for you.

**Comment by jmvbxx** [comment]
@loeffel-io Thank you for your question. Hopefully, you found the guidance useful. We're going to go ahead and close this issue but please feel free to ask any follow-up questions you might still have.
