### ISSUE TITLE
Oneof does not work

### ISSUE THREAD

**Issue by alexisvisco** [go-playground/validator#623]
### Package version eg. v8, v9: v9

Hi, there is a problem with oneof: it does not work at all. 

```
func TestT(t *testing.T) {
	a := struct {
		t string `validate:"oneof=red blue"`
	} {
		t: "...",
	}

	if err := validator.New().Struct(a); err != nil {
		log.Fatal(err)
	}
}
```

output:
```
=== RUN   TestFromStockV2State
--- PASS: TestFromStockV2State (0.00s)
PASS
```

It is clear that t is not one of red or blue. 

Thanks you for reading.

**Comment by deankarn** [comment]
@alexisvisco thanks for reporting, I’ll try and take a look this weekend.

Do you know if the same issue occurs for v10? I’m surprised this made it past the tests.

**Comment by alexisvisco** [comment]
With V10 it's the same result, honestly I was surprised too !

**Comment by nbfhscl** [comment]
change the first character of filed name to upper case and it will work fine

**Comment by deankarn** [comment]
Thanks @nbfhscl sharp eye

I didn’t see that, serves me right answering issues so late at night ;)

@alexisvisco thois packed can only validate exposed(public) types and t is private.
