### ISSUE TITLE
missing field key in error message when validate single field with tag

### ISSUE THREAD

**Issue by daydream123** [go-playground/validator#625]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
Issue

### Code sample, to showcase or reproduce:

```go
import (
	"fmt"
	"github.com/go-playground/validator"
)

type ReqBody struct {
	Username string `json:"username"`
}

func main() {
	reqBody := ReqBody{Username: "abcdefg"}

	v := validator.New()
	err := v.Var(reqBody.Username, "max=4")
	fmt.Println(err)
}
```

### the output error msg is below
```
Key: '' Error:Field validation for '' failed on the 'max' tag
```

I found when validate field with tag, the key name of err msg is missing

**Comment by deankarn** [comment]
@daydream123 sorry for the delay, but I know of no way to retrieve that info via reflection. If you find a way please let me know :)

**Comment by daydream123** [comment]
> @daydream123 sorry for the delay, but I know of no way to retrieve that info via reflection. If you find a way please let me know :)

yes, you're right, it also cannot be done in Java. in fact I known the name of  field when I try to validate it, so I returned the field name manually instead of retrieve from err field.

**Comment by bradleygore** [comment]
If you write a wrapper around the `validator.Var` func, you can easily enough use string replacement: https://play.golang.org/p/thdym3sUT8B

**Comment by 9tec7** [comment]
> @daydream123 sorry for the delay, but I know of no way to retrieve that info via reflection. If you find a way please let me know :)

I suggest adding another parameter to the Var func something like this.
```golang 
func (v *Validate) Var(fieldName string, field interface{}, tag string) error
``` 
so can place the Key/Field name into it and then the error need to read that parameter and return it
