### ISSUE TITLE
Checksum validation for Ethereum address

### ISSUE THREAD

**Issue by elias19r** [go-playground/validator#631]
### Package version eg. v8, v9:

v10

### Issue, Question, or Enhancement:

Enhancement

I was reading the codebase and I came across this comment from 2018-04-08:
https://github.com/go-playground/validator/blob/ea924ce89a4774b8017143b34b946db46add9df1/baked_in.go#L530

Following the link, I found out that it has been implemented since 2018-05-04: https://github.com/golang/crypto/pull/41#issuecomment-386774251

As it is now possible to implement the checksum validation for Ethereum address, I went ahead and implemented it: https://github.com/go-playground/validator/pull/630

Please let me know if I missed anything

**Comment by tremblaysimon** [comment]
Since merge of #630 I think we can close that issue.

**Comment by zemzale** [comment]
Okay, closing this as fixed.
