### ISSUE TITLE
v10 go-urn error

### ISSUE THREAD

**Issue by mistahj67** [go-playground/validator#638]
### Package version: v10
This was found using the gin-gonic package: v1.6.0+
https://github.com/gin-gonic/gin

### Issue, Question or Enhancement:
go: finding module for package github.com/leodido/go-urn
..\..\..\..\..\..\pkg\mod\github.com\go-playground\validator\v10@v10.2.0\baked_in.go:19:2: module github.com/leodido/go-urn@latest found (v1.2.0), but does not contain package github.com/leodido/go-urn

OS: Windows

### Code sample, to showcase or reproduce:

```go

```

**Comment by jmvbxx** [comment]
@mistahj67 Thank you for sharing this issue. I see you've created an issue with `gin-gonic`, as well, that has yet to be resolved. Have you been able to resolve this issue?

Given the age of this issue, I'm going to close it but please feel free to provide any follow-up information or questions here.
