### ISSUE TITLE
check time.Time in golang panic

### ISSUE THREAD

**Issue by Turing-Chu** [go-playground/validator#643]
### Package version eg. v8, v9: 

- go-playground/validator: V10 &V8
- gin version: v1.6.3
- validator in gin: v8
- go version: go version go1.14.4 linux/amd64
- OS: macOS Catalina 10.15.5 (19F101)

### Issue, Question or Enhancement:

I wanto pass a datetime from http post json data to gin web backend,
 
datetime format is `2006-01-02T15:04:05Z07:00`

but it Encountered an error, then I use validator/v10 to Adjustment my format. now I have no idea.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"github.com/go-playground/validator/v10"
	"time"
)

func main() {
	type User struct {
		RegisterTime time.Time `validate:"datetime=2006-01-02T15:04:05Z07:00"`
	}
	user := User{
		RegisterTime: time.Now(),
	}
	validate := validator.New()
	err := validate.Struct(user)
	fmt.Println(err)
}
```

### go code output & panic

```
/private/var/folders/yf/fl99q50s69748cpgv23kqc6r0000gn/T/___go_build__main_go_darwin #gosetup
panic: Bad field type time.Time

goroutine 1 [running]:
github.com/go-playground/validator/v10.isDatetime(0x11cc520, 0xc0001425a0, 0x0)
        /MY_GO_PATH/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/baked_in.go:2097 +0x1f6
github.com/go-playground/validator/v10.wrapFunc.func1(0x11cb4e0, 0xc000136008, 0x11cc520, 0xc0001425a0, 0x11928e0)
        /MY_GO_PATH/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/baked_in.go:36 +0x39
github.com/go-playground/validator/v10.(*validate).traverseField(0xc0001425a0, 0x11cb4e0, 0xc000136008, 0x116f2c0, 0xc0002e81a0, 0x99, 0x11928e0, 0xc0002e81a0, 0x99, 0xc0002d9000, ...)
        /MY_GO_PATH/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator.go:445 +0x576
github.com/go-playground/validator/v10.(*validate).validateStruct(0xc0001425a0, 0x11cb4e0, 0xc000136008, 0x116f2c0, 0xc0002e81a0, 0x99, 0x116f2c0, 0xc0002e81a0, 0x99, 0x11cd4a0, ...)
        /MY_GO_PATH/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator.go:77 +0x4d5
github.com/go-playground/validator/v10.(*Validate).StructCtx(0xc0001352c0, 0x11cb4e0, 0xc000136008, 0x116f2c0, 0xc0002e81a0, 0xc00029ff48, 0x10417ba)
        /MY_GO_PATH/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator_instance.go:304 +0x380
github.com/go-playground/validator/v10.(*Validate).Struct(...)
        /Users/Turing/Desktop/project/github/go/pkg/mod/github.com/go-playground/validator/v10@v10.3.0/validator_instance.go:277
main.main()
        /Hiddien-My-Real-Project-Directory/main.go:22 +0xd4
```

**Comment by elias19r** [comment]
Hi,

The `datetime=` tag should be used to validate a `string`

From `doc.go`:

> Datetime
> 
> This validates that a string value is a valid datetime based on the supplied datetime format.
> Supplied format must match the official Go time format layout as documented in > https://golang.org/pkg/time/
> 
>  Usage: datetime=2006-01-02

Working example: https://play.golang.org/p/Ic5R2U0Akf3

**Comment by Turing-Chu** [comment]
@elias19r 
thanks. So what I should do is using `string` represent a time field then converting to `time.Time` type by `time.Parse` function?

**Comment by elias19r** [comment]
Yes, that's correct

JSON has a limited number of supported types: String, Number (float64), Boolean, null, Array, Object (map/hash)

To pass a datetime via JSON, I'd choose String for ISO/RFC datetime formats (or Number for Unix timestamp), and then convert it to `time.Time` using `time.Parse()`

Example: https://play.golang.org/p/uNCtwisSrxE

**Comment by elias19r** [comment]
However, it seems `json.Unmarshal` alone works fine unmarshaling a datetime RFC 3339 string into a `time.Time` type: https://play.golang.org/p/sK5PYDp3vdx
So, you can also not use this validator package for that

**Comment by Turing-Chu** [comment]
thanks for your suggestions, I think I will use RFC 3339 format.
