### ISSUE TITLE
required can't validate space

### ISSUE THREAD

**Issue by ningye112** [go-playground/validator#648]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
If I have a string field with required tag, when the field is a or multi space e.g. " " or "                 " , the validator can't work.
I wonder how to realize validate the string that only with space.

My Engilish is poor, Can you understand my meaning?

### Code sample, to showcase or reproduce:

```go

```

**Comment by boolooper** [comment]
Felt the same. But my issue was solved by using [github.com/leebenson/conform](https://github.com/leebenson/conform)

I created a sub package in my project, then defined the function below. Then callled the function wherever I needed. At first I sanitized the struct with `conform` then pass it to `validator`for validation. 


```go
// Validate validates the given data.
func Validate(data interface{}) error {
	if err := conform.Strings(data); err != nil {
		return err
	}
	return validate.Struct(data)
}
```

Now all you have to do to trim spaces just add tags like

```go
type Person struct {
	FirstName string `conform:"name"`
	LastName  string `conform:"ucfirst,trim"`
	Email     string `conform:"email"`
	CamelCase string `conform:"camel"`
	UserName  string `conform:"snake"`
	Slug      string `conform:"slug"`
	Blurb     string `conform:"title"`
	Left      string `conform:"ltrim"`
	Right     string `conform:"rtrim"`
}
```

**Comment by deankarn** [comment]
I can also recommend this packages close relative https://github.com/go-playground/mold to do the same, although it could use some more built-in manipulations :)

**Comment by jmvbxx** [comment]
@ningye112 Thank you for your question. Were either of the two recommendations useful? For now we're going to go ahead and close out this issue but please feel free to follow-up with any questions or feedback.
