### ISSUE TITLE
Func never called for custom type

### ISSUE THREAD

**Issue by adrianlungu** [go-playground/validator#651]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

I have a custom type `type Days []int` which is inside another `type struct` in which I'm trying to run validation, but using something like `validate.RegisterCustomTypeFunc(validation.ValidateDaysType, Days{})` doesn't seem to work as `ValidateDaysType` is never called. 

Am I doing something wrong here ?

### Code sample, to showcase or reproduce:

```go

type Days []int

type Program struct {
   Name string
   Days Days `validate:"required, min=1, max=7, dive, min=1, max=7"`
}

func ValidateDaysType(v reflect.Value) interface{} {
	fmt.Println("this is never called", v)

	n, ok := v.Interface().(Days)
	if !ok {
		return nil
	}

	return []int(n)
}

```

**Comment by husniadil** [comment]
This is happening to me as well. Not working for slice maybe?

**Comment by smoyer64** [comment]
@husniadil For a custom type, you should be calling `RegisterCustomTypeFunc` instead.

**Comment by husniadil** [comment]
@smoyer64 got it, thanks!!

**Comment by deankarn** [comment]
@husniadil did this resolve his issue?

**Comment by husniadil** [comment]
@deankarn I decided to use `RegisterStructValidation` instead and it works.
