### ISSUE TITLE
question: tags

### ISSUE THREAD

**Issue by lucaNationwide** [go-playground/validator#656]
### Package version eg. v8, v9: 

v10

### Issue, Question or Enhancement:

hello, I am guessing if there is a predefined tag that allows validating that at least 1 of 2 or more fields it's not null

**Comment by deankarn** [comment]
@lucaNationwide can you please expand on what you mean by providing an example?

**Comment by jmvbxx** [comment]
@lucaNationwide Thank you for your original question. Given the lack of activity in this issue, we're going to go ahead and close it. However, please feel free to reach out and we'll happy to work with you to answer any questions.
