### ISSUE TITLE
How to not validate nested structs

### ISSUE THREAD

**Issue by j0hnwhyte** [go-playground/validator#670]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:

The documentation states:
```
 // Struct validates a structs exposed fields, and automatically validates nested structs, unless otherwise specified.
```

but it doesn't say anything about how to specify *not* to validate nested structs. I also checked example code and issues, there seems to be nothing mentioning it.

Any idea? Thanks

**Comment by deankarn** [comment]
@j0hnwhyte you can ignore traversing nested structs by using `validate:"-"`

**Comment by j0hnwhyte** [comment]
Thanks 👍
