### ISSUE TITLE
FieldError.Field() returning wrong result with gin

### ISSUE THREAD

**Issue by kristijorgji** [go-playground/validator#681]
### Package version eg. v9, v10: 
github.com/go-playground/validator/v10 v10.4.1

### Issue, Question or Enhancement:

The function .Field() of fieldError is supposted to return back the name that we specified in the json tag of the struct, instead it is returning the structure name!!!

The structure is

```go
type createObjectRequest struct {
	Name json.RawMessage `json:"name" binding:"required"`
	Dandy json.RawMessage `json:"dandy" binding:"required"`
}

```

After making one request and those fields missing, gin returns the proper validation error and by calling in the validation field error Field method returns `Name` And `Dandy`, instead of `name` and `dandy` (the json tagged names)

The gin handler for reference:

```go
func (server *Server) createExercise(ctx *gin.Context) {
	var req createObjectRequest
	if err := ctx.ShouldBindJSON(&req); err != nil {
		ctx.JSON(http.StatusBadRequest, errorResponse(err))
		return
	}
}
```

That is attached to one test endpoint `POST /objects`, making one request with empty body should give back the validation errors, which is just one array of FieldError

The problem is that I want to get back the json tagged names, and not the structure names as I am building one map of the error names and messages like

```go
var errors = gin.H{}
	for _, fe := range ve {
		errors[fe.Field()] = fe.Error()
	}
```

By debugging the issue it brings me to this code of your codes:
`/go/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/errors.go:126`

```go
	// returns the fields name with the tag name taking precedence over the
	// field's actual name.
	//
	// eq. JSON name "fname"
	// see StructField for comparison
	Field() string
```

The above is not working as expected. It returns the structure field name and not the name we specify in json tag
The call investigating further goes inside the below method

`/go/pkg/mod/github.com/go-playground/validator/v10@v10.4.1/errors.go:209`
```go
// Field returns the field's name with the tag name taking precedence over the
// field's actual name.
func (fe *fieldError) Field() string {

	return fe.ns[len(fe.ns)-int(fe.fieldLen):]
	// // return fe.field
	// fld := fe.ns[len(fe.ns)-int(fe.fieldLen):]

	// log.Println("FLD:", fld)

	// if len(fld) > 0 && fld[:1] == "." {
	// 	return fld[1:]
	// }

	// return fld
}

```

**Comment by deankarn** [comment]
@kristijorgji The documentation appears to be incorrect.

First you must register a custom [TagNameFunc](https://pkg.go.dev/github.com/go-playground/validator/v10#Validate.RegisterTagNameFunc) in order to get anything besides the struct name and then this function will return that.

To gt this to work in gin it's likely you'll have to register the validator manually for Gin because of the way it's wired up in the backend, but here is an example for v8->v9 which still applies to v10 https://github.com/go-playground/validator/tree/master/_examples/gin-upgrading-overriding

**Comment by deankarn** [comment]
I could use some help updating the documentation

**Comment by deankarn** [comment]
closing due to no response
