### ISSUE TITLE
0 should also be a numeric and a number

### ISSUE THREAD

**Issue by jarnix** [go-playground/validator#691]
### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

Issue

### Code sample, to showcase or reproduce:

```go
type Item struct {
	SomeNumber int `json:"someNumber" validate:"required,numeric"`

```

When the field equals 0, the validator says that the value is incorrect. 0 is a number

**Comment by deankarn** [comment]
@jarnix I think that if you take a closer look at the error message you’ll see it is not failing on the numeric validation, but the required which is correct.

**Comment by jarnix** [comment]
Hi @deankarn 

I understand. So 0 is not a value at all ? :-) 

What should I use if I want to allow 0 but require that the value is set? 

Thx

**Comment by deankarn** [comment]
@jarnix if zero is a valid value then I’d drop the required, but if you need to know if it’s been set then change the int to a pointer *int

**Comment by jarnix** [comment]
ok, will do. Thanks !
