### ISSUE TITLE
There is no "exists" tag anymore and we can not use "required" tag with zero-value

### ISSUE THREAD

**Issue by mohsenasm** [go-playground/validator#692]
Hi, 

We have upgraded from version 8 to version 10 recently.
It seems that there is no `exists` tag anymore and we should use `required` instead. But as states in [this issue](https://github.com/gin-gonic/gin/issues/491), there is a problem with the `required` tag that it doesn't allow zero-value.

What do you suggest?

**Comment by frederikhors** [comment]
@mohsenasm can this help you? https://github.com/go-playground/validator/issues/691

**Comment by mohsenasm** [comment]
Thanks. It's now clear.
So we should use `*int` if we want to allow zero-value.

```go
type User struct {
	Age *int `validate:"required"`
}

age := 0
user := &User{Age: &age}
err := validate.Struct(user) // err == nil

user2 := &User{Age: nil}
err2 := validate.Struct(user2) // err != nil
```

```go
type User struct {
	Age int `validate:"required"`
}

age := 0
user := &User{Age: age}
err := validate.Struct(user) // err != nil
```
