### ISSUE TITLE
An error as a map instead of a string and jsonified keys

### ISSUE THREAD

**Issue by dmytrostriletskyi** [go-playground/validator#695]
### Package version

I use the following version — `10`.

### Issue, Question or Enhancement:

I have a struct with common validation and after I validated incoming arguments (example below), I receive a `string` in an error's string value:

```bash
$ curl ... -d '{
    "id": 10,
    "email": "esdfsdsdfmail",
    "name": "Dmytro sdfsdfjhgfdgh",
    "is_active": true
  }' | python -m json.tool
{
    "error": "Key: 'User.ID' Error:Field validation for 'ID' failed on the 'required' tag\nKey: 'User.Email' Error:Field validation for 'Email' failed on the 'required' tag\nKey: 'User.Name' Error:Field validation for 'Name' failed on the 'required' tag\nKey: 'User.IsActive' Error:Field validation for 'IsActive' failed on the 'required' tag"
}
```

There are the following string joined with `\n`:

```text
Key: User.ID' Error:Field validation for 'ID' failed on the 'required' tag
Key: 'User.Email' Error:Field validation for 'Email' failed on the 'required' tag
Key: 'User.Name' Error:Field validation for 'Name' failed on the 'required' tag
Key: 'User.IsActive' Error:Field validation for 'IsActive' failed on the 'required' tag"
```

I want something user-oriented here based on `JSON` they send:

```bash
$ curl ... -d '{
    "id": 1,
    "email": "dmytro.striletskyi@gmail.com",
    "name": "Dmytro Striletskyi",
    "is_active": true
  }' | python -m json.tool
{
    "errors": {
        "id": "User.ID' Error:Field validation for 'ID' failed on the 'required' tag",
        "email": "User.Email' Error:Field validation for 'Email' failed on the 'required' tag",
        ...
        "is_active": "User.IsActive' Error:Field validation for 'IsActive' failed on the 'required' tag"
    }
}
```

So, basically:

1. It should be a map.
2. The map's key is a `jsonified` name of a struct field (IsActive -> is_active).

Is it possible with built-in functionality or any known extension/library? It's possible to do on my own, but it will take a while to create a few algorithms for parsing/converting things.

### Code sample

```go
validate = validator.New()
err := validate.Struct(requestAdminUser)
if err != nil {
    fmt.Println(err.Error())
}
```

Thanks in advance! :)

**Comment by deankarn** [comment]
The current output of the program is purposefully not opinionated about the output for the callers use case. 

The errors returned however have all of the functionality and infomation you need at your disposal to create your desired output, please see the simple example [here](https://github.com/go-playground/validator/blob/master/_examples/simple/main.go#L69-L79)
