### ISSUE TITLE
Field with create only behavior

### ISSUE THREAD

**Issue by ydhnwb** [go-playground/validator#696]
I've been using this validator to validate my user input from client. But I get confused how to make a field only required when POST / create only?

### Here is my model

```go
type User struct {
	ID       uint64 `gorm:"primary_key:auto_increment" json:"id"`
	Fullname string `gorm:"type:varchar(255)" json:"fullname" binding:"required"`
	Email    string `gorm:"uniqueIndex;type:varchar(255)" json:"email" binding:"required,email"`
	Password string `gorm:"->;<-:create;not null" json:"password,omitempty" binding:"required"`
	Token    string `gorm:"-" binding:"-" json:"token,omitempty"`
}
```

I want **password field** to be required when **POST** only in api/auth/register url. But, when user wants to update their profile via **PUT** api/user/profile, the **password field** is optional. Is that possible without creating other struct model?

**Comment by deankarn** [comment]
There are several options:
- Use a separate struct per endpoint.
- Use multiple validators that operate on different tag keys eg. `binding` & `validate`
- Create a custom validation that can accept data through the `context.Context` with value that could indicate to skip the validation, such as the HTTP method.

**Comment by chrisk314** [comment]
I also hit this issue recently with some fields required only on creation but not on update. I solved it using the second approach mentioned above: using a second validator which targets a different tag name. The key is using `validator.SetTagName` on the second validator. Here's a basic example.

```go
// CustomValidator handles validation of inbound structs in controller layer.
type CustomValidator struct {
	validator         *validator.Validate
	validatorOnCreate *validator.Validate
}

// Validate handles validation of structs in controller later.
func (cv *CustomValidator) Validate(i interface{}) (err error) {
	if err = cv.validator.Struct(i); err != nil {
		return err
	}
	return nil
}

// ValidateOnCreate handles validation of structs on creation in controller later.
func (cv *CustomValidator) ValidateOnCreate(i interface{}) (err error) {
	// TODO : Unify validation errors into single returned error with all validation errors.
	if err = cv.validatorOnCreate.Struct(i); err != nil {
		return err
	}
	if err = cv.Validate(i); err != nil {
		return err
	}
	return nil
}

var customValidator *CustomValidator

// InitValidators initialises validators
func InitValidators() {
	customValidator = &CustomValidator{
		validator:         validator.New(),
		validatorOnCreate: validator.New(),
	}
	customValidator.validator.SetTagName("validate")
	customValidator.validatorOnCreate.SetTagName("validate-req")
}
```

A simple struct using these validators

```go
type User struct {
    ID int `json:"id"`
    Name *string `json:"name" validate-req:"required" validate:"omitempty,min=1,alpha"`
    Password *string `json:"password" validate-req:"required" validate:"omitempty,min=8"`
}
```

Now `User` can be used for both create and update. Validated fields are pointers to easily check which fields have been submitted on update. This means that when specifying validations with `validate` (create & update) validator, `omitempty` must always be used first, otherwise the additional validations fail on fields which are not submitted on update. Also, be aware that because `Name` and `Password` are pointer types zero values for the referred to type (i.e. `""`) will pass through the validator as they are not the zero value for the pointer type (i.e. `nil`); hence using `min=X`.

There may be a cleaner/better way to achieve this but this is working for me.

@deankarn I had to do some digging to figure out how to set up different validators targetting different tags. Could be helpful to make this capability more obvious in the docs. Thanks a lot for your efforts by the way, I really like validator :-)

**Comment by th0th** [comment]
> I also hit this issue recently with some fields required only on creation but not on update. I solved it using the second approach mentioned above: using a second validator which targets a different tag name. The key is using `validator.SetTagName` on the second validator. Here's a basic example.
> 
> ```go
> // CustomValidator handles validation of inbound structs in controller layer.
> type CustomValidator struct {
> 	validator         *validator.Validate
> 	validatorOnCreate *validator.Validate
> }
> 
> // Validate handles validation of structs in controller later.
> func (cv *CustomValidator) Validate(i interface{}) (err error) {
> 	if err = cv.validator.Struct(i); err != nil {
> 		return err
> 	}
> 	return nil
> }
> 
> // ValidateOnCreate handles validation of structs on creation in controller later.
> func (cv *CustomValidator) ValidateOnCreate(i interface{}) (err error) {
> 	// TODO : Unify validation errors into single returned error with all validation errors.
> 	if err = cv.validatorOnCreate.Struct(i); err != nil {
> 		return err
> 	}
> 	if err = cv.Validate(i); err != nil {
> 		return err
> 	}
> 	return nil
> }
> 
> var customValidator *CustomValidator
> 
> // InitValidators initialises validators
> func InitValidators() {
> 	customValidator = &CustomValidator{
> 		validator:         validator.New(),
> 		validatorOnCreate: validator.New(),
> 	}
> 	customValidator.validator.SetTagName("validate")
> 	customValidator.validatorOnCreate.SetTagName("validate-req")
> }
> ```
> 
> A simple struct using these validators
> 
> ```go
> type User struct {
>     ID int `json:"id"`
>     Name *string `json:"name" validate-req:"required" validate:"omitempty,min=1,alpha"`
>     Password *string `json:"password" validate-req:"required" validate:"omitempty,min=8"`
> }
> ```
> 
> Now `User` can be used for both create and update. Validated fields are pointers to easily check which fields have been submitted on update. This means that when specifying validations with `validate` (create & update) validator, `omitempty` must always be used first, otherwise the additional validations fail on fields which are not submitted on update. Also, be aware that because `Name` and `Password` are pointer types zero values for the referred to type (i.e. `""`) will pass through the validator as they are not the zero value for the pointer type (i.e. `nil`); hence using `min=X`.
> 
> There may be a cleaner/better way to achieve this but this is working for me.
> 
> @deankarn I had to do some digging to figure out how to set up different validators targetting different tags. Could be helpful to make this capability more obvious in the docs. Thanks a lot for your efforts by the way, I really like validator :-)

Thanks for the explanation and the example @chrisk314 . However, I couldn't manage to register the same translation for these two `validate`s. Did you have any luck with it?

Here is my example:

```go
package validator

import (
	"fmt"
	localesEn "github.com/go-playground/locales/en"
	"github.com/go-playground/universal-translator"
	"github.com/go-playground/validator/v10"
	translationsEn "github.com/go-playground/validator/v10/translations/en"
	"reflect"
)

var (
	translator          ut.Translator
	universalTranslator *ut.UniversalTranslator
	validate            *validator.Validate
	validateOnCreate    *validator.Validate
)

func mapError(s interface{}, err error) *map[string]interface{} {
	if err == nil {
		return nil
	}

	r := map[string]interface{}{}

	for _, e := range err.(validator.ValidationErrors) {
		field, ok := reflect.TypeOf(s).FieldByName(e.Field())

		if !ok {
			panic("Field not found.")
		}

		r[field.Tag.Get("json")] = fmt.Sprintf("%s.", e.Translate(translator))
	}

	return &r
}

func Init() {
	en := localesEn.New()
	universalTranslator = ut.New(en, en)

	trans, _ := universalTranslator.GetTranslator("en")

	translator = trans

	validate = validator.New()
	validateOnCreate = validator.New()

	validateOnCreate.SetTagName("validateOnCreate")

	translationsEn.RegisterDefaultTranslations(validate, trans)
	translationsEn.RegisterDefaultTranslations(validateOnCreate, trans)
}

func Validate(s interface{}) *map[string]interface{} {
	err := validate.Struct(s)

	return mapError(s, err)
}

func ValidateOnCreate(s interface{}) *map[string]interface{} {
	err := validateOnCreate.Struct(s)

	return mapError(s, err)
}
```

**Comment by chrisk314** [comment]
@th0th I haven't run into this myself as I'm not using translators in my project. I've only used `validator` a bit so I don't know how the internals work. No obvious problems jump out at me in your example. I would suggest opening a new issue specifically related to the use of translators with multiple validators. Hopefully someone more knowledgable can help you.

**Comment by th0th** [comment]
Thanks @chrisk314 💐
