### ISSUE TITLE
Translation for Other tags? Eg: required_without?

### ISSUE THREAD

**Issue by frederikhors** [go-playground/validator#697]
### Issue, Question or Enhancement:

Am I wrong or there is no translation for the `required`s other than for the default one?

Example: is there a translation for `required_without`?

**Comment by deankarn** [comment]
It is possible this has been missed.

If so happy to accept PR's to correct.

**Comment by renato0307** [comment]
@deankarn I'm new to the repo but I can pick this one. 

I've create a draft PR with the `en` translation for `required_if`. 

Is this the right approach?

Cheers,
Renato
