### ISSUE TITLE
Omitempty on a *string field does not work

### ISSUE THREAD

**Issue by frederikhors** [go-playground/validator#698]
This is a simple example I cannot make it work and I don't know why!

All what I need is to `omit` validation (`min=10`) when `Name` is `empty`.

Why isn't it working? Where am I wrong? Maybe because it's a pointer to string?

### Reproduction
https://play.golang.org/p/LZWMVjVERYk

### Code sample

```go
package main

import (
	"log"

	"github.com/go-playground/validator/v10"
)

type SampleWithPointer struct {
	Name *string `validate:"omitempty,min=10"`
}

func main() {
	name := ""

	swp := &SampleWithPointer{Name: &name}

	validate := validator.New()

	if err := validate.Struct(swp); err != nil {
		log.Printf("Validate SampeWithPointer with error, %v", err)
	}
}
```

### Error

`Validate SampeWithPointer with error, Key: 'SampleWithPointer.Name' Error:Field validation for 'Name' failed on the 'min' tag`

**Comment by frederikhors** [comment]
I think the only thing wrong is me!

The `omitempty` for `*string` is `nil`.

Am I right?

**Comment by deankarn** [comment]
That is correct @frederikhors this would work as you with with nil.
