### ISSUE TITLE
how required_if with pointer ?

### ISSUE THREAD

**Issue by qyu37** [go-playground/validator#699]
i want only when A field bool is true, B field required work.

but now i can not work for this code. how can i solve it. thanks~

```
package main

import (
	"log"

	"github.com/go-playground/validator/v10"
)

type Hello struct {
	A      *bool     `validate:"required"`
	B      string     `validate:"required_if=A true"`
}

func main() {
	world := &Hello{
		A: func(x bool) *bool { return &x}(true),
	}

	validate := validator.New()
	err := validate.Struct(world)
	log.Println(err)
}

```

**Comment by deankarn** [comment]
For this you'd have to:
- Use a Struct Level validation.
- Crete a custom validation.

**Comment by jmvbxx** [comment]
@qyu37 Thank you for the question. Was Dean's comment helpful? For now, we're going to close this issue but please feel free to submit a follow-up question.
