### ISSUE TITLE
How to validate `bool` #142 (reopen)

### ISSUE THREAD

**Issue by thalesfsp** [go-playground/validator#714]
### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Problem still exist. How to fix?

### Code sample, to showcase or reproduce:
See #142

**Comment by loeffel-io** [comment]
+1

**Comment by loeffel-io** [comment]
@deankarn ✌️

**Comment by deankarn** [comment]
Hey @loeffel-io I'm not sure why we've reopened, this has been asked many times in other issues.

TL;DR `required` checks if the field is its default value NOT if it exists, if you need an existence check the data type itself will need to be nullable, in this case tai-state, but bool by itself only has 2 states.

Please see https://github.com/go-playground/validator/issues/319

P.S. would love some help documenting this somewhere as it tends to keep coming up.
