### ISSUE TITLE
How to use startswith with Field value?

### ISSUE THREAD

**Issue by aigoya** [go-playground/validator#720]
### Issue, Question or Enhancement:
startswith, endswith, startsnotwith, endsnotwith is a cool validator.
Is it posible to use startswith a value with a Field?

**Example**
I have 2 fields Province and District and I want to validate startswith=Province
01 Province1 {0101 District1, 0102 District2}
02 Province2 {0201 District3, 0202 District4}

### Code sample, to showcase or reproduce:

```go
type MyStruct struct {
	Province    string  `validate:"len=2"`
	District    string  `validate:"len=4, startswith=Province"`
}
```

**Comment by fdmsantos** [comment]
Your Code Should Work. Works For me.

**Comment by jmvbxx** [comment]
@aigoya Thank you for your question. Hopefully, you were able to resolve your issue. We're going to go ahead and close this issue. Please feel free to submit a follow-up question or share any doubts you may have.
