### ISSUE TITLE
Erroneous url_encoded validation

### ISSUE THREAD

**Issue by psankar** [go-playground/validator#723]
### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Issue

### Code sample, to showcase or reproduce:

```go
	createOrganization := CreateOrganization{Organization: "hello"}
	err := validator.New().Struct(&createOrganization)
	if err != nil {
		var validationErrors validator.ValidationErrors
		var ok bool
		if validationErrors, ok = err.(validator.ValidationErrors); !ok {
			fmt.Println("non validation er")
			return
		}

		fmt.Printf("%v", validationErrors)
	} else {
		fmt.Printf("No validation error")
	}
```
Playground URL: https://play.golang.org/p/-awW91lwR-v 

If I use just english text, the above program should pass but it seem to fail. If I use an online url encoder program to encode an english text, I get the same input english text as the output. So the string `hello` should be considered as a valid url_encoded text.

However, if I use something else like `Hello+G%C3%BCnter` for the `Organization`, then the program works fine.

**Comment by drachs** [comment]
I agree, this seems like a bug.  I came here today to ask about this, guess I won't be using this validator.

**Comment by deankarn** [comment]
Thanks @psankar for reporting the validation is clearly not working as intended.

I will try to look at it as soon as I can but PR's to fix are also welcome.
