### ISSUE TITLE
get tag name out of the error message

### ISSUE THREAD

**Issue by 9tec7** [go-playground/validator#728]
### Question :

is there any way to know which tag failed in validation from `Var()` function?

i only need to get the Tag name from the error. 
something like `e.Tag()` and then return me the `max` tag only

### Code sample, to showcase or reproduce:

```go
e := val.Var(d.LastName, "required,max=20,alphanumSpace");
// returns
// => Key: '' Error:Field validation for '' failed on the 'max' tag string
                                                          ^^^^^--------------------- i need only this
```

**Comment by deankarn** [comment]
yes @9tec7 see here https://github.com/go-playground/validator/blob/master/_examples/simple/main.go#L73

please try to look at the examples and docs before reporting an issue :)

**Comment by 9tec7** [comment]
My bad, i was trying to look for something like `e.(validator.ValidationErrors).Tag()` which I thought no need to go for the loop for each of variable validation. :)
