### ISSUE TITLE
Validation with pointers returns unexpected results

### ISSUE THREAD

**Issue by adenix** [go-playground/validator#760]
### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Issue (but maybe its a question)

I am attempting to add validation to structures that have a lot of business rules (industry specification driven). My structures are using pointers to children structures. This seems to break validation. I've put together a demo repository (linked below). There are two mostly identical structures where the only difference is pointers. Unit tests included.

### Code sample, to showcase or reproduce:
[https://github.com/adenix/bug-go-validator](https://github.com/adenix/bug-go-validator)

**Comment by deankarn** [comment]
I think you need to be more specific about what you think is not working, your example is does not specify and has many variables.

**Comment by adenix** [comment]
Hi @deankarn 

When running the unit tests, the validation tags in nested structures are not causing the validation to fail when they data violates the defined rules. The exact structures and tests without the pointers pass validate as expected.

The tests show these validators not erroring for the cases supplied in `/fixtures/mock/family`
https://github.com/adenix/bug-go-validator/blob/main/bug/family.go#L4
https://github.com/adenix/bug-go-validator/blob/main/bug/family.go#L11
https://github.com/adenix/bug-go-validator/blob/main/bug/family.go#L24
https://github.com/adenix/bug-go-validator/blob/main/bug/family.go#L30

```
$ make test
--- FAIL: TestBug_Invalid (0.00s)
    --- FAIL: TestBug_Invalid/invalid.mom.contact.email.json (0.00s)
        family_test.go:26: POINTER TEST: error was expected but not encountered
    --- FAIL: TestBug_Invalid/missing.mom.age.json (0.00s)
        family_test.go:26: POINTER TEST: error was expected but not encountered
    --- FAIL: TestBug_Invalid/missing.mom.json (0.00s)
        family_test.go:26: POINTER TEST: error was expected but not encountered
    --- FAIL: TestBug_Invalid/missing.mom.name.first.json (0.00s)
        family_test.go:26: POINTER TEST: error was expected but not encountered
    --- FAIL: TestBug_Invalid/missingdogs.name.first.json (0.00s)
        family_test.go:26: POINTER TEST: error was expected but not encountered
FAIL
FAIL	github.com/adenix/bug-go-validator/bug	0.138s
?   	github.com/adenix/bug-go-validator/internal/validate	[no test files]
ok  	github.com/adenix/bug-go-validator/works	(cached)
FAIL
make: *** [test] Error 1
```

**Comment by deankarn** [comment]
Hey @adenix,

I created a PR to demonstrate the fixes to your tests [here](https://github.com/adenix/bug-go-validator/pull/1). This appears to be a simple error using pointers and the same struct for all tests.

Please let me know if this explains the issue enough.

**Comment by adenix** [comment]
Ah, I completely missed that dive had to be explicit added. I see it now in the go.dev docs with a find in page. Thank you for the unmarshal callout, rookie mistake!
