### ISSUE TITLE
ISO 4217 Currency Code Validation

### ISSUE THREAD

**Issue by metinogurlu** [go-playground/validator#772]
### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

Question/Enhancement

Is there any support to validate ISO 4217 currency codes, any plan on roadmap or is pr welcomed?

**Comment by deankarn** [comment]
PR is welcome

**Comment by metinogurlu** [comment]
Opened! https://github.com/go-playground/validator/pull/811
