### ISSUE TITLE
[Bug] `file` validator fails if string is a valid filepath but does not exist

### ISSUE THREAD

**Issue by johnnybubonic** [go-playground/validator#808]
- [X] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [X] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Because the isFile() uses `os.Stat`, it will completely fail if the filepath given does not (yet) exist on the system performing validation.

I have not tested, but I presume the `dir` validator suffers the same issue.

This can result in two very obvious failure conditions:

* If the system validating the data is not the system intending to *have* the file, it will fail.
* If the system validating the data is *going to* have a file created there but it does not yet exist, it will fail. (Think in terms of e.g. validating a configuration file's content, for instance.)

### Code sample, to showcase or reproduce:
Assuming you don't have file `/foobarbaz`:

```go
package main

import (
	"fmt"

	"github.com/go-playground/validator/v10"
)

type ExampleFile struct {
	Path string `validate:"required,file"`
}

var validate *validator.Validate

func main() {

	var ef = ExampleFile{Path:"/foobarbaz"}
	var err error

	validate = validator.New()

	err = validate.Struct(ef)

	fmt.Println(err)
}
```
Per the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/), there are some [useful hints](https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/utilities/pathchk.html).

### Suggested Remediation

I'd like to propose instead using the regex pattern:

```
\([^\0 !$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+
```

(per [here](https://stackoverflow.com/a/10047501/733214)). It seems to most closely match the POSIX spec.

Windows may require a separate pattern:

```
(^([a-z]|[A-Z]):(?=\\(?![\0-\37<>:"/\\|?*])|\/(?![\0-\37<>:"/\\|?*])|$)|^\\(?=[\\\/][^\0-\37<>:"/\\|?*]+)|^(?=(\\|\/)$)|^\.(?=(\\|\/)$)|^\.\.(?=(\\|\/)$)|^(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+))((\\|\/)[^\0-\37<>:"/\\|?*]+|(\\|\/)$)*()$
```
(per [here](https://stackoverflow.com/a/42036026/733214)).

Obviously since they both include e.g. null byte characters, a string literal will not be usable so they'll probably need some escaping.

**Comment by johnnybubonic** [comment]
Actually, on second thought, it may make more sense to perform this logic:

IF:
* The path currently exists
** Then VALID.
* The path does not exist
** Attempt to create the file (deleting when done). Something as simple as writing an empty (not nil) byte slice to the path or something with `iotuil.WriteFile` should do.
*** IF:
**** A permission error (`fs.PathError{Err:0xd}`), or directory does not exist (`fs.PathError{Err:0x2}`) - probably a few others - occurs:
***** Then VALID (the error can be safely ignored)
**** An error `fs.PathError{Err:0x16}` is returned
***** The filepath is INVALID.

**Comment by johnnybubonic** [comment]
(Note that this still suffers from the issue of if e.g, the validating machine is different from the machine the path is intended for, e.g. the validator is Linux and the target machine is Windows. But it's a **lot** better than before since, you know, it doesn't require the file to exist first.)

**Comment by TheBeachMaster** [comment]
Interesting, mine is kind of opposite. Not sure whether I should create another issue or add to this one.

In my case, the file is exists but validator does not see it.
```golang
// ..
PhotoURL          string `form:"photo" validate:"file"`
// ..
```
Example output:
Validator: <- Does not see file
```json
{
  "error": true,
  "messsage": [
    {
      "FailedField": "CreateUser.PhotoURL",
      "Tag": "file",
      "Value": ""
    }
  ]
}
```
API: <- Sees file
```bash
time="2021-07-30T18:04:49+03:00" level=info msg="File URI: stefan-stefancik--g7axSVst6Y-unsplash.jpg"
```

**Comment by johnnybubonic** [comment]
@TheBeachMaster I'd definitely open another issue, but based on `message[0].Value`, it seems the struct field isn't properly being populated by your API. `file` implicates `required`, so since it's essentially an empty string, ...

**Comment by roelarents** [comment]
A note on
> the validating machine is different from the machine the path is intended for

Even if the OS is the same, I cannot use this validation reliably now on a different machine. Because if the dir exists but it is a file (or vice versa), it fails. While it might still be a valid path syntax-wise.

**Comment by nf-brentsaner** [comment]
This would be expected, I'd imagine. Use `validate=filepath|dirpath` if you just want a valid path.
