### ISSUE TITLE
How to validate a struct field, only if it has content?

### ISSUE THREAD

**Issue by thalesfsp** [go-playground/validator#834]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Code sample, to showcase or reproduce:

```go
type X struct {
    Code int `json:"code"`
    Message string `json:"message" validate:"gte=3"`
}
```

I would like `Message` to only be validated (`gte=3`) if it isn't the zero value. Is is possible?

**Comment by filikos** [comment]
You can add the `omitempty` tag so the go zero value if `Message` was not set will be ignored. https://play.golang.org/p/yMY_JKY8Q2K

**Comment by thalesfsp** [comment]
U saved me :) Tkx!
