### ISSUE TITLE
omitempty combined with other validators doesn't work with pointer

### ISSUE THREAD

**Issue by bencrouse** [go-playground/validator#849]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:

When combining an `omitempty` with another validator (I've tried `len` and `email`), `omitempty` doesn't stop the next validator from running if the struct field is a pointer. It works as expected if the field isn't a pointer.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	validator "github.com/go-playground/validator/v10"
)

type Test struct {
	String  string  `validate:"omitempty,len=5"`
	Pointer *string `validate:"omitempty,len=5"`
}

func main() {
	v := validator.New()
	emptyString := ""

	fmt.Println(v.Struct(&Test{String: emptyString}))   // Success
	fmt.Println(v.Struct(&Test{Pointer: &emptyString})) // Fail
}
```

Demo available here: https://play.golang.org/p/IxzauZtis11

**Comment by deankarn** [comment]
omitempty should be clearly documented.

I think perhaps the confusion is that you were thinking a pointer doesn’t have a value, but it does as nil is a value in Go. There is no such thing as an uninitialized value in Go like there can be in C.
