### ISSUE TITLE
How can I validate a field with type *big.Int?

### ISSUE THREAD

**Issue by petrovi4ev** [go-playground/validator#852]
* [x]  I have looked at the documentation here first?
* [x]  I have looked at the examples provided that may showcase my question here?

### Package version eg. v9, v10: 

 v10

### Issue, Question or Enhancement:

How can I validate a field with type *big.Int?

### Code sample, to showcase or reproduce:

this code not work, what am I doing wrong?

```go
type Settings struct {
	Target       *big.Int `validate:"gte=1"`
}

func main() {
        s := Settings{Target: big.NewInt(0)}
        
        validate := validator.New()
	validate.RegisterCustomTypeFunc(ValidateValuer, &big.Int{})

	err := validate.Struct(s)
	fmt.Printf("%+v", err)
}

// ValidateValuer implements validator.CustomTypeFunc
func ValidateValuer(field reflect.Value) interface{} {
	n, ok := field.Interface().(*big.Int)
	if !ok {
		return nil
	}

	return n.Int64()
}
```

**Comment by fairyhunter13** [comment]
@petrovi4ev How about trying it like this?
```go
type Settings struct {
	Target       *big.Int `validate:"gte=1"`
}

func main() {
        s := Settings{Target: big.NewInt(0)}
        
        validate := validator.New()
	validate.RegisterCustomTypeFunc(ValidateValuer, big.Int{})

	err := validate.Struct(s)
	fmt.Printf("%+v", err)
}

// ValidateValuer implements validator.CustomTypeFunc
func ValidateValuer(field reflect.Value) interface{} {
	n, ok := field.Interface().(big.Int)
	if !ok {
		return nil
	}

	return n.Int64()
}
```

**Comment by petrovi4ev** [comment]
@fairyhunter13 this does not work. I am trying to execute this simple test:

`	t.Run("big int validate", func(t *testing.T) {
		settings := config.InitSettings()
		settings.Main.Divider.SetInt64(0)

		// field Divider *big.Int`json:"divider" validate:"gte=10000000000"`
		errs := settings.Validate()
		assert.Equal(t, 1, len(errs))
	})`

**Comment by petrovi4ev** [comment]
Thanks it works
