### ISSUE TITLE
Pass multiple values to startsnotwith annotation

### ISSUE THREAD

**Issue by oriAdler** [go-playground/validator#864]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first? 
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
I'm trying to use the Baked-in validation for string.
I would like to make sure a string field doesn't start with ``.`` or ``space`` or ``,``.
Is it possible to pass multiple values to the ``startsnotwith`` annotation?

### Code sample, to showcase or reproduce:

```go
	Details           *string                       `json:"details,omitempty" validate:"startsnotwith=.`

```

**Comment by zemzale** [comment]
You can just chain them using OR. It would be something like this
```go
Details string `json:"details,omitempty" validate:"startsnotwith=.|startsnotwith= |startsnotwith=,` 
```

**Comment by oriAdler** [comment]
I did use the solution you provided and it works well.

I was hoping there is a shortened way to write this expression, something like:
`Details string json:"details,omitempty" validate:"startsnotwith= . | 0x2C | "`.

Thanks a lot.

**Comment by Octobug** [comment]
> I did use the solution you provided and it works well.
> 
> I was hoping there is a shortened way to write this expression, something like: `Details string json:"details,omitempty" validate:"startsnotwith= . | 0x2C | "`.
> 
> Thanks a lot.

It's a pity that there isn't.
