### ISSUE TITLE
Fail to try use required_if with boolean field value

### ISSUE THREAD

**Issue by torwald-sergesson** [go-playground/validator#869]
- [ + ] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ + ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v10

### Issue, Question or Enhancement:

Boolean fields cannot be used  for "required_if" and "required_unless" tags.

### Code sample, to showcase or reproduce:

```go
type S struct {
    Name string `validate:"required_if=IsAnonymous false"`
    IsAnonymous bool `validate:"requried"`
}
```

**Comment by ibreakthecloud** [comment]
was this fixed? I am facing this too.
