### ISSUE TITLE
json tag of a struct is not taking precedence of the field name

### ISSUE THREAD

**Issue by banjoh** [go-playground/validator#877]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:
I would like to use json tag names of structs when generating validation error translations. Unfortunately I'm not able to get the field name when I call `fe.Field()`. According to https://github.com/go-playground/validator/blob/v10.10.0/errors.go#L126, the json tag should have precedence if defined when evaluating the string to be returned.

I believe I'm missing something very basic here but I've ran out of ideas.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"log"

	"github.com/go-playground/validator/v10"
)

func main() {
	type User struct {
		Username string `validate:"required" json:"uname"`
	}

	validate := validator.New()
	err := validate.Struct(User{})
	errs := err.(validator.ValidationErrors)

	log.Printf("Field: %s", errs[0].Field()) // I expect to get "uname" printed out
}
```

Log output
```
2022/01/10 17:48:02 Field: Username
```

**Comment by banjoh** [comment]
I created a helper function that does this for me. If anyone finds themselves here they can utilise it as well

```go
func FindJsonTagName(i interface{}, original string) string {
	reflected := reflect.ValueOf(i)

	switch reflected.Kind() {
	case reflect.Ptr:
		reflected = reflected.Elem()
	case reflect.Struct:
		break
	default:
		// Fields that are not structs will be ignored
		return original
	}

	// Find the field from the struct and extract tag
	for i := 0; i < reflected.Type().NumField(); i++ {
		f := reflected.Type().Field(i)
		if f.Name == original {
			tag := f.Tag.Get("json")
			if tag != "" {
				return tag
			} else {
				return original
			}
		}
	}

	// Always return the original field name
	// We should never get here. If we do, it means the struct being
	// checked is the wrong one. The field should always be found.
	return original
}
```

Usage
```go
errs = err.(validator.ValidationErrors)
ts := map[string]string{}

for _, e := range errs {
	// Translate each error at a time
	fieldName := web.FindJsonTagName(dto, e.Field())
	ts[fieldName] = e.Translate(api.Router.Translator)
}
```

**Comment by deankarn** [comment]
@banjoh 

To use a tag name you need to tell validator to use one. This information os documented and even provides the JSON tag name example https://pkg.go.dev/github.com/go-playground/validator/v10#Validate.RegisterTagNameFunc

**Comment by banjoh** [comment]
I knew I was missing something very basic here. Works as expected.

Thanks a lot for the prompt response @deankarn
