### ISSUE TITLE
top level slice of structs

### ISSUE THREAD

**Issue by pete911** [go-playground/validator#882]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

We have a use case where we want to validate slice of structs. We cannot wrap the slice in a struct, because we need to return json array (not json object with array field). Current validator allows only validation if the input (top) is a struct (I know that we can add `dive` tag, but it is not possible to add tag to a slice e.g.:

```go
type Output []SomeStruct `validate"required,dive"` // does not compile, tags can be added only on struct type
---
type Output []SomeStruct
type OutputStruct struct {
    Output `validate"required,dive"` // json will wrap slice in "output", "output" is omitted only if the type is struct
}
```

### Code sample, to showcase or reproduce:

```go
	in := []struct {
		Value string `validate:"contains=@"`
	}{
		{Value: "test@1"}, {Value: "test@2"},
	}
	validate := New()
	errs := validate.Struct(in) // fails with InvalidValidationError
```
I understand that slice and map can be validated with `dive`, but as mentioned above it is imposible to add `dive` tag on the slice itself and we cannot wrap slice in a struct, because we need to return (json) array.

**Comment by pete911** [comment]
I've created a pull request #883 to "fix" (if you agree that this is a limitation of the validator).

**Comment by deankarn** [comment]
@pete911 is there any reason that `validate.Var(...)` doesn't work for this?

**Comment by pete911** [comment]
@deankarn thanks I wasn't aware of `validate.Var`. Looking at it, it requires additional argument `tag`. Our validator runs in interceptor/middleware, so we don't know if we are going to get struct, slice, ... 

It would be nice to have some generic method `validator.Validate(...)` that would check if the input type is:
- struct -> run `validate.Struct(...)`
- slice/map -> run `validate.Var(..., "dive")`

**Comment by deankarn** [comment]
@pete911 After reviewing and thinking about this for some time I think that it is better for the calling application to loop or to use the provided `validate.Var(...)`

I think that consumers may all have a different idea of how a generic `validator.Validate(..)` function might work. this is why the composition has been left up to the caller and the lowest level primitives provided.

Going to close this for now and as always thank you for your interest in `validator`!
