### ISSUE TITLE
How do I set different expressions for a field when another field meets certain conditions

### ISSUE THREAD

**Issue by zbwang163** [go-playground/validator#889]
- [ ] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

if field A equals 'a', the field B has expression 'b'. if field A equals 'aa', the field B has expression 'bb'.  How do I set different expressions for a field when another field meets certain conditions?

### Code sample, to showcase or reproduce:

```go
type Example struct{
    A string
    B string `if A='a' then len<10; if A='aa' then len<20`
}
```
how do I set expression for field B?
thanks

**Comment by zemzale** [comment]
Hey @zbwang163. 

There are no ways how to do it out of the box with the library. You are going to have to register a custom validation function. See here https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Custom_Validation_Functions
