### ISSUE TITLE
go-difflib is no longer maintained

### ISSUE THREAD

**Issue by tbankar** [go-playground/validator#903]
- [X ] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ X] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
github.com/pmezard/go-difflib is no longer maintained (EOLed) since 2016, kindly find an alternative.

### Code sample, to showcase or reproduce:

```go

```

**Comment by zemzale** [comment]
Hey @tbankar 

This library is a dependency of an indirect dependency. 

To explain it: 
- We require `github.com/leodido/go-urn` for validation rule `urn_rfc2141`
- `github.com/leodido/go-urn` requires `github.com/stretchr/testify`, but we don't use it meaning it's an indirect dependency
- `github.com/stretchr/testify` requires `github.com/pmezard/go-difflib` and that is why it's in our `go.sum` file

We simply can't change this fact without changing something in `github.com/stretchr/testify` or `github.com/leodido/go-urn`, but that is not really any of our concerns.
