### ISSUE TITLE
Enhanced ValidationCtx method to support nested map in slice

### ISSUE THREAD

**Issue by leftjs** [go-playground/validator#915]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
Enhanced ValidationCtx method to support nested map in slice

Currently ValidateCtx cannot support the validation method of nested map in slices, which makes ValidateCtx inconvenient to use. Can it be enhanced?

### Code sample, to showcase or reproduce:
test data like this
```go
data: map[string]interface{}{
	"Test_A": map[string]interface{}{
		"Test_B": "Test_B",
		"Test_C": []interface{}{"Test_D"},
		"Test_E": map[string]interface{}{
			"Test_F": "Test_F",
		},
		"Test_G": "Test_G",
		"Test_I": []map[string]interface{}{
			{
				"Test_J": "Test_J",
			},
		},
	},
},
rules: map[string]interface{}{
	"Test_A": map[string]interface{}{
		"Test_B": "min=2",
		"Test_C": map[string]interface{}{
			"Test_D": "min=2",
		},
		"Test_E": map[string]interface{}{
			"Test_F": "min=100",
		},
		"Test_G": map[string]interface{}{
			"Test_H": "min=2",
		},
		"Test_I": map[string]interface{}{
			"Test_J": "min=100",
		},
	},
},
```

**Comment by deankarn** [comment]
PR #915 merged
