### ISSUE TITLE
Can i get an addressable reflect.Value inside custom validation function?

### ISSUE THREAD

**Issue by AlAnwari-ari** [go-playground/validator#919]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 

v.10

### Issue, Question or Enhancement:

Question.
Why im getting an unadressable reflect inside custom validation (validator.FieldLevel)?
Can i get an addressable reflect inside custom validation?

### Code sample, to showcase or reproduce:

```go
func CustomValidator(fl validator.FieldLevel) bool {

// I have use all method from FieldLevel to get reflect.Value and got unadressable reflect.Value.

}
```

**Comment by deankarn** [comment]
@AlAnwari-ari no you will not be able to get an addressable field(s) within the validation function, this package is not designed to do that.

But if you're looking at changing values dynamically you can check out [mold](https://github.com/go-playground/mold) to set values etc. based on struct tags. It is not as robust in options/features as validator but will work for most situations.

**Comment by AlAnwari-ari** [comment]
@deankarn Thank you for your fast response, appreciate it very much! And thanks in advance for the clear answer and the option as my solution, will check the mold further. One of great libs for my golang apps! Thanks :D
