### ISSUE TITLE
"dive" tag doesn't work with fields that are pointers to slices

### ISSUE THREAD

**Issue by mattwelke** [go-playground/validator#920]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
Yes. The documentation includes information about the dive feature, and I believe I understand how it works in v10 of the library right now.
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?
Yes, the dive example does not use pointers.

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:

I'm editing legacy code where we used this library for validating data. Our structs look like this:

```go
type MetadataItem struct {
	Key   *string `json:"key" validate:"required,min=1"`
	Value *string `json:"value" validate:"required,min=1"`
}
type Search struct {
	Id       string          `json:"id" validate:"required"`
	Metadata *[]MetadataItem `json:"metadata" validate:"required"`
}
```

I noticed today that the code wasn't validating properly in some situations. It was when the items in the slice were invalid. I then learned about the "dive" tag. We didn't know about the dive tag a few years ago when we put this code into production because the README didn't mention it. When I add the dive tag and make a few small examples, it works great. It allows the validator to dive into (lol) the slice and do what it's supposed to do. No complains there.

My issue is that we coded our structs using pointers all over the place. We lacked a good understanding of how to do data validation in Go back then because we were learning Go at the time. We thought we needed to use pointers to be able to validate required properties so we put them on everything, even slices. Because of that, it would be a difficult refactor to change our code to use regular slices instead of pointers to slices.

And now, when I add the dive tag to the `*[]MetadataItem` field in my code above, it doesn't do what I expect it to. It returns an error: `Key: 'Search.Metadata' Error:Field validation for 'Metadata' failed on the 'dive' tag` when the pointer is nil. In my use case, this is valid data. It's an optional slice, that when provided, must have valid elements for each element of the slice.

Full example:

```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/go-playground/validator/v10"
)

type MetadataItem struct {
	Key   *string `json:"key" validate:"required,min=1"`
	Value *string `json:"value" validate:"required,min=1"`
}
type Search struct {
	Id       string          `json:"id" validate:"required"`
	Metadata *[]MetadataItem `json:"metadata" validate:"dive,required"`
}

fmt.Printf("test: %s\n", "no metadata")

var parsed Search
if err := json.Unmarshal([]byte(`{ "id": "abc123" }`), &parsed); err != nil {
	panic(err)
}

// Validate
validate := validator.New()
err := validate.Struct(parsed)
if err != nil {
	validationErrors := err.(validator.ValidationErrors)
	fmt.Printf("Validation errors: %+v\n", validationErrors)
} else {
	fmt.Printf("No errors.\n")
}

// Make into JSON again
marshaled, err := json.Marshal(parsed)
if err != nil {
	panic(fmt.Errorf("could not marshal: %w", err))
}
fmt.Printf("Marshaled: %s\n\n", marshaled)
```

In this situation, do I have to refactor my code to make it work with the way "dive" is set up today? Is there a way I could add tags to my structs to allow the validation to work without changing types? Or is this a feature that makes sense for the library to have, where if it's a pointer to a slice, with "dive", the library could dive into each element in the slice to validate the elements?

**Comment by deankarn** [comment]
@mattwelke  Haven't tested it but I think that `omit empty` might work for what your looking for eg. `validate:"dive,omitempty,required"`
