### ISSUE TITLE
Request Help:  How Define ' default_or'

### ISSUE THREAD

**Issue by zhixiongdu027** [go-playground/validator#927]
- [ Y ] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [ Y ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

we neec check a string  is      "" or match `hostname_rfc1123`

I looked at a lot of documentation, but didn't find a definition that satisfies this logic

Someone Can Help . TKS

### Code sample, to showcase or reproduce:

```go

```

**Comment by zemzale** [comment]
For this `omitempty,hostname_rfc1123` would do the trick if your string is not a pointer. 

`omitempty` would not fail the validation if the string is empty https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Omit_Empty

And then you just need to add the validation you require. 

I will close this, but if something doesn't work feel free to comment and reopen the issue.
