### ISSUE TITLE
error: reflect: reflect.Value.Set using unaddressable value

### ISSUE THREAD

**Issue by muhfaris** [go-playground/validator#928]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
How to create custom validation and populate the value?

In this case, is I create custom validation to add a default value for an empty field.
bot I got the error
```
=== RUN   TestValidateDefault
=== RUN   TestValidateDefault/default_string_without_value
--- FAIL: TestValidateDefault (0.00s)
    --- FAIL: TestValidateDefault/default_string_without_value (0.00s)
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value

```

### Code sample, to showcase or reproduce:

```go
// default.go
package customvalidation

import (
	"fmt"
	"reflect"
	"unsafe"

	"github.com/go-playground/validator/v10"
)

func ValidateDefault(fl validator.FieldLevel) bool {	
	field := fl.Field()

	if !field.IsZero() {
		return true
	}

	param := fl.Param()
	nv := reflect.ValueOf(&param).Elem()
	//	field = nv

	fl.Field().Set(nv)

	return true
}
```

```go
// default_test.go
package customvalidation

import (
	"testing"

	"github.com/go-playground/validator/v10"
)

const (
	defaultField    = "default"
	isPositiveField = "isPositive"
)

func TestValidateDefault(t *testing.T) {
	validate := validator.New()
	validate.RegisterValidation(defaultField, ValidateDefault)

	type args struct {
		Name string `validate:"default=faris"`
	}

	tests := []struct {
		name string
		args args
		want interface{}
	}{
		{
			name: "default string without value",
			want: "faris",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := validate.Struct(tt.args)
			if err != nil {
				t.Error(err)
			}

			if tt.args.Name != tt.want {
				t.Errorf("Expected: %v, but Got: %v", tt.want, tt.args.Name)
			}
		})
	}
}
```

**Comment by deankarn** [comment]
@muhfaris just a word of caution, it is not guaranteed that any field or data passed to the validation functions will be addressable or persist to the outer data structure as validator usually unwraps pointers, sometimes smart pointers, etc. to get down to the final data and type to validate.

github.com/go-playground/mold is designed to  keep data addressable, set default values and sanitize data prior to validation if that helps.

**Comment by muhfaris** [comment]
okay thank you @deankarn
