### ISSUE TITLE
Excluded_if Doesn't behave as expected

### ISSUE THREAD

**Issue by CorentinClabaut** [go-playground/validator#938]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version: 
v10

### Issue, Question or Enhancement:
Validator `excluded_if` doesn't behave as the documentation describes.
The documentation says:`The field under validation must not be present or not empty only if all the other specified fields are equal to the value following the specified field.`.
The validator does: `fail if any of the other specified fields are not equal to the value following the specified field.`

### Code sample, to showcase or reproduce:

```go
type Struct struct {
	Field1 string
	Field2 string `validate:"excluded_if=Field1 exclude"`
}

errs = validate.Struct(Struct{Field1: "dontExclude", Field2: "value"}) // -> Returns error, but shouldn't 
errs = validate.Struct(Struct{Field1: "dontExclude"}) // -> Returns error, but shouldn't
errs = validate.Struct(Struct{Field1: "exclude", Field2: "value"}) // -> Returns no error, but it should
```

**Comment by ilior** [comment]
It looks like current version of the "excluded_unless" validator is also wrong and works as the "excluded_if" should. As a temporary solution i used "excluded_unless"
