### ISSUE TITLE
Can I validate slice with contains some value ?

### ISSUE THREAD

**Issue by yuta-hidaka** [go-playground/validator#953]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

Hi all.

I'm trying to validate slice that on of contains some value.(Like below)
There is some type if validator ?
If there not I will create custom validator.

### Code sample, to showcase or reproduce:

```go
package main

import "github.com/go-playground/validator/v10"

type Test struct {
	s []bool `json:"operations" validate:"array-contains=true"`
}

func main() {
	var v Test
	validate := validator.New()

	// ==> this is will be valid
	v.s = append(v.s, true)
	v.s = append(v.s, false)
	_ = validate.Struct(v)

	// ==> this is will be invalid
	v.s = append(v.s, true)
	v.s = append(v.s, true)
	_ = validate.Struct(v)

}
```

**Comment by zemzale** [comment]
There is nothing that will behave like that, so you are gonna need a custom validator. https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Custom_Validation_Functions
