### ISSUE TITLE
err := validate.Struct(mystruct)  does not work

### ISSUE THREAD

**Issue by diogo-soares** [go-playground/validator#965]
i have a problem when i try to use

err := validate.Struct(user)

![image](https://user-images.githubusercontent.com/62112057/175199845-e9118f69-fcd0-4ebd-843c-5858c4c3db38.png)

**Comment by diogo-soares** [comment]
![image](https://user-images.githubusercontent.com/62112057/175201077-91a6b480-8ea0-4174-9e2b-dce6a108b9f0.png)

**Comment by deankarn** [comment]
Did you look at ANY examples or documentation?
