### ISSUE TITLE
why not work with this situation

### ISSUE THREAD

**Issue by youngkai** [go-playground/validator#973]
- [ x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x ] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:
[SignUpParam]         *work*      {"name":"q1mi","age":18,"email":"123.com"}
[Array]        *not work*    {"params": [{"name":"q1mi","age":18,"email":"123.com"}]}

### Code sample, to showcase or reproduce:

```go
type Array struct {
	Params []SignUpParam `json:"params" binding:""`
}

type SignUpParam struct {
	Age        uint8  `json:"age" binding:"gte=1,lte=130"`
	Name       string `json:"name" binding:"required"`
	Email      string `json:"email" binding:"required,email"`
	Password   string `json:"password" binding:"required"`
	RePassword string `json:"re_password" binding:"required,eqfield=Password"`
}
```

**Comment by deankarn** [comment]
Validator does not automatically traverse arrays or maps. You want to use the `dive` Tag to do that.

please take a look at the document.

**Comment by youngkai** [comment]
thanks, bro
