### ISSUE TITLE
Uninformative message when validating a struct field via Var()

### ISSUE THREAD

**Issue by Antonboom** [go-playground/validator#995]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-playground/validator/v10"
)

var v = validator.New()

type Options struct {
	pingPeriod time.Duration
}

func main() {
	opts := Options{pingPeriod: 10 * time.Minute}

	err := v.Var(opts.pingPeriod, "min=1s,max=1m")
	fmt.Println(err)
	// Key: '' Error:Field validation for '' failed on the 'max' tag
	//      ^^^                           ^^^
}
```

**Comment by Antonboom** [comment]
I think it is related to https://github.com/go-playground/validator/issues/417

**Comment by zemzale** [comment]
@Antonboom Indeed the unexported field is the issue here. I will close this in favor of that issue.
